// Generated by scripts/build-morph.mjs. Do not edit.
enum MetalMorphCatalog {
    static let names: Set<MetalIconName> = [.select, .text, .note, .image, .link, .draw, .pen, .marker, .line, .arrow, .rectangle, .ellipse, .eraser, .layout, .tidy, .search, .zoomIn, .zoomOut, .fit, .duplicate, .copy, .save, .download, .upload, .send, .external, .settings, .filter, .sort, .eye, .eyeOff, .lock, .stop, .attach, .retry, .person, .bell, .palette, .volume, .brightness, .sendAway, .trash, .group, .ungroup, .pin, .board, .share, .undo, .redo, .more, .close, .play, .pause, .check, .info, .warning, .sun, .moon, .sidebar, .sidebarCollapsed, .synced, .offline, .syncError, .capture, .paste, .plus, .minus, .chevron, .region, .task, .tag, .calendar, .document, .spark, .coin, .clock, .me, .seed]
}
