// Generated by scripts/build-icons.mjs from icons/src/icons.mjs. Do not edit.
// Each icon's act (docs/ICON-MOTION.md): the parts that move, their keyframes per property,
// and the inked elements they carry. Played by MetalIconActView.
import CoreGraphics

extension MetalIconAct {
    static let all: [MetalIconName: MetalIconAct] = [
        .select: MetalIconAct(
            duration: 0.9,
            caption: "The pointer draws back, clicks its tip down, and a ring opens where it lands.",
            parts: [
            MetalIconActPart(
                name: "cursor", origin: CGPoint(x: 6.1, y: 4.9),
                poses: [
                    .init(0.0, x: 0.0, y: 0.0, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.55, 0.0, 0.85, 0.45)),
                    .init(0.1667, x: 1.5, y: 1.5, r: 5.0, sx: 1.0, sy: 1.0, ease: .init(0.16, 0.75, 0.3, 0.95)),
                    .init(0.3333, x: -0.9, y: -0.9, r: -8.0, sx: 0.86, sy: 0.86, ease: .init(0.4, 0.0, 0.2, 1.0)),
                    .init(0.4444, x: -0.7, y: -0.7, r: -7.0, sx: 0.9, sy: 0.9, ease: .init(0.4, 0.0, 0.2, 1.0)),
                    .init(0.6222, x: 0.45, y: 0.45, r: 2.0, sx: 1.03, sy: 1.03, ease: .init(0.4, 0.0, 0.2, 1.0)),
                    .init(0.8, x: -0.12, y: -0.12, r: -0.6, sx: 1.0, sy: 1.0, ease: .init(0.22, 1.0, 0.36, 1.0)),
                    .init(1.0, x: 0.0, y: 0.0, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.4, 0.0, 0.2, 1.0)),
                ],
                opacity: [],
                draw: []
            ),
            MetalIconActPart(
                name: "click", origin: CGPoint(x: 6.1, y: 4.9),
                poses: [
                    .init(0.0, x: 0.0, y: 0.0, r: 0.0, sx: 0.3, sy: 0.3, ease: .linear),
                    .init(0.3222, x: 0.0, y: 0.0, r: 0.0, sx: 0.3, sy: 0.3, ease: .init(0.22, 1.0, 0.36, 1.0)),
                    .init(0.3778, x: 0.0, y: 0.0, r: 0.0, sx: 0.75, sy: 0.75, ease: .init(0.4, 0.0, 0.2, 1.0)),
                    .init(0.7111, x: 0.0, y: 0.0, r: 0.0, sx: 1.5, sy: 1.5, ease: .linear),
                    .init(1.0, x: 0.0, y: 0.0, r: 0.0, sx: 0.3, sy: 0.3, ease: .linear),
                ],
                opacity: [
                    .init(0.0, 0.0, ease: .linear),
                    .init(0.3222, 0.0, ease: .init(0.22, 1.0, 0.36, 1.0)),
                    .init(0.3778, 0.9, ease: .init(0.4, 0.0, 0.2, 1.0)),
                    .init(0.7111, 0.0, ease: .linear),
                    .init(1.0, 0.0, ease: .linear),
                ],
                draw: []
            ),
            ],
            ink: [
            MetalIconActInk(d: "M6.1 4.9L18.3 10.6C18.488 10.6833 18.6059 10.8732 18.597 11.0786C18.5882 11.2841 18.4545 11.4632 18.26 11.53L13 13.2L10.8 18.3C10.7206 18.4893 10.5335 18.6108 10.3282 18.6064C10.1229 18.602 9.9412 18.4726 9.87 18.28L6.1 4.9Z", parts: [0], stroke: 1.0, fill: .duotone(0.14), opacity: 1.0),
            MetalIconActInk(d: "M9.3 4.9C9.3 6.6673 7.8673 8.1 6.1 8.1C4.3327 8.1 2.9 6.6673 2.9 4.9C2.9 3.1327 4.3327 1.7 6.1 1.7C7.8673 1.7 9.3 3.1327 9.3 4.9Z", parts: [1], stroke: 0.7, fill: .none, opacity: 1.0),
            ]
        ),
        .layout: MetalIconAct(
            duration: 1.143,
            caption: "The panes are drawn apart, snap back onto the grid, and the gutter rule flashes where they seat.",
            parts: [
            MetalIconActPart(
                name: "tall", origin: CGPoint(x: 10.6, y: 12.0),
                poses: [
                    .init(0.0, x: 0.0, y: 0.0, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.4, 0.0, 0.2, 1.0)),
                    .init(0.1662, x: -1.1, y: 0.0, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.4, 0.0, 0.2, 1.0)),
                    .init(0.2187, x: -1.155, y: 0.0, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.55, 0.0, 0.85, 0.45)),
                    .init(0.3237, x: 0.0, y: 0.0, r: 0.0, sx: 0.84, sy: 1.06, ease: .init(0.37, 0.0, 0.63, 1.0)),
                    .init(0.6352, x: 0.0, y: 0.0, r: 0.0, sx: 1.0158, sy: 0.9941, ease: .init(0.37, 0.0, 0.63, 1.0)),
                    .init(0.9475, x: 0.0, y: 0.0, r: 0.0, sx: 1.0, sy: 1.0, ease: .linear),
                    .init(1.0, x: 0.0, y: 0.0, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.4, 0.0, 0.2, 1.0)),
                ],
                opacity: [],
                draw: []
            ),
            MetalIconActPart(
                name: "top", origin: CGPoint(x: 13.4, y: 7.1),
                poses: [
                    .init(0.0, x: 0.0, y: 0.0, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.4, 0.0, 0.2, 1.0)),
                    .init(0.1925, x: 1.3, y: 0.0, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.4, 0.0, 0.2, 1.0)),
                    .init(0.245, x: 1.365, y: 0.0, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.55, 0.0, 0.85, 0.45)),
                    .init(0.35, x: 0.0, y: 0.0, r: 0.0, sx: 0.84, sy: 1.06, ease: .init(0.37, 0.0, 0.63, 1.0)),
                    .init(0.6614, x: 0.0, y: 0.0, r: 0.0, sx: 1.0158, sy: 0.9941, ease: .init(0.37, 0.0, 0.63, 1.0)),
                    .init(0.9738, x: 0.0, y: 0.0, r: 0.0, sx: 1.0, sy: 1.0, ease: .linear),
                    .init(1.0, x: 0.0, y: 0.0, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.4, 0.0, 0.2, 1.0)),
                ],
                opacity: [],
                draw: []
            ),
            MetalIconActPart(
                name: "bottom", origin: CGPoint(x: 13.4, y: 16.9),
                poses: [
                    .init(0.0, x: 0.0, y: 0.0, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.4, 0.0, 0.2, 1.0)),
                    .init(0.2187, x: 1.3, y: 0.0, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.4, 0.0, 0.2, 1.0)),
                    .init(0.2712, x: 1.365, y: 0.0, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.55, 0.0, 0.85, 0.45)),
                    .init(0.3762, x: 0.0, y: 0.0, r: 0.0, sx: 0.84, sy: 1.06, ease: .init(0.37, 0.0, 0.63, 1.0)),
                    .init(0.6877, x: 0.0, y: 0.0, r: 0.0, sx: 1.0158, sy: 0.9941, ease: .init(0.37, 0.0, 0.63, 1.0)),
                    .init(1.0, x: 0.0, y: 0.0, r: 0.0, sx: 1.0, sy: 1.0, ease: .linear),
                ],
                opacity: [],
                draw: []
            ),
            MetalIconActPart(
                name: "rule", origin: CGPoint(x: 12.0, y: 12.0),
                poses: [
                    .init(0.0, x: 0.0, y: 0.0, r: 0.0, sx: 1.0, sy: 0.4, ease: .linear),
                    .init(0.3237, x: 0.0, y: 0.0, r: 0.0, sx: 1.0, sy: 0.4, ease: .init(0.16, 0.75, 0.3, 0.95)),
                    .init(0.3675, x: 0.0, y: 0.0, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.4, 0.0, 0.2, 1.0)),
                    .init(0.6649, x: 0.0, y: 0.0, r: 0.0, sx: 1.0, sy: 1.04, ease: .linear),
                    .init(1.0, x: 0.0, y: 0.0, r: 0.0, sx: 1.0, sy: 0.4, ease: .linear),
                ],
                opacity: [
                    .init(0.0, 0.0, ease: .linear),
                    .init(0.3237, 0.0, ease: .init(0.16, 0.75, 0.3, 0.95)),
                    .init(0.3675, 0.85, ease: .init(0.4, 0.0, 0.2, 1.0)),
                    .init(0.6649, 0.0, ease: .linear),
                    .init(1.0, 0.0, ease: .linear),
                ],
                draw: []
            ),
            ],
            ink: [
            MetalIconActInk(d: "M6 3.6L8.2 3.6C9.5255 3.6 10.6 4.6745 10.6 6L10.6 18C10.6 19.3255 9.5255 20.4 8.2 20.4L6 20.4C4.6745 20.4 3.6 19.3255 3.6 18L3.6 6C3.6 4.6745 4.6745 3.6 6 3.6Z", parts: [0], stroke: 1.0, fill: .duotone(0.16), opacity: 1.0),
            MetalIconActInk(d: "M15.8 3.6L18 3.6C19.3255 3.6 20.4 4.6745 20.4 6L20.4 8.2C20.4 9.5255 19.3255 10.6 18 10.6L15.8 10.6C14.4745 10.6 13.4 9.5255 13.4 8.2L13.4 6C13.4 4.6745 14.4745 3.6 15.8 3.6Z", parts: [1], stroke: 1.0, fill: .none, opacity: 1.0),
            MetalIconActInk(d: "M15.8 13.4L18 13.4C19.3255 13.4 20.4 14.4745 20.4 15.8L20.4 18C20.4 19.3255 19.3255 20.4 18 20.4L15.8 20.4C14.4745 20.4 13.4 19.3255 13.4 18L13.4 15.8C13.4 14.4745 14.4745 13.4 15.8 13.4Z", parts: [2], stroke: 1.0, fill: .none, opacity: 1.0),
            MetalIconActInk(d: "M12 4.6L12 19.4", parts: [3], stroke: 0.6, fill: .none, opacity: 1.0),
            ]
        ),
        .tidy: MetalIconAct(
            duration: 1.28,
            caption: "The loose pills are knocked square against the guide, and registration ticks flash where they sit flush.",
            parts: [
            MetalIconActPart(
                name: "guide", origin: CGPoint(x: 4.3, y: 12.0),
                poses: [
                    .init(0.0, x: 0.0, y: 0.0, r: 0.0, sx: 1.0, sy: 1.0, ease: .linear),
                    .init(0.2578, x: 0.0, y: 0.0, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.16, 0.75, 0.3, 0.95)),
                    .init(0.2891, x: -0.6, y: 0.0, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.37, 0.0, 0.63, 1.0)),
                    .init(0.5273, x: 0.0, y: 0.0, r: 0.0, sx: 1.0, sy: 1.0, ease: .linear),
                    .init(1.0, x: 0.0, y: 0.0, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.4, 0.0, 0.2, 1.0)),
                ],
                opacity: [],
                draw: []
            ),
            MetalIconActPart(
                name: "row1", origin: CGPoint(x: 8.8, y: 6.4),
                poses: [
                    .init(0.0, x: 0.0, y: 0.0, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.4, 0.0, 0.2, 1.0)),
                    .init(0.125, x: 0.7, y: 0.0, r: -2.0, sx: 1.0, sy: 1.0, ease: .init(0.55, 0.0, 0.85, 0.45)),
                    .init(0.2578, x: -1.6, y: 0.0, r: 5.0, sx: 0.86, sy: 1.08, ease: .init(0.37, 0.0, 0.63, 1.0)),
                    .init(0.4961, x: -1.6, y: 0.0, r: 5.0, sx: 1.0122, sy: 0.993, ease: .init(0.22, 1.0, 0.36, 1.0)),
                    .init(0.6563, x: -1.6, y: 0.0, r: 5.0, sx: 1.0, sy: 1.0, ease: .init(0.4, 0.0, 0.2, 1.0)),
                    .init(1.0, x: 0.0, y: 0.0, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.4, 0.0, 0.2, 1.0)),
                ],
                opacity: [],
                draw: []
            ),
            MetalIconActPart(
                name: "row2", origin: CGPoint(x: 10.0, y: 12.0),
                poses: [
                    .init(0.0, x: 0.0, y: 0.0, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.4, 0.0, 0.2, 1.0)),
                    .init(0.1484, x: 0.7, y: 0.0, r: 2.0, sx: 1.0, sy: 1.0, ease: .init(0.55, 0.0, 0.85, 0.45)),
                    .init(0.2813, x: -2.8, y: 0.0, r: -5.0, sx: 0.86, sy: 1.08, ease: .init(0.37, 0.0, 0.63, 1.0)),
                    .init(0.5195, x: -2.8, y: 0.0, r: -5.0, sx: 1.0122, sy: 0.993, ease: .init(0.22, 1.0, 0.36, 1.0)),
                    .init(0.625, x: -2.8, y: 0.0, r: -5.0, sx: 1.0, sy: 1.0, ease: .init(0.4, 0.0, 0.2, 1.0)),
                    .init(1.0, x: 0.0, y: 0.0, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.4, 0.0, 0.2, 1.0)),
                ],
                opacity: [],
                draw: []
            ),
            MetalIconActPart(
                name: "row3", origin: CGPoint(x: 8.1, y: 17.6),
                poses: [
                    .init(0.0, x: 0.0, y: 0.0, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.4, 0.0, 0.2, 1.0)),
                    .init(0.1719, x: 0.7, y: 0.0, r: -1.2, sx: 1.0, sy: 1.0, ease: .init(0.55, 0.0, 0.85, 0.45)),
                    .init(0.3047, x: -0.9, y: 0.0, r: 3.0, sx: 0.86, sy: 1.08, ease: .init(0.37, 0.0, 0.63, 1.0)),
                    .init(0.543, x: -0.9, y: 0.0, r: 3.0, sx: 1.0122, sy: 0.993, ease: .init(0.22, 1.0, 0.36, 1.0)),
                    .init(0.6367, x: -0.9, y: 0.0, r: 3.0, sx: 1.0, sy: 1.0, ease: .init(0.4, 0.0, 0.2, 1.0)),
                    .init(1.0, x: 0.0, y: 0.0, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.4, 0.0, 0.2, 1.0)),
                ],
                opacity: [],
                draw: []
            ),
            MetalIconActPart(
                name: "ticks", origin: CGPoint(x: 5.85, y: 12.0),
                poses: [
                    .init(0.0, x: 0.0, y: 0.0, r: 0.0, sx: 0.3, sy: 1.0, ease: .linear),
                    .init(0.2656, x: 0.0, y: 0.0, r: 0.0, sx: 0.3, sy: 1.0, ease: .init(0.16, 0.75, 0.3, 0.95)),
                    .init(0.3047, x: 0.0, y: 0.0, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.4, 0.0, 0.2, 1.0)),
                    .init(0.5, x: 0.0, y: 0.0, r: 0.0, sx: 1.2, sy: 1.0, ease: .linear),
                    .init(1.0, x: 0.0, y: 0.0, r: 0.0, sx: 0.3, sy: 1.0, ease: .linear),
                ],
                opacity: [
                    .init(0.0, 0.0, ease: .linear),
                    .init(0.2656, 0.0, ease: .init(0.16, 0.75, 0.3, 0.95)),
                    .init(0.3047, 0.9, ease: .init(0.4, 0.0, 0.2, 1.0)),
                    .init(0.5, 0.0, ease: .linear),
                    .init(1.0, 0.0, ease: .linear),
                ],
                draw: []
            ),
            ],
            ink: [
            MetalIconActInk(d: "M4.3 3.8L4.3 20.2", parts: [0], stroke: 1.0, fill: .none, opacity: 1.0),
            MetalIconActInk(d: "M10.6181 4.2333L19.1853 3.4838C20.2857 3.3875 21.2558 4.2015 21.352 5.3018L21.352 5.3018C21.4483 6.4022 20.6343 7.3723 19.534 7.4685L10.9667 8.2181C9.8663 8.3143 8.8963 7.5004 8.8 6.4L8.8 6.4C8.7037 5.2996 9.5177 4.3296 10.6181 4.2333Z", parts: [1], stroke: 1.0, fill: .duotone(0.14), opacity: 1.0),
            MetalIconActInk(d: "M12.1667 10.1819L16.7492 10.5828C17.8496 10.6791 18.6635 11.6492 18.5673 12.7495L18.5673 12.7495C18.471 13.8499 17.5009 14.6639 16.4006 14.5676L11.8181 14.1667C10.7177 14.0704 9.9037 13.1004 10 12L10 12C10.0963 10.8996 11.0663 10.0856 12.1667 10.1819Z", parts: [2], stroke: 1.0, fill: .duotone(0.14), opacity: 1.0),
            MetalIconActInk(d: "M9.9926 15.4981L16.983 15.1317C18.0861 15.0739 19.0271 15.9213 19.0849 17.0243L19.0849 17.0243C19.1427 18.1274 18.2954 19.0684 17.1923 19.1262L10.2019 19.4926C9.0989 19.5504 8.1578 18.7031 8.1 17.6L8.1 17.6C8.0422 16.4969 8.8895 15.5559 9.9926 15.4981Z", parts: [3], stroke: 1.0, fill: .duotone(0.14), opacity: 1.0),
            MetalIconActInk(d: "M5.4 6.4L6.3 6.4M5.4 12L6.3 12M5.4 17.6L6.3 17.6", parts: [4], stroke: 0.7, fill: .none, opacity: 1.0),
            ]
        ),
        .search: MetalIconAct(
            duration: 1.12,
            caption: "The lens is swept across the field and stops; the focus closes in and a glint crosses the glass.",
            parts: [
            MetalIconActPart(
                name: "tool", origin: CGPoint(x: 19.8, y: 19.8),
                poses: [
                    .init(0.0, x: 0.0, y: 0.0, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.4, 0.0, 0.2, 1.0)),
                    .init(0.1607, x: 0.0, y: 0.0, r: 6.0, sx: 1.0, sy: 1.0, ease: .init(0.16, 0.75, 0.3, 0.95)),
                    .init(0.3393, x: 0.0, y: 0.0, r: -10.5, sx: 1.0, sy: 1.0, ease: .init(0.4, 0.0, 0.2, 1.0)),
                    .init(0.4286, x: 0.0, y: 0.0, r: -6.3, sx: 1.0, sy: 1.0, ease: .init(0.4, 0.0, 0.2, 1.0)),
                    .init(0.5179, x: 0.0, y: 0.0, r: -7.3, sx: 1.0, sy: 1.0, ease: .init(0.22, 1.0, 0.36, 1.0)),
                    .init(0.6786, x: 0.0, y: 0.0, r: -7.0, sx: 1.0, sy: 1.0, ease: .init(0.4, 0.0, 0.2, 1.0)),
                    .init(0.8571, x: 0.0, y: 0.0, r: 0.9, sx: 1.0, sy: 1.0, ease: .init(0.4, 0.0, 0.2, 1.0)),
                    .init(1.0, x: 0.0, y: 0.0, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.4, 0.0, 0.2, 1.0)),
                ],
                opacity: [],
                draw: []
            ),
            MetalIconActPart(
                name: "focus", origin: CGPoint(x: 10.6, y: 10.6),
                poses: [
                    .init(0.0, x: 0.0, y: 0.0, r: 0.0, sx: 2.1, sy: 2.1, ease: .linear),
                    .init(0.3571, x: 0.0, y: 0.0, r: 0.0, sx: 2.1, sy: 2.1, ease: .init(0.22, 1.0, 0.36, 1.0)),
                    .init(0.4821, x: 0.0, y: 0.0, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.4, 0.0, 0.2, 1.0)),
                    .init(0.625, x: 0.0, y: 0.0, r: 0.0, sx: 0.8, sy: 0.8, ease: .linear),
                    .init(1.0, x: 0.0, y: 0.0, r: 0.0, sx: 2.1, sy: 2.1, ease: .linear),
                ],
                opacity: [
                    .init(0.0, 0.0, ease: .linear),
                    .init(0.3571, 0.0, ease: .init(0.22, 1.0, 0.36, 1.0)),
                    .init(0.4821, 0.85, ease: .init(0.4, 0.0, 0.2, 1.0)),
                    .init(0.625, 0.0, ease: .linear),
                    .init(1.0, 0.0, ease: .linear),
                ],
                draw: []
            ),
            MetalIconActPart(
                name: "glint", origin: CGPoint(x: 10.6, y: 10.6),
                poses: [
                    .init(0.0, x: 0.0, y: 0.0, r: -40.0, sx: 1.0, sy: 1.0, ease: .linear),
                    .init(0.4464, x: 0.0, y: 0.0, r: -40.0, sx: 1.0, sy: 1.0, ease: .init(0.4, 0.0, 0.2, 1.0)),
                    .init(0.5536, x: 0.0, y: 0.0, r: 5.0, sx: 1.0, sy: 1.0, ease: .init(0.4, 0.0, 0.2, 1.0)),
                    .init(0.75, x: 0.0, y: 0.0, r: 50.0, sx: 1.0, sy: 1.0, ease: .linear),
                    .init(1.0, x: 0.0, y: 0.0, r: -40.0, sx: 1.0, sy: 1.0, ease: .linear),
                ],
                opacity: [
                    .init(0.0, 0.0, ease: .linear),
                    .init(0.4464, 0.0, ease: .init(0.4, 0.0, 0.2, 1.0)),
                    .init(0.5536, 0.75, ease: .init(0.4, 0.0, 0.2, 1.0)),
                    .init(0.75, 0.0, ease: .linear),
                    .init(1.0, 0.0, ease: .linear),
                ],
                draw: []
            ),
            ],
            ink: [
            MetalIconActInk(d: "M16.9 10.6C16.9 14.0794 14.0794 16.9 10.6 16.9C7.1206 16.9 4.3 14.0794 4.3 10.6C4.3 7.1206 7.1206 4.3 10.6 4.3C14.0794 4.3 16.9 7.1206 16.9 10.6Z", parts: [0], stroke: 1.0, fill: .none, opacity: 1.0),
            MetalIconActInk(d: "M15.2 15.2L19.8 19.8", parts: [0], stroke: 1.0, fill: .none, opacity: 1.0),
            MetalIconActInk(d: "M12.6 10.6C12.6 11.7046 11.7046 12.6 10.6 12.6C9.4954 12.6 8.6 11.7046 8.6 10.6C8.6 9.4954 9.4954 8.6 10.6 8.6C11.7046 8.6 12.6 9.4954 12.6 10.6Z", parts: [0, 1], stroke: 0.6, fill: .none, opacity: 1.0),
            MetalIconActInk(d: "M7.6 9.1C7.935 8.3996 8.4996 7.835 9.2 7.5", parts: [0, 2], stroke: 0.8, fill: .none, opacity: 1.0),
            ]
        ),
        .zoomIn: MetalIconAct(
            duration: 1.14,
            caption: "The lens is pushed in along its handle and the plus under it is magnified.",
            parts: [
            MetalIconActPart(
                name: "tool", origin: CGPoint(x: 19.8, y: 19.8),
                poses: [
                    .init(0.0, x: 0.0, y: 0.0, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.4, 0.0, 0.2, 1.0)),
                    .init(0.1404, x: 0.6, y: 0.6, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.16, 0.75, 0.3, 0.95)),
                    .init(0.307, x: -1.45, y: -1.45, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.37, 0.0, 0.63, 1.0)),
                    .init(0.5746, x: -1.2, y: -1.2, r: 0.0, sx: 1.0, sy: 1.0, ease: .linear),
                    .init(0.6316, x: -1.2, y: -1.2, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.4, 0.0, 0.2, 1.0)),
                    .init(0.8421, x: 0.2, y: 0.2, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.4, 0.0, 0.2, 1.0)),
                    .init(1.0, x: 0.0, y: 0.0, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.4, 0.0, 0.2, 1.0)),
                ],
                opacity: [],
                draw: []
            ),
            MetalIconActPart(
                name: "sign", origin: CGPoint(x: 10.6, y: 10.6),
                poses: [
                    .init(0.0, x: 0.0, y: 0.0, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.4, 0.0, 0.2, 1.0)),
                    .init(0.1404, x: 0.0, y: 0.0, r: 0.0, sx: 0.94, sy: 0.94, ease: .init(0.55, 0.0, 0.85, 0.45)),
                    .init(0.307, x: 0.0, y: 0.0, r: 0.0, sx: 1.05, sy: 1.05, ease: .init(0.16, 0.75, 0.3, 0.95)),
                    .init(0.3421, x: 0.0, y: 0.0, r: 0.0, sx: 1.36, sy: 1.36, ease: .init(0.37, 0.0, 0.63, 1.0)),
                    .init(0.6096, x: 0.0, y: 0.0, r: 0.0, sx: 1.2948, sy: 1.2948, ease: .init(0.37, 0.0, 0.63, 1.0)),
                    .init(0.6667, x: 0.0, y: 0.0, r: 0.0, sx: 1.3, sy: 1.3, ease: .init(0.4, 0.0, 0.2, 1.0)),
                    .init(0.8947, x: 0.0, y: 0.0, r: 0.0, sx: 0.97, sy: 0.97, ease: .init(0.4, 0.0, 0.2, 1.0)),
                    .init(1.0, x: 0.0, y: 0.0, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.4, 0.0, 0.2, 1.0)),
                ],
                opacity: [],
                draw: []
            ),
            MetalIconActPart(
                name: "throw", origin: CGPoint(x: 10.6, y: 10.6),
                poses: [
                    .init(0.0, x: 0.0, y: 0.0, r: 0.0, sx: 1.0, sy: 1.0, ease: .linear),
                    .init(0.3421, x: 0.0, y: 0.0, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.22, 1.0, 0.36, 1.0)),
                    .init(0.4035, x: 0.0, y: 0.0, r: 0.0, sx: 1.15, sy: 1.15, ease: .init(0.4, 0.0, 0.2, 1.0)),
                    .init(0.614, x: 0.0, y: 0.0, r: 0.0, sx: 1.2, sy: 1.2, ease: .linear),
                    .init(1.0, x: 0.0, y: 0.0, r: 0.0, sx: 1.0, sy: 1.0, ease: .linear),
                ],
                opacity: [
                    .init(0.0, 0.0, ease: .linear),
                    .init(0.3421, 0.0, ease: .init(0.22, 1.0, 0.36, 1.0)),
                    .init(0.4035, 0.85, ease: .init(0.4, 0.0, 0.2, 1.0)),
                    .init(0.614, 0.0, ease: .linear),
                    .init(1.0, 0.0, ease: .linear),
                ],
                draw: []
            ),
            ],
            ink: [
            MetalIconActInk(d: "M16.9 10.6C16.9 14.0794 14.0794 16.9 10.6 16.9C7.1206 16.9 4.3 14.0794 4.3 10.6C4.3 7.1206 7.1206 4.3 10.6 4.3C14.0794 4.3 16.9 7.1206 16.9 10.6Z", parts: [0], stroke: 1.0, fill: .none, opacity: 1.0),
            MetalIconActInk(d: "M15.2 15.2L19.8 19.8", parts: [0], stroke: 1.0, fill: .none, opacity: 1.0),
            MetalIconActInk(d: "M8.2 10.6L13 10.6M10.6 8.2L10.6 13", parts: [0, 1], stroke: 1.0, fill: .none, opacity: 1.0),
            MetalIconActInk(d: "M13.15 8.05L13.65 7.55M13.15 13.15L13.65 13.65M8.05 13.15L7.55 13.65M8.05 8.05L7.55 7.55", parts: [0, 2], stroke: 0.7471, fill: .none, opacity: 1.0),
            ]
        ),
        .zoomOut: MetalIconAct(
            duration: 1.14,
            caption: "The lens is drawn back along its handle; the minus recedes and the old view closes in.",
            parts: [
            MetalIconActPart(
                name: "tool", origin: CGPoint(x: 19.8, y: 19.8),
                poses: [
                    .init(0.0, x: 0.0, y: 0.0, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.4, 0.0, 0.2, 1.0)),
                    .init(0.1316, x: -0.5, y: -0.5, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.16, 0.75, 0.3, 0.95)),
                    .init(0.3158, x: 1.3, y: 1.3, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.37, 0.0, 0.63, 1.0)),
                    .init(0.5833, x: 1.1, y: 1.1, r: 0.0, sx: 1.0, sy: 1.0, ease: .linear),
                    .init(0.6316, x: 1.1, y: 1.1, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.4, 0.0, 0.2, 1.0)),
                    .init(0.8421, x: -0.2, y: -0.2, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.4, 0.0, 0.2, 1.0)),
                    .init(1.0, x: 0.0, y: 0.0, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.4, 0.0, 0.2, 1.0)),
                ],
                opacity: [],
                draw: []
            ),
            MetalIconActPart(
                name: "sign", origin: CGPoint(x: 10.6, y: 10.6),
                poses: [
                    .init(0.0, x: 0.0, y: 0.0, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.4, 0.0, 0.2, 1.0)),
                    .init(0.1316, x: 0.0, y: 0.0, r: 0.0, sx: 1.06, sy: 1.06, ease: .init(0.55, 0.0, 0.85, 0.45)),
                    .init(0.3158, x: 0.0, y: 0.0, r: 0.0, sx: 0.92, sy: 0.92, ease: .init(0.16, 0.75, 0.3, 0.95)),
                    .init(0.3509, x: 0.0, y: 0.0, r: 0.0, sx: 0.66, sy: 0.66, ease: .init(0.37, 0.0, 0.63, 1.0)),
                    .init(0.6184, x: 0.0, y: 0.0, r: 0.0, sx: 0.7035, sy: 0.7035, ease: .init(0.37, 0.0, 0.63, 1.0)),
                    .init(0.6667, x: 0.0, y: 0.0, r: 0.0, sx: 0.7, sy: 0.7, ease: .init(0.4, 0.0, 0.2, 1.0)),
                    .init(0.8947, x: 0.0, y: 0.0, r: 0.0, sx: 1.03, sy: 1.03, ease: .init(0.4, 0.0, 0.2, 1.0)),
                    .init(1.0, x: 0.0, y: 0.0, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.4, 0.0, 0.2, 1.0)),
                ],
                opacity: [],
                draw: []
            ),
            MetalIconActPart(
                name: "field", origin: CGPoint(x: 10.6, y: 10.6),
                poses: [
                    .init(0.0, x: 0.0, y: 0.0, r: 0.0, sx: 1.2, sy: 1.2, ease: .linear),
                    .init(0.3333, x: 0.0, y: 0.0, r: 0.0, sx: 1.2, sy: 1.2, ease: .init(0.22, 1.0, 0.36, 1.0)),
                    .init(0.4211, x: 0.0, y: 0.0, r: 0.0, sx: 1.05, sy: 1.05, ease: .init(0.4, 0.0, 0.2, 1.0)),
                    .init(0.614, x: 0.0, y: 0.0, r: 0.0, sx: 0.8, sy: 0.8, ease: .linear),
                    .init(1.0, x: 0.0, y: 0.0, r: 0.0, sx: 1.2, sy: 1.2, ease: .linear),
                ],
                opacity: [
                    .init(0.0, 0.0, ease: .linear),
                    .init(0.3333, 0.0, ease: .init(0.22, 1.0, 0.36, 1.0)),
                    .init(0.4211, 0.85, ease: .init(0.4, 0.0, 0.2, 1.0)),
                    .init(0.614, 0.0, ease: .linear),
                    .init(1.0, 0.0, ease: .linear),
                ],
                draw: []
            ),
            ],
            ink: [
            MetalIconActInk(d: "M16.9 10.6C16.9 14.0794 14.0794 16.9 10.6 16.9C7.1206 16.9 4.3 14.0794 4.3 10.6C4.3 7.1206 7.1206 4.3 10.6 4.3C14.0794 4.3 16.9 7.1206 16.9 10.6Z", parts: [0], stroke: 1.0, fill: .none, opacity: 1.0),
            MetalIconActInk(d: "M15.2 15.2L19.8 19.8", parts: [0], stroke: 1.0, fill: .none, opacity: 1.0),
            MetalIconActInk(d: "M8.2 10.6L13 10.6", parts: [0, 1], stroke: 1.0, fill: .none, opacity: 1.0),
            MetalIconActInk(d: "M7.4 8.3L7.4 7.4L8.3 7.4M12.9 7.4L13.8 7.4L13.8 8.3M13.8 12.9L13.8 13.8L12.9 13.8M8.3 13.8L7.4 13.8L7.4 12.9", parts: [0, 2], stroke: 0.6, fill: .none, opacity: 1.0),
            ]
        ),
        .fit: MetalIconAct(
            duration: 1.16,
            caption: "The content grows to the frame and the four corners clamp onto it; the open sides of the frame flash shut.",
            parts: [
            MetalIconActPart(
                name: "nw", origin: CGPoint(x: 12.0, y: 12.0),
                poses: [
                    .init(0.0, x: 0.0, y: 0.0, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.4, 0.0, 0.2, 1.0)),
                    .init(0.1379, x: -0.5, y: -0.5, r: 0.0, sx: 1.0, sy: 1.0, ease: .linear),
                    .init(0.2241, x: -0.5, y: -0.5, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.16, 0.75, 0.3, 0.95)),
                    .init(0.3276, x: 1.3, y: 1.3, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.4, 0.0, 0.2, 1.0)),
                    .init(0.4052, x: 1.0, y: 1.0, r: 0.0, sx: 1.0, sy: 1.0, ease: .linear),
                    .init(0.6207, x: 1.0, y: 1.0, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.37, 0.0, 0.63, 1.0)),
                    .init(0.8914, x: 0.0, y: 0.0, r: 0.0, sx: 1.0, sy: 1.0, ease: .linear),
                    .init(1.0, x: 0.0, y: 0.0, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.4, 0.0, 0.2, 1.0)),
                ],
                opacity: [],
                draw: []
            ),
            MetalIconActPart(
                name: "ne", origin: CGPoint(x: 12.0, y: 12.0),
                poses: [
                    .init(0.0, x: 0.0, y: 0.0, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.4, 0.0, 0.2, 1.0)),
                    .init(0.1379, x: 0.5, y: -0.5, r: 0.0, sx: 1.0, sy: 1.0, ease: .linear),
                    .init(0.2241, x: 0.5, y: -0.5, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.16, 0.75, 0.3, 0.95)),
                    .init(0.3276, x: -1.3, y: 1.3, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.4, 0.0, 0.2, 1.0)),
                    .init(0.4052, x: -1.0, y: 1.0, r: 0.0, sx: 1.0, sy: 1.0, ease: .linear),
                    .init(0.6207, x: -1.0, y: 1.0, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.37, 0.0, 0.63, 1.0)),
                    .init(0.8914, x: 0.0, y: 0.0, r: 0.0, sx: 1.0, sy: 1.0, ease: .linear),
                    .init(1.0, x: 0.0, y: 0.0, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.4, 0.0, 0.2, 1.0)),
                ],
                opacity: [],
                draw: []
            ),
            MetalIconActPart(
                name: "se", origin: CGPoint(x: 12.0, y: 12.0),
                poses: [
                    .init(0.0, x: 0.0, y: 0.0, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.4, 0.0, 0.2, 1.0)),
                    .init(0.1379, x: 0.5, y: 0.5, r: 0.0, sx: 1.0, sy: 1.0, ease: .linear),
                    .init(0.2241, x: 0.5, y: 0.5, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.16, 0.75, 0.3, 0.95)),
                    .init(0.3276, x: -1.3, y: -1.3, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.4, 0.0, 0.2, 1.0)),
                    .init(0.4052, x: -1.0, y: -1.0, r: 0.0, sx: 1.0, sy: 1.0, ease: .linear),
                    .init(0.6207, x: -1.0, y: -1.0, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.37, 0.0, 0.63, 1.0)),
                    .init(0.8914, x: 0.0, y: 0.0, r: 0.0, sx: 1.0, sy: 1.0, ease: .linear),
                    .init(1.0, x: 0.0, y: 0.0, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.4, 0.0, 0.2, 1.0)),
                ],
                opacity: [],
                draw: []
            ),
            MetalIconActPart(
                name: "sw", origin: CGPoint(x: 12.0, y: 12.0),
                poses: [
                    .init(0.0, x: 0.0, y: 0.0, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.4, 0.0, 0.2, 1.0)),
                    .init(0.1379, x: -0.5, y: 0.5, r: 0.0, sx: 1.0, sy: 1.0, ease: .linear),
                    .init(0.2241, x: -0.5, y: 0.5, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.16, 0.75, 0.3, 0.95)),
                    .init(0.3276, x: 1.3, y: -1.3, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.4, 0.0, 0.2, 1.0)),
                    .init(0.4052, x: 1.0, y: -1.0, r: 0.0, sx: 1.0, sy: 1.0, ease: .linear),
                    .init(0.6207, x: 1.0, y: -1.0, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.37, 0.0, 0.63, 1.0)),
                    .init(0.8914, x: 0.0, y: 0.0, r: 0.0, sx: 1.0, sy: 1.0, ease: .linear),
                    .init(1.0, x: 0.0, y: 0.0, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.4, 0.0, 0.2, 1.0)),
                ],
                opacity: [],
                draw: []
            ),
            MetalIconActPart(
                name: "content", origin: CGPoint(x: 12.0, y: 12.0),
                poses: [
                    .init(0.0, x: 0.0, y: 0.0, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.4, 0.0, 0.2, 1.0)),
                    .init(0.1379, x: 0.0, y: 0.0, r: 0.0, sx: 0.92, sy: 0.92, ease: .init(0.16, 0.75, 0.3, 0.95)),
                    .init(0.3103, x: 0.0, y: 0.0, r: 0.0, sx: 1.4484, sy: 1.4484, ease: .init(0.4, 0.0, 0.2, 1.0)),
                    .init(0.3276, x: 0.0, y: 0.0, r: 0.0, sx: 1.349, sy: 1.349, ease: .init(0.37, 0.0, 0.63, 1.0)),
                    .init(0.5905, x: 0.0, y: 0.0, r: 0.0, sx: 1.4262, sy: 1.4262, ease: .init(0.37, 0.0, 0.63, 1.0)),
                    .init(0.6207, x: 0.0, y: 0.0, r: 0.0, sx: 1.42, sy: 1.42, ease: .init(0.4, 0.0, 0.2, 1.0)),
                    .init(0.8793, x: 0.0, y: 0.0, r: 0.0, sx: 0.97, sy: 0.97, ease: .init(0.22, 1.0, 0.36, 1.0)),
                    .init(1.0, x: 0.0, y: 0.0, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.4, 0.0, 0.2, 1.0)),
                ],
                opacity: [],
                draw: []
            ),
            MetalIconActPart(
                name: "seams", origin: CGPoint(x: 12.0, y: 12.0),
                poses: [
                    .init(0.0, x: 0.0, y: 0.0, r: 0.0, sx: 1.1, sy: 1.1, ease: .linear),
                    .init(0.3362, x: 0.0, y: 0.0, r: 0.0, sx: 1.1, sy: 1.1, ease: .init(0.16, 0.75, 0.3, 0.95)),
                    .init(0.3879, x: 0.0, y: 0.0, r: 0.0, sx: 1.0, sy: 1.0, ease: .init(0.4, 0.0, 0.2, 1.0)),
                    .init(0.6034, x: 0.0, y: 0.0, r: 0.0, sx: 1.06, sy: 1.06, ease: .linear),
                    .init(1.0, x: 0.0, y: 0.0, r: 0.0, sx: 1.1, sy: 1.1, ease: .linear),
                ],
                opacity: [
                    .init(0.0, 0.0, ease: .linear),
                    .init(0.3362, 0.0, ease: .init(0.16, 0.75, 0.3, 0.95)),
                    .init(0.3879, 0.8, ease: .init(0.4, 0.0, 0.2, 1.0)),
                    .init(0.6034, 0.0, ease: .linear),
                    .init(1.0, 0.0, ease: .linear),
                ],
                draw: []
            ),
            ],
            ink: [
            MetalIconActInk(d: "M3.8 8.6L3.8 6.4C3.8 4.9641 4.9641 3.8 6.4 3.8L8.6 3.8", parts: [0], stroke: 1.0, fill: .none, opacity: 1.0),
            MetalIconActInk(d: "M15.4 3.8L17.6 3.8C19.0359 3.8 20.2 4.9641 20.2 6.4L20.2 8.6", parts: [1], stroke: 1.0, fill: .none, opacity: 1.0),
            MetalIconActInk(d: "M20.2 15.4L20.2 17.6C20.2 19.0359 19.0359 20.2 17.6 20.2L15.4 20.2", parts: [2], stroke: 1.0, fill: .none, opacity: 1.0),
            MetalIconActInk(d: "M8.6 20.2L6.4 20.2C4.9641 20.2 3.8 19.0359 3.8 17.6L3.8 15.4", parts: [3], stroke: 1.0, fill: .none, opacity: 1.0),
            MetalIconActInk(d: "M10.7 9L13.3 9C14.2389 9 15 9.7611 15 10.7L15 13.3C15 14.2389 14.2389 15 13.3 15L10.7 15C9.7611 15 9 14.2389 9 13.3L9 10.7C9 9.7611 9.7611 9 10.7 9Z", parts: [4], stroke: 1.0, fill: .duotone(0.18), opacity: 1.0),
            MetalIconActInk(d: "M10.9 4.8L13.1 4.8M19.2 10.9L19.2 13.1M13.1 19.2L10.9 19.2M4.8 13.1L4.8 10.9", parts: [5], stroke: 0.6, fill: .none, opacity: 1.0),
            ]
        ),
    ]
}
