// @unlocalhosted/metalui/gadgets: the gadget foundations (materials lit by one light).
export { GADGETS, GADGET_MATERIALS, type GadgetMaterial } from './gadgets/gadgets.generated';
export { pigment, deltaE, type Pigment } from './gadgets/color';
export { materialFilter, holeFilter, bodyFill, tierFor, type Tier, type Host, type LightOptions } from './gadgets/light';
export { normalize, JOBS, MATERIALS, PARTS, MECHANISMS, type Job, type Feel, type GadgetSpec, type RigSpec, type PartPlacement, type Channel, type Value } from './gadgets/spec';
export { resolve, resolveFeel, materialFor, bodyColor, accentFor, checkSet, type ResolvedFeel, type ResolvedGadget, type Placement, type SetProblem } from './gadgets/resolve';
export { validate, validateGadget, validateRig, type Problem, type ProblemCode, type Validation } from './gadgets/validate';
export { simulateCvd } from './gadgets/color';
export { MECHANISMS as MECHANISM_TIMELINES } from './gadgets/mechanisms.generated';
export { createPlayer, sampleTrack, bezier, REST, type Player, type PlayerOptions, type CueEvent, type Cue, type Pose, type MechanismName } from './gadgets/player';
export { drawSlab, slabPath, cutPath, floorColor, roundedRect, type Cut, type CutKind, type SlabSpec } from './gadgets/parts/slab';
export { useHost } from './gadgets/host';
export { drawJack, type JackSpec } from './gadgets/parts/jack';
export { drawPlug, type PlugSpec } from './gadgets/parts/plug';
export { cableControls, cablePath, cableSag, createCableSwing, drawCable, type CableSpec, type CableSwing } from './gadgets/parts/cable';
export { beeperEnvelope, drawBeeper, playBeeper, type BeeperSpec } from './gadgets/parts/beeper';
export { drawCap, pressCap, type CapSpec, type CapShape } from './gadgets/parts/cap';
export { drawLamp, LAMP_COLORS, type LampSpec } from './gadgets/parts/led';
export { drawGadget, driveTargets, driveDefault, renderGadgetSvg, describeGadget, formPoses, stateOf, type GadgetDraw, type DrawOptions } from './gadgets/draw';
export { Gadget, type GadgetProps } from './gadgets/Gadget';
export { createDrive, DriveModel, type Drive, type DriveEvent, type DriveName, type DriveOptions } from './gadgets/drive';
