// Generated by scripts/build-icons.mjs from icons/src/icons.mjs. Do not edit.
// Each entry opens with its motion storyboard; `pressMs` is the press track's full length (TIMING).
export interface IconRecord {
  label: string;
  category: 'Tools' | 'Actions' | 'Status';
  hover: string;
  press: string;
  /** Ms from press to the end of the longest press track. */
  pressMs: number;
  defs: string;
  body: string;
  /** Simplified geometry for 16px and below, when the master clogs. */
  body16?: string;
  sw16: number;
}

export const ICON_CATALOG = {
  /* ─────────────────────────────────────────────────────────
   * SELECT · Tools
   *
   * HOVER pose (spring, reversible, interruptible)
   *          tilts onto its tip
   * PRESS one-shot (from the current pose)
   *          clicks: tip dips, a ring leaves the point
   *     0ms   .cur plays sel-p (340ms)
   *     0ms   .rip plays sel-r (440ms)
   * REDUCED MOTION   static glyph
   * ───────────────────────────────────────────────────────── */
  "select": {
    label: "Select",
    category: "Tools",
    hover: "tilts onto its tip",
    press: "clicks: tip dips, a ring leaves the point",
    pressMs: 440,
    defs: "",
    body: "<g class=\"cur\"><path class=\"f\" d=\"M6.1 4.9 18.3 10.6a.5.5 0 0 1-.04.93L13 13.2l-2.2 5.1a.5.5 0 0 1-.93-.02L6.1 4.9Z\"/></g><circle class=\"rip\" cx=\"6.1\" cy=\"4.9\" r=\"3.2\"/>",
    sw16: 1.85,
  },
  /* ─────────────────────────────────────────────────────────
   * TEXT · Tools
   *
   * HOVER pose (spring, reversible, interruptible)
   *          glyph steps aside, caret appears and blinks
   * PRESS one-shot (from the current pose)
   *          glyph stamps down
   *     0ms   .tg plays txt-p (300ms)
   * REDUCED MOTION   static glyph
   * ───────────────────────────────────────────────────────── */
  "text": {
    label: "Text",
    category: "Tools",
    hover: "glyph steps aside, caret appears and blinks",
    press: "glyph stamps down",
    pressMs: 300,
    defs: "",
    body: "<g class=\"tg\"><path d=\"M6.2 7.3V6.4a1.2 1.2 0 0 1 1.2-1.2h9.2a1.2 1.2 0 0 1 1.2 1.2v.9\"/><path d=\"M12 5.2v13.6M9.6 18.8h4.8\"/></g><path class=\"car\" d=\"M19.4 12.9v6.2\"/>",
    sw16: 1.85,
  },
  /* ─────────────────────────────────────────────────────────
   * NOTE · Tools
   *
   * HOVER pose (spring, reversible, interruptible)
   *          corner curls up
   * PRESS one-shot (from the current pose)
   *          lines write themselves in
   *     0ms   .nl plays note-w (360ms)
   *    60ms   .n2 plays (inherits) (360ms)
   * REDUCED MOTION   static glyph
   * ───────────────────────────────────────────────────────── */
  "note": {
    label: "Note",
    category: "Tools",
    hover: "corner curls up",
    press: "lines write themselves in",
    pressMs: 420,
    defs: "",
    body: "<path class=\"nb\" d=\"M20.5 14.2V7A3.5 3.5 0 0 0 17 3.5H7A3.5 3.5 0 0 0 3.5 7v10A3.5 3.5 0 0 0 7 20.5h7.2Z\"/><path class=\"nf f\" style=\"--duo:.2\" d=\"M14.2 20.5v-3.9a2.4 2.4 0 0 1 2.4-2.4h3.9Z\"/><path class=\"nl\" pathLength=\"1\" d=\"M7.6 8.6h8.8\"/><path class=\"nl n2\" pathLength=\"1\" d=\"M7.6 12.2h4.8\"/>",
    sw16: 1.85,
  },
  /* ─────────────────────────────────────────────────────────
   * IMAGE · Tools
   *
   * HOVER pose (spring, reversible, interruptible)
   *          sun rises behind the ridge
   * PRESS one-shot (from the current pose)
   *          frame breathes, sun flares
   *     0ms   .fr plays img-f (360ms)
   *     0ms   .sun plays img-s (400ms)
   * REDUCED MOTION   static glyph
   * ───────────────────────────────────────────────────────── */
  "image": {
    label: "Image",
    category: "Tools",
    hover: "sun rises behind the ridge",
    press: "frame breathes, sun flares",
    pressMs: 400,
    defs: "<clipPath id=\"&-in\"><rect x=\"3.6\" y=\"5.1\" width=\"16.8\" height=\"13.8\" rx=\"2.6\"/></clipPath><mask id=\"&-sky\" maskUnits=\"userSpaceOnUse\" x=\"0\" y=\"0\" width=\"24\" height=\"24\"><rect width=\"24\" height=\"24\" fill=\"#fff\" stroke=\"none\"/><path d=\"M2 18.4 8.4 12a1.3 1.3 0 0 1 1.84 0L14.3 16l2-1.9a1.3 1.3 0 0 1 1.8 0L22 17.8V24H2Z\" fill=\"#000\" stroke=\"#000\" stroke-width=\"3.9\" stroke-linejoin=\"round\"/></mask>",
    body: "<rect class=\"fr\" x=\"2.8\" y=\"4.3\" width=\"18.4\" height=\"15.4\" rx=\"3.4\"/><g clip-path=\"url(#&-in)\"><g mask=\"url(#&-sky)\"><circle class=\"sun s\" cx=\"16.9\" cy=\"11.9\" r=\"1.85\"/></g><path class=\"d\" d=\"M2 18.4 8.4 12a1.3 1.3 0 0 1 1.84 0L14.3 16l2-1.9a1.3 1.3 0 0 1 1.8 0L22 17.8V24H2Z\"/></g><path class=\"rg\" d=\"M3.4 17 8.4 12a1.3 1.3 0 0 1 1.84 0L14.3 16l2-1.9a1.3 1.3 0 0 1 1.8 0l2.6 2.5\"/>",
    sw16: 1.85,
  },
  /* ─────────────────────────────────────────────────────────
   * LINK · Tools
   *
   * HOVER pose (spring, reversible, interruptible)
   *          links pull apart, bar thins
   * PRESS one-shot (from the current pose)
   *          snap together
   *     0ms   .la plays lk-a (340ms)
   *     0ms   .lb plays lk-b (340ms)
   *     0ms   .lbar plays lk-c (340ms)
   * REDUCED MOTION   static glyph
   * ───────────────────────────────────────────────────────── */
  "link": {
    label: "Link",
    category: "Tools",
    hover: "links pull apart, bar thins",
    press: "snap together",
    pressMs: 340,
    defs: "",
    body: "<path class=\"la\" d=\"M11.2 7.6l1.4-1.4a3.7 3.7 0 0 1 5.2 5.2l-1.4 1.4\"/><path class=\"lb\" d=\"M12.8 16.4l-1.4 1.4a3.7 3.7 0 0 1-5.2-5.2l1.4-1.4\"/><path class=\"lbar\" d=\"M9.8 14.2 14.2 9.8\"/>",
    sw16: 1.85,
  },
  /* ─────────────────────────────────────────────────────────
   * DRAW · Tools
   *
   * HOVER pose (spring, reversible, interruptible)
   *          tip slides and draws a stroke
   * PRESS one-shot (from the current pose)
   *          taps the paper
   *     0ms   .pen plays pen-p (320ms)
   * REDUCED MOTION   static glyph
   * ───────────────────────────────────────────────────────── */
  "draw": {
    label: "Draw",
    category: "Tools",
    hover: "tip slides and draws a stroke",
    press: "taps the paper",
    pressMs: 320,
    defs: "",
    body: "<path class=\"ln\" pathLength=\"1\" d=\"M5.6 17.45c1.05.7 2 .7 3 0\"/><g class=\"pen\"><g transform=\"translate(-1.6 .6) rotate(45 12 12)\"><path class=\"f\" style=\"--duo:.16\" d=\"M9.4 14.4V5.8a2.6 2.6 0 0 1 5.2 0v8.6l-1.75 4a.9.9 0 0 1-1.7 0Z\"/><path d=\"M9.4 8.2h5.2\"/></g></g>",
    sw16: 1.85,
  },
  /* ─────────────────────────────────────────────────────────
   * LAYOUT · Tools
   *
   * HOVER pose (spring, reversible, interruptible)
   *          tiles swap sides
   * PRESS one-shot (from the current pose)
   *          tiles settle together
   *     0ms   .lt plays lay-p (320ms)
   *    40ms   .l1 plays lay-p1 (320ms)
   *    80ms   .l2 plays lay-p1 (320ms)
   * REDUCED MOTION   static glyph
   * ───────────────────────────────────────────────────────── */
  "layout": {
    label: "Layout",
    category: "Tools",
    hover: "tiles swap sides",
    press: "tiles settle together",
    pressMs: 400,
    defs: "",
    body: "<rect class=\"lt f\" style=\"--duo:.16\" x=\"3.6\" y=\"3.6\" width=\"7\" height=\"16.8\" rx=\"2.4\"/><rect class=\"l1\" x=\"13.4\" y=\"3.6\" width=\"7\" height=\"7\" rx=\"2.4\"/><rect class=\"l2\" x=\"13.4\" y=\"13.4\" width=\"7\" height=\"7\" rx=\"2.4\"/>",
    sw16: 1.85,
  },
  /* ─────────────────────────────────────────────────────────
   * TIDY · Tools
   *
   * HOVER pose (spring, reversible, interruptible)
   *          loose tiles snap to the guide
   * PRESS one-shot (from the current pose)
   *          guide pulses, tiles click home
   *     0ms   .g plays tdy-g (340ms)
   *     0ms   .t1 plays tdy-t (300ms)
   *    40ms   .t2 plays tdy-t (300ms)
   *    80ms   .t3 plays tdy-t (300ms)
   * REDUCED MOTION   static glyph
   * ───────────────────────────────────────────────────────── */
  "tidy": {
    label: "Tidy",
    category: "Tools",
    hover: "loose tiles snap to the guide",
    press: "guide pulses, tiles click home",
    pressMs: 380,
    defs: "",
    body: "<path class=\"g\" d=\"M4.3 3.8v16.4\"/><rect class=\"t1 f\" x=\"7.2\" y=\"4.4\" width=\"12.6\" height=\"4\" rx=\"2\"/><rect class=\"t2 f\" x=\"7.2\" y=\"10\" width=\"8.6\" height=\"4\" rx=\"2\"/><rect class=\"t3 f\" x=\"7.2\" y=\"15.6\" width=\"11\" height=\"4\" rx=\"2\"/>",
    body16: "<path d=\"M4.3 4v16\"/><path d=\"M8.2 6.4h11.4\" transform=\"translate(1.2 0) rotate(-4 8.2 6.4)\"/><path d=\"M8.2 12h7.4\" transform=\"translate(2.4 0) rotate(5 8.2 12)\"/><path d=\"M8.2 17.6h9.6\" transform=\"translate(.8 0) rotate(-3 8.2 17.6)\"/>",
    sw16: 1.85,
  },
  /* ─────────────────────────────────────────────────────────
   * SEARCH · Tools
   *
   * HOVER pose (spring, reversible, interruptible)
   *          lens sweeps, glint crosses glass
   * PRESS one-shot (from the current pose)
   *          lens focuses
   *     0ms   .lens plays srch-p (340ms)
   * REDUCED MOTION   static glyph
   * ───────────────────────────────────────────────────────── */
  "search": {
    label: "Search",
    category: "Tools",
    hover: "lens sweeps, glint crosses glass",
    press: "lens focuses",
    pressMs: 340,
    defs: "",
    body: "<g class=\"sg\"><circle class=\"lens\" cx=\"10.6\" cy=\"10.6\" r=\"6.3\"/><path class=\"hdl\" d=\"M15.2 15.2 19.8 19.8\"/><path class=\"gl\" d=\"M7.6 9.1a3.4 3.4 0 0 1 1.6-1.6\"/></g>",
    sw16: 1.85,
  },
  /* ─────────────────────────────────────────────────────────
   * ZOOM IN · Tools
   *
   * HOVER pose (spring, reversible, interruptible)
   *          plus turns a quarter
   * PRESS one-shot (from the current pose)
   *          lens swells
   *     0ms   .sg plays zi-p (340ms)
   * REDUCED MOTION   static glyph
   * ───────────────────────────────────────────────────────── */
  "zoom-in": {
    label: "Zoom In",
    category: "Tools",
    hover: "plus turns a quarter",
    press: "lens swells",
    pressMs: 340,
    defs: "",
    body: "<g class=\"sg\"><circle class=\"lens\" cx=\"10.6\" cy=\"10.6\" r=\"6.3\"/><path class=\"hdl\" d=\"M15.2 15.2 19.8 19.8\"/><path class=\"pm\" d=\"M8.2 10.6h4.8M10.6 8.2v4.8\"/></g>",
    sw16: 1.85,
  },
  /* ─────────────────────────────────────────────────────────
   * ZOOM OUT · Tools
   *
   * HOVER pose (spring, reversible, interruptible)
   *          minus narrows, lens recedes
   * PRESS one-shot (from the current pose)
   *          lens shrinks
   *     0ms   .sg plays zo-p (340ms)
   * REDUCED MOTION   static glyph
   * ───────────────────────────────────────────────────────── */
  "zoom-out": {
    label: "Zoom Out",
    category: "Tools",
    hover: "minus narrows, lens recedes",
    press: "lens shrinks",
    pressMs: 340,
    defs: "",
    body: "<g class=\"sg\"><circle class=\"lens\" cx=\"10.6\" cy=\"10.6\" r=\"6.3\"/><path class=\"hdl\" d=\"M15.2 15.2 19.8 19.8\"/><path class=\"pm\" d=\"M8.2 10.6h4.8\"/></g>",
    sw16: 1.85,
  },
  /* ─────────────────────────────────────────────────────────
   * FIT · Tools
   *
   * HOVER pose (spring, reversible, interruptible)
   *          content grows to the frame
   * PRESS one-shot (from the current pose)
   *          corners clamp
   *     0ms   .c1 plays fit-1 (300ms)
   *     0ms   .c2 plays fit-2 (300ms)
   *     0ms   .c3 plays fit-3 (300ms)
   *     0ms   .c4 plays fit-4 (300ms)
   * REDUCED MOTION   static glyph
   * ───────────────────────────────────────────────────────── */
  "fit": {
    label: "Fit",
    category: "Tools",
    hover: "content grows to the frame",
    press: "corners clamp",
    pressMs: 300,
    defs: "",
    body: "<path class=\"c1\" d=\"M3.8 8.6V6.4a2.6 2.6 0 0 1 2.6-2.6h2.2\"/><path class=\"c2\" d=\"M15.4 3.8h2.2a2.6 2.6 0 0 1 2.6 2.6v2.2\"/><path class=\"c3\" d=\"M20.2 15.4v2.2a2.6 2.6 0 0 1-2.6 2.6h-2.2\"/><path class=\"c4\" d=\"M8.6 20.2H6.4a2.6 2.6 0 0 1-2.6-2.6v-2.2\"/><rect class=\"in f\" style=\"--duo:.18\" x=\"9\" y=\"9\" width=\"6\" height=\"6\" rx=\"1.7\"/>",
    sw16: 1.85,
  },
  /* ─────────────────────────────────────────────────────────
   * DUPLICATE · Actions
   *
   * HOVER pose (spring, reversible, interruptible)
   *          copy slides off the original
   * PRESS one-shot (from the current pose)
   *          copy stamps back and out
   *     0ms   .fg plays dup-p (380ms)
   *     0ms   .fm plays dup-p (380ms)
   * REDUCED MOTION   static glyph
   * ───────────────────────────────────────────────────────── */
  "duplicate": {
    label: "Duplicate",
    category: "Actions",
    hover: "copy slides off the original",
    press: "copy stamps back and out",
    pressMs: 380,
    defs: "<mask id=\"&-m\" maskUnits=\"userSpaceOnUse\" x=\"0\" y=\"0\" width=\"24\" height=\"24\"><rect width=\"24\" height=\"24\" fill=\"#fff\" stroke=\"none\"/><rect class=\"fm\" x=\"7\" y=\"7\" width=\"15\" height=\"15\" rx=\"4.4\" fill=\"#000\" stroke=\"none\"/></mask>",
    body: "<rect class=\"bk\" mask=\"url(#&-m)\" x=\"3.5\" y=\"3.5\" width=\"12\" height=\"12\" rx=\"3\"/><g class=\"fg\"><rect class=\"f\" style=\"--duo:.16\" x=\"8.5\" y=\"8.5\" width=\"12\" height=\"12\" rx=\"3\"/><path d=\"M14.5 12.3v4.4M12.3 14.5h4.4\"/></g>",
    sw16: 1.85,
  },
  /* ─────────────────────────────────────────────────────────
   * DELETE · SEND AWAY · Actions
   *
   * HOVER pose (spring, reversible, interruptible)
   *          well turns, dot is drawn in
   * PRESS one-shot (from the current pose)
   *          dot is pulled into the centre and vanishes
   *     0ms   .sp plays sa-sp (460ms)
   *    30ms   .orb plays sa-orb (460ms)
   *    30ms   .rad plays sa-rad (460ms)
   *     0ms   .dot plays sa-dot (460ms)
   * REDUCED MOTION   static glyph
   * ───────────────────────────────────────────────────────── */
  "send-away": {
    label: "Delete · Send away",
    category: "Actions",
    hover: "well turns, dot is drawn in",
    press: "dot is pulled into the centre and vanishes",
    pressMs: 490,
    defs: "",
    body: "<path class=\"sp\" d=\"M12.06 13.05L11.89 13.19L11.69 13.3L11.46 13.36L11.2 13.37L10.94 13.34L10.67 13.25L10.4 13.11L10.15 12.92L9.93 12.68L9.74 12.39L9.59 12.07L9.5 11.7L9.46 11.31L9.48 10.91L9.57 10.5L9.73 10.09L9.96 9.7L10.25 9.34L10.61 9.01L11.03 8.74L11.5 8.53L12.01 8.38L12.55 8.31L13.1 8.33L13.67 8.43L14.23 8.62L14.76 8.9L15.26 9.27L15.72 9.72L16.1 10.24L16.42 10.82L16.64 11.46L16.78 12.14L16.81 12.85L16.73 13.57L16.55 14.29L16.25 14.98L15.85 15.64L15.34 16.24L14.75 16.77L14.06 17.21L13.31 17.55L12.5 17.79L11.65 17.9L10.78 17.89L9.9 17.74L9.05 17.47L8.23 17.06L7.46 16.53L6.77 15.89L6.17 15.14L5.69 14.29L5.32 13.37L5.09 12.4L5.01 11.38L5.08 10.36L5.29 9.33L5.67 8.34L6.18 7.4L6.84 6.53L7.63 5.76L8.54 5.11L9.54 4.58L10.63 4.21L11.77 3.99L12.94 3.95L14.12 4.07L15.29 4.38L16.41 4.85L17.46 5.49\"/><g class=\"orb\"><g class=\"rad\"><circle class=\"dot s\" cx=\"20.17\" cy=\"10.26\" r=\"1.4\"/></g></g>",
    body16: "<path d=\"M10.34 11.07L10.4 10.78L10.51 10.48L10.68 10.19L10.9 9.92L11.17 9.68L11.49 9.48L11.85 9.32L12.25 9.21L12.67 9.17L13.11 9.19L13.56 9.28L14 9.44L14.43 9.67L14.83 9.98L15.19 10.35L15.5 10.79L15.74 11.28L15.92 11.82L16.02 12.39L16.03 12.99L15.95 13.6L15.78 14.2L15.51 14.79L15.16 15.35L14.71 15.86L14.18 16.3L13.58 16.68L12.91 16.97L12.2 17.16L11.44 17.25L10.67 17.22L9.89 17.08L9.13 16.82L8.4 16.45L7.72 15.97L7.1 15.38L6.57 14.69L6.13 13.92L5.81 13.08L5.6 12.19L5.53 11.25L5.59 10.31L5.8 9.36L6.14 8.45L6.63 7.57L7.24 6.77L7.97 6.05L8.82 5.43L9.76 4.93L10.77 4.58L11.85 4.36L12.96 4.31L14.08 4.42L15.19 4.69L16.26 5.12L17.27 5.72\"/><circle class=\"s\" cx=\"20.16\" cy=\"11.14\" r=\"1.6\"/>",
    sw16: 1.9,
  },
  /* ─────────────────────────────────────────────────────────
   * DELETE · TRASH · Actions
   *
   * HOVER pose (spring, reversible, interruptible)
   *          lid lifts on its hinge
   * PRESS one-shot (from the current pose)
   *          lid closes with a small settle
   *     0ms   .lid plays tr-p (380ms)
   * REDUCED MOTION   static glyph
   * ───────────────────────────────────────────────────────── */
  "trash": {
    label: "Delete · Trash",
    category: "Actions",
    hover: "lid lifts on its hinge",
    press: "lid closes with a small settle",
    pressMs: 380,
    defs: "",
    body: "<g class=\"lid\"><path d=\"M4.4 7h15.2\"/><path d=\"M9.4 7V5.6a1.4 1.4 0 0 1 1.4-1.4h2.4a1.4 1.4 0 0 1 1.4 1.4V7\"/></g><path class=\"f\" style=\"--duo:.12\" d=\"M6.2 7h11.6l-.86 11.1a2.3 2.3 0 0 1-2.3 2.1H9.36a2.3 2.3 0 0 1-2.3-2.1Z\"/><path d=\"M10.2 10.6v5.8M13.8 10.6v5.8\"/>",
    sw16: 1.85,
  },
  /* ─────────────────────────────────────────────────────────
   * GROUP · STACK · Actions
   *
   * HOVER pose (spring, reversible, interruptible)
   *          cards rise and fan above the flap
   * PRESS one-shot (from the current pose)
   *          cards drop into the folder
   *     0ms   .c1 plays grp-p (440ms)
   *    50ms   .c2 plays grp-p2 (440ms)
   *     0ms   .ff plays grp-f (440ms)
   * REDUCED MOTION   static glyph
   * ───────────────────────────────────────────────────────── */
  "group": {
    label: "Group · Stack",
    category: "Actions",
    hover: "cards rise and fan above the flap",
    press: "cards drop into the folder",
    pressMs: 490,
    defs: "<mask id=\"&-m\" maskUnits=\"userSpaceOnUse\" x=\"0\" y=\"0\" width=\"24\" height=\"24\"><rect width=\"24\" height=\"24\" fill=\"#fff\" stroke=\"none\"/><path d=\"M1 11.2h22V24H1Z\" fill=\"#000\" stroke=\"none\"/></mask><mask id=\"&-b\" maskUnits=\"userSpaceOnUse\" x=\"0\" y=\"0\" width=\"24\" height=\"24\"><rect width=\"24\" height=\"24\" fill=\"#fff\" stroke=\"none\"/><g fill=\"#000\" stroke=\"#000\" stroke-width=\"3.3\"><rect class=\"c1\" x=\"5.6\" y=\"6.4\" width=\"8.2\" height=\"10\" rx=\"1.7\"/><rect class=\"c2\" x=\"10.2\" y=\"7.4\" width=\"8.2\" height=\"10\" rx=\"1.7\"/></g></mask><mask id=\"&-c\" maskUnits=\"userSpaceOnUse\" x=\"0\" y=\"0\" width=\"24\" height=\"24\"><rect width=\"24\" height=\"24\" fill=\"#fff\" stroke=\"none\"/><rect class=\"c2\" x=\"10.2\" y=\"7.4\" width=\"8.2\" height=\"10\" rx=\"1.7\" fill=\"#000\" stroke=\"#000\" stroke-width=\"3.3\"/></mask>",
    body: "<path mask=\"url(#&-b)\" d=\"M3.5 12.4V6.3a1.9 1.9 0 0 1 1.9-1.9h3.1a1.6 1.6 0 0 1 1.2.53l1.2 1.37h7.7a1.9 1.9 0 0 1 1.9 1.9v4.2\"/><g mask=\"url(#&-m)\"><g mask=\"url(#&-c)\"><rect class=\"c1\" x=\"5.6\" y=\"6.4\" width=\"8.2\" height=\"10\" rx=\"1.7\"/></g><rect class=\"c2 f\" style=\"--duo:.14\" x=\"10.2\" y=\"7.4\" width=\"8.2\" height=\"10\" rx=\"1.7\"/></g><path class=\"ff f\" style=\"--duo:.16\" d=\"M3.5 12.2h17v5.4a2.5 2.5 0 0 1-2.5 2.5H6a2.5 2.5 0 0 1-2.5-2.5Z\"/>",
    body16: "<path d=\"M3.5 12.2V6.3a1.9 1.9 0 0 1 1.9-1.9h3.1a1.6 1.6 0 0 1 1.2.53l1.2 1.37H12\"/><path d=\"M8.2 11V8.6a1.8 1.8 0 0 1 1.8-1.8h6.6a1.8 1.8 0 0 1 1.8 1.8V11\" transform=\"rotate(4 13 11)\"/><path class=\"f\" style=\"--duo:.16\" d=\"M3.5 12.4h17v5.2a2.5 2.5 0 0 1-2.5 2.5H6a2.5 2.5 0 0 1-2.5-2.5Z\"/>",
    sw16: 1.9,
  },
  /* ─────────────────────────────────────────────────────────
   * UNGROUP · Actions
   *
   * HOVER pose (spring, reversible, interruptible)
   *          cards spread wider
   * PRESS one-shot (from the current pose)
   *          cards pop out and separate
   *     0ms   .u1 plays ug-1 (400ms)
   *    50ms   .u2 plays ug-2 (400ms)
   * REDUCED MOTION   static glyph
   * ───────────────────────────────────────────────────────── */
  "ungroup": {
    label: "Ungroup",
    category: "Actions",
    hover: "cards spread wider",
    press: "cards pop out and separate",
    pressMs: 450,
    defs: "",
    body: "<rect class=\"u1 f\" style=\"--duo:.1\" x=\"3.2\" y=\"3.4\" width=\"8\" height=\"9.4\" rx=\"1.6\"/><rect class=\"u2 f\" style=\"--duo:.1\" x=\"12.8\" y=\"3.4\" width=\"8\" height=\"9.4\" rx=\"1.6\"/><path class=\"ff\" d=\"M3.5 15.2v2.4a2.5 2.5 0 0 0 2.5 2.5h12a2.5 2.5 0 0 0 2.5-2.5v-2.4\"/>",
    sw16: 1.85,
  },
  /* ─────────────────────────────────────────────────────────
   * PIN · Actions
   *
   * HOVER pose (spring, reversible, interruptible)
   *          pin lifts, its contact shadow fades
   * PRESS one-shot (from the current pose)
   *          pushes in
   *     0ms   .pn plays pin-p (340ms)
   *     0ms   .sh plays pin-s (340ms)
   * REDUCED MOTION   static glyph
   * ───────────────────────────────────────────────────────── */
  "pin": {
    label: "Pin",
    category: "Actions",
    hover: "pin lifts, its contact shadow fades",
    press: "pushes in",
    pressMs: 340,
    defs: "",
    body: "<g class=\"pn\"><path class=\"f\" style=\"--duo:.16\" d=\"M8.8 3.8h6.4M9.9 3.8v4.9L7.2 12a.7.7 0 0 0 .54 1.14h8.52a.7.7 0 0 0 .54-1.14L14.1 8.7V3.8\"/><path d=\"M12 13.2v6.4\"/></g><path class=\"sh\" d=\"M10.6 20.8h2.8\"/>",
    sw16: 1.85,
  },
  /* ─────────────────────────────────────────────────────────
   * BOARD · Actions
   *
   * HOVER pose (spring, reversible, interruptible)
   *          ribbon lengthens
   * PRESS one-shot (from the current pose)
   *          drops into place
   *     0ms   .bm plays bd-p (380ms)
   * REDUCED MOTION   static glyph
   * ───────────────────────────────────────────────────────── */
  "board": {
    label: "Board",
    category: "Actions",
    hover: "ribbon lengthens",
    press: "drops into place",
    pressMs: 380,
    defs: "",
    body: "<path class=\"bm f\" style=\"--duo:.16\" d=\"M6.8 19.8V5.9a2.1 2.1 0 0 1 2.1-2.1h6.2a2.1 2.1 0 0 1 2.1 2.1v13.9l-4.3-3a1.6 1.6 0 0 0-1.8 0Z\"/>",
    sw16: 1.85,
  },
  /* ─────────────────────────────────────────────────────────
   * SHARE · EXPORT · Actions
   *
   * HOVER pose (spring, reversible, interruptible)
   *          arrow lifts out of the tray
   * PRESS one-shot (from the current pose)
   *          arrow leaves, a new one rises
   *     0ms   .ar plays sh-p (420ms)
   * REDUCED MOTION   static glyph
   * ───────────────────────────────────────────────────────── */
  "share": {
    label: "Share · Export",
    category: "Actions",
    hover: "arrow lifts out of the tray",
    press: "arrow leaves, a new one rises",
    pressMs: 420,
    defs: "",
    body: "<path class=\"tray\" d=\"M8.4 9.6H7.4A2.4 2.4 0 0 0 5 12v5.6a2.4 2.4 0 0 0 2.4 2.4h9.2a2.4 2.4 0 0 0 2.4-2.4V12a2.4 2.4 0 0 0-2.4-2.4h-1\"/><g class=\"ar\"><path d=\"M12 14.2V3.9M8.9 7 12 3.9 15.1 7\"/></g>",
    sw16: 1.85,
  },
  /* ─────────────────────────────────────────────────────────
   * UNDO · Actions
   *
   * HOVER pose (spring, reversible, interruptible)
   *          head reaches back
   * PRESS one-shot (from the current pose)
   *          arrow arcs back and returns
   *     0ms   .ug plays un-p (420ms)
   * REDUCED MOTION   static glyph
   * ───────────────────────────────────────────────────────── */
  "undo": {
    label: "Undo",
    category: "Actions",
    hover: "head reaches back",
    press: "arrow arcs back and returns",
    pressMs: 420,
    defs: "",
    body: "<g class=\"ug\"><path class=\"uh\" d=\"M9 5.3 5.3 9 9 12.7\"/><path class=\"us\" d=\"M5.3 9h9.3a4.6 4.6 0 0 1 0 9.2h-4\"/></g>",
    sw16: 1.85,
  },
  /* ─────────────────────────────────────────────────────────
   * REDO · Actions
   *
   * HOVER pose (spring, reversible, interruptible)
   *          head reaches forward
   * PRESS one-shot (from the current pose)
   *          arrow arcs forward and returns
   *     0ms   .ug plays rd-p (420ms)
   * REDUCED MOTION   static glyph
   * ───────────────────────────────────────────────────────── */
  "redo": {
    label: "Redo",
    category: "Actions",
    hover: "head reaches forward",
    press: "arrow arcs forward and returns",
    pressMs: 420,
    defs: "",
    body: "<g transform=\"matrix(-1 0 0 1 24 0)\"><g class=\"ug\"><path class=\"uh\" d=\"M9 5.3 5.3 9 9 12.7\"/><path class=\"us\" d=\"M5.3 9h9.3a4.6 4.6 0 0 1 0 9.2h-4\"/></g></g>",
    sw16: 1.85,
  },
  /* ─────────────────────────────────────────────────────────
   * MORE · Actions
   *
   * HOVER pose (spring, reversible, interruptible)
   *          dots swell in sequence
   * PRESS one-shot (from the current pose)
   *          dots gather and part
   *     0ms   .m1 plays mo-1 (340ms)
   *    80ms   .m3 plays mo-3 (340ms)
   * REDUCED MOTION   static glyph
   * ───────────────────────────────────────────────────────── */
  "more": {
    label: "More",
    category: "Actions",
    hover: "dots swell in sequence",
    press: "dots gather and part",
    pressMs: 420,
    defs: "",
    body: "<circle class=\"m1 s\" cx=\"5.6\" cy=\"12\" r=\"1.55\"/><circle class=\"m2 s\" cx=\"12\" cy=\"12\" r=\"1.55\"/><circle class=\"m3 s\" cx=\"18.4\" cy=\"12\" r=\"1.55\"/>",
    sw16: 1.85,
  },
  /* ─────────────────────────────────────────────────────────
   * CLOSE · Actions
   *
   * HOVER pose (spring, reversible, interruptible)
   *          turns a quarter and softens
   * PRESS one-shot (from the current pose)
   *          pinches closed
   *     0ms   .x plays cl-p (300ms)
   * REDUCED MOTION   static glyph
   * ───────────────────────────────────────────────────────── */
  "close": {
    label: "Close",
    category: "Actions",
    hover: "turns a quarter and softens",
    press: "pinches closed",
    pressMs: 300,
    defs: "",
    body: "<path class=\"x\" d=\"M7.2 7.2l9.6 9.6M16.8 7.2l-9.6 9.6\"/>",
    sw16: 1.85,
  },
  /* ─────────────────────────────────────────────────────────
   * CHECK · Actions
   *
   * HOVER pose (spring, reversible, interruptible)
   *          tick lifts
   * PRESS one-shot (from the current pose)
   *          tick redraws
   *     0ms   .tk plays ck-p (300ms)
   * REDUCED MOTION   static glyph
   * ───────────────────────────────────────────────────────── */
  "check": {
    label: "Check",
    category: "Actions",
    hover: "tick lifts",
    press: "tick redraws",
    pressMs: 300,
    defs: "",
    body: "<path class=\"tk\" pathLength=\"1\" d=\"M5.4 12.6l4.1 4.1 9.1-9.4\"/>",
    sw16: 1.85,
  },
  /* ─────────────────────────────────────────────────────────
   * SYNCED · Status
   *
   * HOVER pose (spring, reversible, interruptible)
   *          satellite advances along its orbit
   * PRESS one-shot (from the current pose)
   *          orbit completes a full turn
   *     0ms   .or plays syn-p (460ms)
   * REDUCED MOTION   static glyph
   * ───────────────────────────────────────────────────────── */
  "synced": {
    label: "Synced",
    category: "Status",
    hover: "satellite advances along its orbit",
    press: "orbit completes a full turn",
    pressMs: 460,
    defs: "",
    body: "<circle class=\"core s\" cx=\"12\" cy=\"12\" r=\"2.1\"/><g class=\"or\"><circle class=\"ring\" cx=\"12\" cy=\"12\" r=\"7.6\" pathLength=\"100\" transform=\"rotate(-18 12 12)\"/><circle class=\"sat s\" cx=\"17.37\" cy=\"6.63\" r=\"1.75\"/></g>",
    sw16: 1.85,
  },
  /* ─────────────────────────────────────────────────────────
   * OFFLINE · Status
   *
   * HOVER pose (spring, reversible, interruptible)
   *          satellite drifts further out
   * PRESS one-shot (from the current pose)
   *          tries to return, drifts away
   *     0ms   .sat plays off-p (460ms)
   * REDUCED MOTION   static glyph
   * ───────────────────────────────────────────────────────── */
  "offline": {
    label: "Offline",
    category: "Status",
    hover: "satellite drifts further out",
    press: "tries to return, drifts away",
    pressMs: 460,
    defs: "",
    body: "<circle class=\"core s\" cx=\"12\" cy=\"12\" r=\"2.1\" style=\"opacity:.55\"/><circle class=\"ring\" cx=\"12\" cy=\"12\" r=\"7.6\" pathLength=\"100\" transform=\"rotate(-3 12 12)\"/><circle class=\"sat s\" cx=\"19\" cy=\"5\" r=\"1.6\"/>",
    sw16: 1.85,
  },
  /* ─────────────────────────────────────────────────────────
   * SYNC ERROR · Status
   *
   * HOVER pose (spring, reversible, interruptible)
   *          mark nudges
   * PRESS one-shot (from the current pose)
   *          orbit shivers once
   *     0ms   .or plays err-p (420ms)
   * REDUCED MOTION   static glyph
   * ───────────────────────────────────────────────────────── */
  "sync-error": {
    label: "Sync Error",
    category: "Status",
    hover: "mark nudges",
    press: "orbit shivers once",
    pressMs: 420,
    defs: "",
    body: "<g class=\"or\"><circle class=\"ring\" cx=\"12\" cy=\"12\" r=\"7.6\" pathLength=\"100\" transform=\"rotate(-18 12 12)\"/></g><path class=\"ex\" d=\"M12 8.6v4.2\"/><circle class=\"exd s\" cx=\"12\" cy=\"15.7\" r=\"1.05\"/>",
    sw16: 1.85,
  },
  /* ─────────────────────────────────────────────────────────
   * CAPTURE · Status
   *
   * HOVER pose (spring, reversible, interruptible)
   *          viewfinder focuses in
   * PRESS one-shot (from the current pose)
   *          shutter blinks
   *     0ms   .ap plays cap-p (340ms)
   * REDUCED MOTION   static glyph
   * ───────────────────────────────────────────────────────── */
  "capture": {
    label: "Capture",
    category: "Status",
    hover: "viewfinder focuses in",
    press: "shutter blinks",
    pressMs: 340,
    defs: "",
    body: "<path class=\"c1\" d=\"M3.8 8.4V7A3.2 3.2 0 0 1 7 3.8h1.4\"/><path class=\"c2\" d=\"M15.6 3.8H17A3.2 3.2 0 0 1 20.2 7v1.4\"/><path class=\"c3\" d=\"M20.2 15.6V17a3.2 3.2 0 0 1-3.2 3.2h-1.4\"/><path class=\"c4\" d=\"M8.4 20.2H7A3.2 3.2 0 0 1 3.8 17v-1.4\"/><circle class=\"ap f\" style=\"--duo:.16\" cx=\"12\" cy=\"12\" r=\"3.6\"/>",
    sw16: 1.85,
  },
  /* ─────────────────────────────────────────────────────────
   * PASTE · Status
   *
   * HOVER pose (spring, reversible, interruptible)
   *          clip lifts
   * PRESS one-shot (from the current pose)
   *          contents land on the board
   *     0ms   .pl plays ps-p (340ms)
   *    60ms   .p2 plays (inherits) (340ms)
   * REDUCED MOTION   static glyph
   * ───────────────────────────────────────────────────────── */
  "paste": {
    label: "Paste",
    category: "Status",
    hover: "clip lifts",
    press: "contents land on the board",
    pressMs: 400,
    defs: "",
    body: "<path class=\"f\" style=\"--duo:.1\" d=\"M8.6 5.2H7.4A2.4 2.4 0 0 0 5 7.6v10.6a2.4 2.4 0 0 0 2.4 2.4h9.2a2.4 2.4 0 0 0 2.4-2.4V7.6a2.4 2.4 0 0 0-2.4-2.4h-1.2\"/><rect class=\"clip\" x=\"8.6\" y=\"3.4\" width=\"6.8\" height=\"3.6\" rx=\"1.3\"/><path class=\"pl\" pathLength=\"1\" d=\"M8.6 11.8h6.8\"/><path class=\"pl p2\" pathLength=\"1\" d=\"M8.6 15.4h4.2\"/>",
    sw16: 1.85,
  },
  /* ─────────────────────────────────────────────────────────
   * KEEPER · Status
   *
   * HOVER pose (spring, reversible, interruptible)
   *          blinks
   * PRESS one-shot (from the current pose)
   *          ring tips, eyes look up
   *     0ms   .rg plays kp-r (440ms)
   *     0ms   .eyes plays kp-e (440ms)
   * REDUCED MOTION   static glyph
   * ───────────────────────────────────────────────────────── */
  "keeper": {
    label: "Keeper",
    category: "Status",
    hover: "blinks",
    press: "ring tips, eyes look up",
    pressMs: 440,
    defs: "<mask id=\"&-k\" maskUnits=\"userSpaceOnUse\" x=\"0\" y=\"0\" width=\"24\" height=\"24\"><rect width=\"24\" height=\"24\" fill=\"#fff\" stroke=\"none\"/><g class=\"eyes\"><rect x=\"8.9\" y=\"7.5\" width=\"2.4\" height=\"4.2\" rx=\"1.2\" fill=\"#000\" stroke=\"none\"/><rect x=\"12.7\" y=\"7.5\" width=\"2.4\" height=\"4.2\" rx=\"1.2\" fill=\"#000\" stroke=\"none\"/></g><g class=\"rg\"><path d=\"M2.2 12.8a9.8 2.5 0 0 0 19.6 0\" fill=\"none\" stroke=\"#000\" stroke-width=\"4\" transform=\"rotate(-12 12 12.8)\"/></g></mask><mask id=\"&-kb\" maskUnits=\"userSpaceOnUse\" x=\"0\" y=\"0\" width=\"24\" height=\"24\"><rect width=\"24\" height=\"24\" fill=\"#fff\" stroke=\"none\"/><circle cx=\"12\" cy=\"11.4\" r=\"8\" fill=\"#000\" stroke=\"none\"/></mask>",
    body: "<g mask=\"url(#&-kb)\"><g class=\"rg\"><path d=\"M2.2 12.8a9.8 2.5 0 0 1 19.6 0\" transform=\"rotate(-12 12 12.8)\" style=\"stroke-width:calc(var(--sw) * .88)\"/></g></g><circle class=\"s\" mask=\"url(#&-k)\" cx=\"12\" cy=\"11.4\" r=\"6.8\"/><g class=\"rg\"><path d=\"M2.2 12.8a9.8 2.5 0 0 0 19.6 0\" transform=\"rotate(-12 12 12.8)\" style=\"stroke-width:calc(var(--sw) * .88)\"/></g>",
    body16: "<defs><mask id=\"&-k\" maskUnits=\"userSpaceOnUse\" x=\"0\" y=\"0\" width=\"24\" height=\"24\"><rect width=\"24\" height=\"24\" fill=\"#fff\" stroke=\"none\"/><rect x=\"8.7\" y=\"7.2\" width=\"2.7\" height=\"4.5\" rx=\"1.35\" fill=\"#000\" stroke=\"none\"/><rect x=\"12.6\" y=\"7.2\" width=\"2.7\" height=\"4.5\" rx=\"1.35\" fill=\"#000\" stroke=\"none\"/><path d=\"M2.4 13a9.6 2.4 0 0 0 19.2 0\" fill=\"none\" stroke=\"#000\" stroke-width=\"4.4\" transform=\"rotate(-12 12 13)\"/></mask></defs><circle class=\"s\" mask=\"url(#&-k)\" cx=\"12\" cy=\"11.2\" r=\"7\"/><path d=\"M2.4 13a9.6 2.4 0 0 0 19.2 0\" transform=\"rotate(-12 12 13)\"/>",
    sw16: 1.9,
  },
  /* ─────────────────────────────────────────────────────────
   * NEW · Actions
   *
   * HOVER pose (spring, reversible, interruptible)
   *          the plus turns a quarter
   * PRESS one-shot (from the current pose)
   *          the tile presses in
   *     0ms   .pt plays pl-p (300ms)
   * REDUCED MOTION   static glyph
   * ───────────────────────────────────────────────────────── */
  "plus": {
    label: "New",
    category: "Actions",
    hover: "the plus turns a quarter",
    press: "the tile presses in",
    pressMs: 300,
    defs: "",
    body: "<rect class=\"pt f\" style=\"--duo:.12\" x=\"4.5\" y=\"4.5\" width=\"15\" height=\"15\" rx=\"3.5\"/><path class=\"pa\" d=\"M8.8 12h6.4\"/><path class=\"pa\" d=\"M12 8.8v6.4\"/>",
    sw16: 1.85,
  },
  /* ─────────────────────────────────────────────────────────
   * REGION · Tools
   *
   * HOVER pose (spring, reversible, interruptible)
   *          the name writes across the head
   * PRESS one-shot (from the current pose)
   *          the frame settles
   *     0ms   .rb plays rg-p (340ms)
   * REDUCED MOTION   static glyph
   * ───────────────────────────────────────────────────────── */
  "region": {
    label: "Region",
    category: "Tools",
    hover: "the name writes across the head",
    press: "the frame settles",
    pressMs: 340,
    defs: "",
    body: "<rect class=\"rb f\" style=\"--duo:.08\" x=\"3.5\" y=\"5\" width=\"17\" height=\"14\" rx=\"3.5\"/><path d=\"M3.5 9.6h17\"/><path class=\"rn\" d=\"M6.8 7.3h3.6\"/>",
    sw16: 1.85,
  },
  /* ─────────────────────────────────────────────────────────
   * TASK · Tools
   *
   * HOVER pose (spring, reversible, interruptible)
   *          the tick lifts
   * PRESS one-shot (from the current pose)
   *          the tick redraws
   *     0ms   .tk plays tk-p (300ms)
   * REDUCED MOTION   static glyph
   * ───────────────────────────────────────────────────────── */
  "task": {
    label: "Task",
    category: "Tools",
    hover: "the tick lifts",
    press: "the tick redraws",
    pressMs: 300,
    defs: "",
    body: "<rect class=\"tb f\" style=\"--duo:.12\" x=\"5\" y=\"5\" width=\"14\" height=\"14\" rx=\"3.5\"/><path class=\"tk\" pathLength=\"1\" d=\"M8.7 12.2l2.3 2.3 4.4-4.9\"/>",
    sw16: 1.85,
  },
  /* ─────────────────────────────────────────────────────────
   * TAG · Tools
   *
   * HOVER pose (spring, reversible, interruptible)
   *          the tag swings on its eyelet
   * PRESS one-shot (from the current pose)
   *          the tag stamps
   *     0ms   .tg plays tg-p (340ms)
   * REDUCED MOTION   static glyph
   * ───────────────────────────────────────────────────────── */
  "tag": {
    label: "Tag",
    category: "Tools",
    hover: "the tag swings on its eyelet",
    press: "the tag stamps",
    pressMs: 340,
    defs: "",
    body: "<g class=\"tg\"><path class=\"f\" style=\"--duo:.12\" d=\"M10.2 5h7.6a2.2 2.2 0 0 1 2.2 2.2v9.6a2.2 2.2 0 0 1-2.2 2.2h-7.6a2.2 2.2 0 0 1-1.7-.8L4.6 13.4a2.2 2.2 0 0 1 0-2.8l3.9-4.8a2.2 2.2 0 0 1 1.7-.8Z\"/><circle class=\"s\" cx=\"9.4\" cy=\"12\" r=\"1.3\"/></g>",
    sw16: 1.85,
  },
  /* ─────────────────────────────────────────────────────────
   * CALENDAR · Tools
   *
   * HOVER pose (spring, reversible, interruptible)
   *          the rings lift
   * PRESS one-shot (from the current pose)
   *          the page turns in
   *     0ms   .cb plays cl-p (340ms)
   * REDUCED MOTION   static glyph
   * ───────────────────────────────────────────────────────── */
  "calendar": {
    label: "Calendar",
    category: "Tools",
    hover: "the rings lift",
    press: "the page turns in",
    pressMs: 340,
    defs: "",
    body: "<rect class=\"cb f\" style=\"--duo:.08\" x=\"3.5\" y=\"5.2\" width=\"17\" height=\"15\" rx=\"3.2\"/><path d=\"M3.5 10h17\"/><path class=\"cr\" d=\"M8.2 3.4v3.4M15.8 3.4v3.4\"/>",
    sw16: 1.85,
  },
  /* ─────────────────────────────────────────────────────────
   * DOCUMENT · Tools
   *
   * HOVER pose (spring, reversible, interruptible)
   *          the second line writes on
   * PRESS one-shot (from the current pose)
   *          the lines redraw
   *     0ms   .dl plays dc-p (360ms)
   *    60ms   .d2 plays (inherits) (360ms)
   * REDUCED MOTION   static glyph
   * ───────────────────────────────────────────────────────── */
  "document": {
    label: "Document",
    category: "Tools",
    hover: "the second line writes on",
    press: "the lines redraw",
    pressMs: 420,
    defs: "",
    body: "<path class=\"f\" style=\"--duo:.1\" d=\"M7.2 3.5h6.4l5 5v10a2 2 0 0 1-2 2H7.2a2 2 0 0 1-2-2v-13a2 2 0 0 1 2-2Z\"/><path class=\"dl\" pathLength=\"1\" d=\"M8.6 12.4h6.8\"/><path class=\"dl d2\" pathLength=\"1\" d=\"M8.6 15.8h4\"/>",
    sw16: 1.85,
  },
  /* ─────────────────────────────────────────────────────────
   * TIME · Status
   *
   * HOVER pose (spring, reversible, interruptible)
   *          the minute hand sweeps on
   * PRESS one-shot (from the current pose)
   *          the face ticks
   *     0ms   .hd plays ck2-p (340ms)
   * REDUCED MOTION   static glyph
   * ───────────────────────────────────────────────────────── */
  "clock": {
    label: "Time",
    category: "Status",
    hover: "the minute hand sweeps on",
    press: "the face ticks",
    pressMs: 340,
    defs: "",
    body: "<path class=\"f\" style=\"--duo:.08\" d=\"M12 3.5a8.5 8.5 0 1 1 0 17 8.5 8.5 0 1 1 0-17Z\"/><path class=\"hd\" d=\"M12 7.4V12l3.2 2\"/>",
    sw16: 1.85,
  },
} satisfies Record<string, IconRecord>;

export type IconName = keyof typeof ICON_CATALOG;
export const ICON_NAMES = Object.keys(ICON_CATALOG) as IconName[];
