// Generated by scripts/build-icons.mjs from icons/src/icons.mjs. Do not edit.
import { createIcon } from './Icon';

/** Select. Hover: The pointer draws back, clicks its tip down, and a ring opens where it lands.. Press: plays the same act. */
export const SelectIcon = createIcon("select", "SelectIcon");
/** Text. Hover: glyph steps aside, caret appears and blinks. Press: glyph stamps down. */
export const TextIcon = createIcon("text", "TextIcon");
/** Note. Hover: corner curls up. Press: lines write themselves in. */
export const NoteIcon = createIcon("note", "NoteIcon");
/** Image. Hover: sun rises behind the ridge. Press: frame breathes, sun flares. */
export const ImageIcon = createIcon("image", "ImageIcon");
/** Link. Hover: links pull apart, bar thins. Press: snap together. */
export const LinkIcon = createIcon("link", "LinkIcon");
/** Draw. Hover: tip slides and draws a stroke. Press: taps the paper. */
export const DrawIcon = createIcon("draw", "DrawIcon");
/** Pen. Hover: the nib glides and lays a wave of ink. Press: the nib presses: the line swells and a drop of ink blooms. */
export const PenIcon = createIcon("pen", "PenIcon");
/** Marker. Hover: it sweeps right and lays a see-through band. Press: it lifts back, then sweeps a fresh band. */
export const MarkerIcon = createIcon("marker", "MarkerIcon");
/** Line. Hover: plucked like a string: it bows, swings back and settles straight. Press: it pulls back into its start and is drawn out again. */
export const LineIcon = createIcon("line", "LineIcon");
/** Arrow. Hover: it bends into a connector and the head swings round to follow. Press: it draws back and shoots, the shaft stretching behind the head. */
export const ArrowIcon = createIcon("arrow", "ArrowIcon");
/** Rectangle. Hover: a rough hand-drawn box snaps into a clean one. Press: the box is dragged out again from its corner. */
export const RectangleIcon = createIcon("rectangle", "RectangleIcon");
/** Ellipse. Hover: it is pulled toward a circle, narrowing as it grows. Press: a pen point traces it again, all the way round. */
export const EllipseIcon = createIcon("ellipse", "EllipseIcon");
/** Eraser. Hover: it leans onto a scribble, ready. Press: it rubs back and forth, the scribble goes and crumbs fall. */
export const EraserIcon = createIcon("eraser", "EraserIcon");
/** Layout. Hover: tiles swap sides. Press: tiles settle together. */
export const LayoutIcon = createIcon("layout", "LayoutIcon");
/** Tidy. Hover: loose tiles snap to the guide. Press: guide pulses, tiles click home. */
export const TidyIcon = createIcon("tidy", "TidyIcon");
/** Search. Hover: lens sweeps, glint crosses glass. Press: lens focuses. */
export const SearchIcon = createIcon("search", "SearchIcon");
/** Zoom In. Hover: the plus is magnified: it grows more than the lens. Press: the lens swells one step in. */
export const ZoomInIcon = createIcon("zoom-in", "ZoomInIcon");
/** Zoom Out. Hover: minus narrows, lens recedes. Press: lens shrinks. */
export const ZoomOutIcon = createIcon("zoom-out", "ZoomOutIcon");
/** Fit. Hover: content grows to the frame. Press: corners clamp. */
export const FitIcon = createIcon("fit", "FitIcon");
/** Duplicate. Hover: copy slides off the original. Press: copy stamps back and out. */
export const DuplicateIcon = createIcon("duplicate", "DuplicateIcon");
/** Delete · Send away. Hover: well turns, dot is drawn in. Press: dot is pulled into the centre and vanishes. */
export const SendAwayIcon = createIcon("send-away", "SendAwayIcon");
/** Delete · Trash. Hover: lid lifts on its hinge. Press: lid closes with a small settle. */
export const TrashIcon = createIcon("trash", "TrashIcon");
/** Group · Stack. Hover: cards rise and fan above the flap. Press: cards drop into the folder. */
export const GroupIcon = createIcon("group", "GroupIcon");
/** Ungroup. Hover: cards spread wider. Press: cards pop out and separate. */
export const UngroupIcon = createIcon("ungroup", "UngroupIcon");
/** Pin. Hover: pin lifts, its contact shadow fades. Press: pushes in. */
export const PinIcon = createIcon("pin", "PinIcon");
/** Board. Hover: ribbon lengthens. Press: drops into place. */
export const BoardIcon = createIcon("board", "BoardIcon");
/** Share · Export. Hover: arrow lifts out of the tray. Press: arrow leaves, a new one rises. */
export const ShareIcon = createIcon("share", "ShareIcon");
/** Undo. Hover: head reaches back. Press: arrow arcs back and returns. */
export const UndoIcon = createIcon("undo", "UndoIcon");
/** Redo. Hover: head reaches forward. Press: arrow arcs forward and returns. */
export const RedoIcon = createIcon("redo", "RedoIcon");
/** More. Hover: a wave runs through the dots, left to right: it goes on. Press: dots gather and part. */
export const MoreIcon = createIcon("more", "MoreIcon");
/** Close. Hover: its arms draw in toward the crossing, ready. Press: it folds into its centre and springs back out. */
export const CloseIcon = createIcon("close", "CloseIcon");
/** Check. Hover: it nods yes about its vertex. Press: the tick is drawn again and lands with weight. */
export const CheckIcon = createIcon("check", "CheckIcon");
/** Synced. Hover: satellite advances along its orbit. Press: orbit completes a full turn. */
export const SyncedIcon = createIcon("synced", "SyncedIcon");
/** Offline. Hover: satellite drifts further out. Press: tries to return, drifts away. */
export const OfflineIcon = createIcon("offline", "OfflineIcon");
/** Sync Error. Hover: the orbit tries to turn, catches and snaps back; the mark jumps. Press: orbit shivers once. */
export const SyncErrorIcon = createIcon("sync-error", "SyncErrorIcon");
/** Capture. Hover: viewfinder focuses in. Press: shutter blinks. */
export const CaptureIcon = createIcon("capture", "CaptureIcon");
/** Paste. Hover: clip lifts. Press: contents land on the board. */
export const PasteIcon = createIcon("paste", "PasteIcon");
/** Keeper. Hover: blinks. Press: ring tips, eyes look up. */
export const KeeperIcon = createIcon("keeper", "KeeperIcon");
/** New. Hover: the plus grows out from the centre of the tile. Press: the tile presses in and the plus pops out, made. */
export const PlusIcon = createIcon("plus", "PlusIcon");
/** Region. Hover: the name writes across the head. Press: the frame settles. */
export const RegionIcon = createIcon("region", "RegionIcon");
/** Task. Hover: the tick nods yes inside its box. Press: the box presses in and comes back up ticked. */
export const TaskIcon = createIcon("task", "TaskIcon");
/** Tag. Hover: the tag swings on its eyelet. Press: the tag stamps. */
export const TagIcon = createIcon("tag", "TagIcon");
/** Calendar. Hover: the rings lift. Press: the page turns in. */
export const CalendarIcon = createIcon("calendar", "CalendarIcon");
/** Document. Hover: the second line writes on. Press: the lines redraw. */
export const DocumentIcon = createIcon("document", "DocumentIcon");
/** Time. Hover: an hour passes: the minute hand sweeps round as the hour hand moves one on. Press: the minute hand ticks forward a minute. */
export const ClockIcon = createIcon("clock", "ClockIcon");
/** Me. Hover: the trend redraws to its last point. Press: the last point pulses. */
export const MeIcon = createIcon("me", "MeIcon");
/** Seed sample. Hover: the sprout grows. Press: the seed settles. */
export const SeedIcon = createIcon("seed", "SeedIcon");
