import { expect, test } from '@playwright/test';
import { COLORWAYS, open } from './helpers';
for (const colorway of COLORWAYS) test(`a scrub is one source transaction with retained UTF16 selection in ${colorway}`, async ({ page }) => {
  await open(page, '/components/cue#source-history', colorway);
  const host = page.getByTestId('cue-document-proof');
  const editor = host.getByRole('textbox', { name: 'Document source' });
  const original = await editor.inputValue();
  const label = host.getByText('Sleep duration', { exact: true });
  const rect = await label.boundingBox(); expect(rect).not.toBeNull();
  await page.mouse.move(rect!.x + rect!.width / 2, rect!.y + rect!.height / 2);
  await page.mouse.down(); await page.mouse.move(rect!.x + rect!.width / 2 + 12, rect!.y + rect!.height / 2, { steps: 6 });
  await expect(editor).not.toHaveValue(original);
  await expect(host.getByLabel('Retained selection')).toContainText('2–2');
  await page.mouse.up();
  await expect(host.getByLabel('Retained selection')).toContainText('committed');
  await host.getByRole('button', { name: 'Undo source edit' }).click();
  await expect(editor).toHaveValue(original);
  await expect(host.getByRole('button', { name: 'Undo source edit' })).toBeDisabled();
  await host.getByRole('button', { name: 'Redo source edit' }).click();
  await expect(editor).not.toHaveValue(original);
  await host.getByRole('button', { name: 'Undo source edit' }).click();
  await page.mouse.move(rect!.x + rect!.width / 2, rect!.y + rect!.height / 2); await page.mouse.down();
  await page.mouse.move(rect!.x + rect!.width / 2 + 8, rect!.y + rect!.height / 2, { steps: 4 });
  await label.press('Escape'); await page.mouse.up();
  await expect(editor).toHaveValue(original);
  await editor.focus(); await editor.press('ControlOrMeta+End'); await editor.press('ArrowLeft');
  const before = await editor.evaluate((el: HTMLTextAreaElement) => el.selectionStart);
  await host.locator('input').first().focus(); await host.locator('input').first().press('ArrowUp');
  const changed = await editor.inputValue(); expect(changed).toContain('7h');
  await host.locator('input').first().press('ArrowUp'); await host.locator('input').first().press('ArrowUp'); await host.locator('input').first().press('ArrowUp');
  await expect(host.getByLabel('Retained selection')).toContainText(`${before + 1}–${before + 1}`);
  await host.locator('input').first().press('ControlOrMeta+z');
  await expect(editor).toHaveValue(original.replace('6h', '9h'));
  await expect(host.getByLabel('Retained selection')).toContainText(`${before}–${before}`);
});
