// Generated by scripts/build-tokens.mjs from tokens/tokens.json (sound). Do not edit.
// The recipes the Web Audio engine plays; MetalSound.generated.swift carries the same table.
export const SOUND = {
  "policy": {
    "default": "off",
    "plays": {
      "acts": "acts and states",
      "states": "states only"
    },
    "rate": {
      "gapMs": 1500,
      "burst": 3,
      "burstWindowMs": 10000
    },
    "vary": {
      "f0": 0.03,
      "decay": 0.1,
      "filter": 0.06
    },
    "decayAfter": [
      [
        20,
        -2
      ],
      [
        60,
        -4
      ]
    ],
    "levelDb": {
      "act": -17,
      "beep": -20,
      "limit": -20
    },
    "sizeGain": [
      [
        32,
        0.55
      ],
      [
        64,
        0.75
      ],
      [
        160,
        1
      ]
    ]
  },
  "pitch": {
    "base": 2400,
    "ref": 16,
    "heavy": 0.35,
    "body": 320
  },
  "reach": {
    "own": {
      "send": 0.05,
      "pan": 0
    },
    "others": {
      "send": 0.22,
      "pan": 0.15
    },
    "world": {
      "send": 0.4,
      "pan": 0.25
    }
  },
  "room": {
    "seconds": 1.6,
    "curve": 3.2
  },
  "thump": {
    "from": 150,
    "to": 60,
    "ms": 90,
    "above": 0.5,
    "level": 0.36
  },
  "render": {
    "contactAttackMs": 0.8,
    "bandQ": 2.2,
    "bandGain": 1.6,
    "gritQ": 3,
    "gritMs": 3,
    "gritSpread": 0.3,
    "bouncePitch": 1.04,
    "ceilingHz": 16000
  },
  "materials": {
    "clay": {
      "f0x": 0.9,
      "tone": 0.8,
      "loud": 0.6,
      "attackMs": 3,
      "maxMs": 150,
      "modes": [
        [
          1,
          1,
          70
        ],
        [
          1.58,
          0.35,
          40
        ],
        [
          2.2,
          0.15,
          25
        ]
      ],
      "noise": [
        {
          "type": "bandpass",
          "f": 1500,
          "q": 1.2,
          "ms": 18,
          "gain": 0.81
        },
        {
          "type": "lowpass",
          "f": 700,
          "ms": 25,
          "gain": 0.36
        }
      ],
      "hear": "A soft, short, damp knock."
    },
    "ceramic": {
      "f0x": 1.3,
      "tone": 1,
      "loud": 1,
      "attackMs": 1.5,
      "maxMs": 450,
      "modes": [
        [
          1,
          1,
          320
        ],
        [
          2.4,
          0.5,
          200
        ],
        [
          4.6,
          0.2,
          120
        ]
      ],
      "noise": [
        {
          "type": "bandpass",
          "f": 4500,
          "q": 3,
          "ms": 20,
          "gain": 0.81
        }
      ],
      "hear": "A bright tink, like a cup."
    },
    "resin": {
      "f0x": 1.1,
      "tone": 0.9,
      "loud": 0.8,
      "attackMs": 1.5,
      "maxMs": 220,
      "modes": [
        [
          1,
          1,
          150
        ],
        [
          2.61,
          0.35,
          90
        ],
        [
          4.9,
          0.12,
          50
        ]
      ],
      "noise": [
        {
          "type": "bandpass",
          "f": 3000,
          "q": 1.5,
          "ms": 12,
          "gain": 0.72
        }
      ],
      "hear": "A hard, short, slightly hollow tock, like tapping a thick acrylic block."
    },
    "stone": {
      "f0x": 0.8,
      "tone": 0.8,
      "loud": 0.55,
      "attackMs": 1,
      "maxMs": 120,
      "noisyModes": true,
      "modes": [
        [
          1,
          1,
          35
        ],
        [
          1.73,
          0.6,
          25
        ],
        [
          2.91,
          0.35,
          18
        ],
        [
          4.14,
          0.2,
          12
        ]
      ],
      "noise": [
        {
          "type": "lowpass",
          "f": 900,
          "ms": 30,
          "gain": 0.9
        },
        {
          "type": "highpass",
          "f": 3000,
          "ms": 8,
          "gain": 0.18
        }
      ],
      "grit": {
        "n": 5,
        "spreadMs": 22,
        "f": 2200,
        "level": 0.22
      },
      "hear": "A dead, gritty knock that stops almost at once."
    },
    "glass": {
      "f0x": 2.1,
      "tone": 1,
      "loud": 1,
      "attackMs": 0.6,
      "maxMs": 320,
      "modes": [
        [
          1,
          1,
          260
        ],
        [
          2.32,
          0.4,
          150
        ],
        [
          4.25,
          0.2,
          80
        ]
      ],
      "noise": [
        {
          "type": "bandpass",
          "f": 8500,
          "q": 5,
          "ms": 7,
          "gain": 0.72
        }
      ],
      "hear": "A short, high, pure tink."
    },
    "metal": {
      "f0x": 0.7,
      "tone": 1,
      "loud": 1,
      "attackMs": 0.5,
      "maxMs": 1200,
      "modes": [
        [
          1,
          1,
          1100
        ],
        [
          1.006,
          0.8,
          1100
        ],
        [
          2.76,
          0.7,
          800
        ],
        [
          2.781,
          0.5,
          800
        ],
        [
          5.4,
          0.45,
          600
        ],
        [
          8.93,
          0.25,
          400
        ],
        [
          13.34,
          0.12,
          250
        ]
      ],
      "noise": [
        {
          "type": "bandpass",
          "f": 3500,
          "q": 1.2,
          "ms": 10,
          "gain": 1.08
        }
      ],
      "hear": "A lower clang that hangs on and beats."
    },
    "rubber": {
      "f0x": 0.95,
      "tone": 0.7,
      "loud": 0.7,
      "attackMs": 1.5,
      "maxMs": 120,
      "thump": false,
      "modes": [
        [
          1,
          1,
          45,
          0.93,
          18
        ],
        [
          2.3,
          0.3,
          22
        ]
      ],
      "noise": [
        {
          "type": "bandpass",
          "f": 1200,
          "q": 0.9,
          "ms": 12,
          "gain": 0.9
        },
        {
          "type": "lowpass",
          "f": 600,
          "ms": 16,
          "gain": 0.315
        }
      ],
      "bounce": {
        "ms": 70,
        "level": 0.25
      },
      "hear": "A short, dull pock with a little give, and a small second bounce."
    }
  },
  "beeper": {
    "resonance": 3200,
    "q": 6,
    "boostDb": 9,
    "square": 0.02,
    "attackMs": 2,
    "earcons": {
      "done": {
        "label": "Done",
        "notes": [
          [
            79,
            0,
            90,
            1
          ],
          [
            86,
            120,
            90,
            1
          ]
        ],
        "led": "green"
      },
      "failed": {
        "label": "Failed",
        "notes": [
          [
            67,
            0,
            90,
            1.2
          ],
          [
            67,
            150,
            120,
            0.8
          ],
          [
            68,
            150,
            120,
            0.8
          ]
        ],
        "led": "red"
      },
      "waiting": {
        "label": "Waiting",
        "notes": [
          [
            76,
            0,
            90,
            1
          ],
          [
            76,
            300,
            90,
            1
          ]
        ],
        "led": "amber"
      },
      "ready": {
        "label": "Ready",
        "notes": [
          [
            72,
            0,
            90,
            1
          ],
          [
            76,
            60,
            90,
            1
          ],
          [
            79,
            120,
            160,
            1
          ]
        ],
        "led": "green"
      }
    }
  }
} as const;
export type SoundMaterial = 'clay' | 'ceramic' | 'resin' | 'stone' | 'glass' | 'metal' | 'rubber';
export type Earcon = 'done' | 'failed' | 'waiting' | 'ready';
export type Reach = 'own' | 'others' | 'world';
export const SOUND_MATERIALS: readonly SoundMaterial[] = ['clay', 'ceramic', 'resin', 'stone', 'glass', 'metal', 'rubber'];
export const EARCONS: readonly Earcon[] = ['done', 'failed', 'waiting', 'ready'];
