// tokens/tokens.json (gadgets) → the gadget foundations for the web renderer and SwiftUI.
// `--check` fails instead of writing when an output is stale.
import { readFileSync, readdirSync } from 'node:fs';
import { pathToFileURL } from 'node:url';
import { root, emit, finish } from './lib/emit.mjs';

const T = JSON.parse(readFileSync(root('tokens/tokens.json'), 'utf8'));
const G = T.gadgets;

const camel = (k) => k.replace(/-([a-zA-Z0-9])/g, (_, c) => c.toUpperCase());
// Keys become camelCase, except names in the catalogs (parts, mechanisms, slots, jobs), which are looked up as written.
const NAMED = new Set(['parts', 'mechanisms', 'slots', 'jobs', 'materials']);
const strip = (v, named = false) => Array.isArray(v) ? v.map((x) => strip(x))
  : v && typeof v === 'object' ? Object.fromEntries(Object.entries(v).filter(([k]) => !k.startsWith('$')).map(([k, x]) => [named ? k : camel(k), strip(x, !named && NAMED.has(k))]))
  : v;
const num = (n) => (Number.isInteger(n) ? n.toFixed(1) : String(+n.toFixed(4)));
const keys = (o) => Object.keys(o).filter((k) => !k.startsWith('$'));

// One vocabulary: a material that looks has to sound, and the other way round.
const visual = keys(G.materials), acoustic = keys(T.sound.materials);
if (visual.join() !== acoustic.join()) {
  console.error(`gadgets: materials differ from sound.materials\n  gadgets: ${visual.join(', ')}\n  sound:   ${acoustic.join(', ')}`);
  process.exit(1);
}

emit('packages/metalui/src/gadgets/gadgets.generated.ts', `// Generated by scripts/build-gadgets.mjs from tokens/tokens.json (gadgets). Do not edit.
// The visual foundations of gadgets; the acoustic recipes are the sound foundation (same keys).
export const GADGETS = ${JSON.stringify(strip(G), null, 2)} as const;
export type GadgetMaterial = ${visual.map((m) => `'${m}'`).join(' | ')};
export const GADGET_MATERIALS: readonly GadgetMaterial[] = [${visual.map((m) => `'${m}'`).join(', ')}];
`);

const pair = (a) => `(${num(a[0])}, ${num(a[1])})`;
const shadow = ([b, x, y, a]) => `MetalGadgetShadow(blur: ${num(b)}, dx: ${num(x)}, dy: ${num(y)}, alpha: ${num(a)})`;
const material = ([k, m]) => `        case .${k}:
            return MetalGadgetFinish(
                lightness: ${pair(m.L)}, chromaCap: ${num(m['C-cap'])}, bevel: ${num(m.bevel)}, surfaceScale: ${num(m['surface-scale'])},
                diffuse: ${num(m.diffuse)}, glossExponent: ${num(m.gloss[0])}, glossStrength: ${num(m.gloss[1])},
                grainFrequency: ${num(m.grain[0])}, grainAmplitude: ${num(m.grain[1])}, grainDirectional: ${m['grain-direction'] !== undefined},
                flecks: ${num(m.flecks)}, translucency: ${num(m.translucency)},
                cast: ${shadow(m.shadow.cast)}, contact: ${shadow(m.shadow.contact)},
                sampleHue: ${num(m.sample)}, strikeTravel: ${num(G.strike.travel[k] ?? 0)}, strikeSquash: ${num(G.strike.squash[k] ?? 0)}
            )`;
emit('swift/Sources/MetalUI/Tokens/MetalGadgets.generated.swift', `// Generated by scripts/build-gadgets.mjs from tokens/tokens.json (gadgets). Do not edit.
// The visual foundations of gadgets; MetalSoundMaterial carries the acoustic recipes (same cases).

extension MetalSoundMaterial {
    /// The finish of a body cut from this material: how the one light shades it.
    public var finish: MetalGadgetFinish {
        switch self {
${Object.entries(G.materials).filter(([k]) => !k.startsWith('$')).map(material).join('\n')}
        }
    }
}

/// The gadget foundations that are not per material.
public enum MetalGadgetTokens {
    public static let canvas: Double = ${num(G.canvas.size)}
    public static let bodyRect: (x: Double, y: Double, width: Double, height: Double) = (${G.canvas.body.map(num).join(', ')})
    public static let bodyRadius: Double = ${num(G.canvas.radius)}
    public static let lightAzimuth: Double = ${num(G.light.azimuth)}
    public static let lightElevation: Double = ${num(G.light.elevation)}
    public static let partBevel: Double = ${num(G['part-scale'].bevel)}
    public static let partShadow: Double = ${num(G['part-scale'].shadow)}
    public static let holeBlur: Double = ${num(G.hole.blur)}
    public static let holeOffset: (dx: Double, dy: Double) = (${G.hole.offset.map(num).join(', ')})
    public static let holeAlpha: Double = ${num(G.hole.alpha)}
    public static let tierFull: Double = ${num(G.tiers.full)}
    public static let tierLite: Double = ${num(G.tiers.lite)}
    public static let liteBevel: Double = ${num(G.tiers['lite-bevel'])}
    public static let graphiteShadow: Double = ${num(G.host.graphite.shadow)}
    public static let graphiteBrightDrop: Double = ${num(G.host.graphite['bright-L-drop'])}
    public static let graphiteBrightAbove: Double = ${num(G.host.graphite['bright-L-above'])}
    public static let contrastShadow: Double = ${num(G.host.contrast.shadow)}
    public static let glintAbove: Double = ${num(G.strike['glint-above'])}
    public static let glintMs: Double = ${num(G.strike['glint-ms'])}
    public static let jackHole: Double = ${num(G.jack.hole)}
    public static let jackKnurls: Double = ${num(G.jack.knurls)}
    public static let jackKnurl: (Double, Double) = (${G.jack.knurl.map(num).join(', ')})
    public static let jackMetal: (L: Double, C: Double, H: Double) = (${G.jack.metal.map(num).join(', ')})
    public static let jackFloor: Double = ${num(G.jack.floor)}
    public static let plugSide: Double = ${num(G.plug.side)}
    public static let plugSkirt: Double = ${num(G.plug.skirt)}
    public static let plugKnurls: Int = ${G.plug.knurls}
    public static let plugKnurl: (Double, Double) = (${G.plug.knurl.map(num).join(', ')})
    public static let plugKnurlAlpha: Double = ${num(G.plug['knurl-alpha'])}
    public static let plugBoss: Double = ${num(G.plug.boss)}
    public static let plugStub: (length: Double, width: Double) = (${G.plug.stub.map(num).join(', ')})
    public static let plugShadow: (blur: Double, dx: Double, dy: Double, alpha: Double) = (${G.plug.shadow.map(num).join(', ')})
    public static let plugAlone: Double = ${num(G.plug.alone)}
    public static let plugFace: Double = ${num(G.plug.face)}
    public static let plugCentreY: Double = ${num(G.plug['centre-y'])}
    public static let plugStubFrom: Double = ${num(G.plug['stub-from'])}
    public static let plugStubL: Double = ${num(G.plug['stub-L'])}
    public static let plugStubChroma: Double = ${num(G.plug['stub-C'])}
    public static let plugFaceClay: Double = ${num(G.plug['face-clay'])}
    public static let plugFaceChroma: Double = ${num(G.plug['face-C'])}
    public static let plugBossDrop: Double = ${num(G.plug['boss-drop'])}
    public static let plugKnurlWidth: Double = ${num(G.plug['knurl-width'])}
    public static let cableWidth: Double = ${num(G.cable.width)}
    public static let cableSag: (share: Double, min: Double, max: Double) = (${G.cable.sag.map(num).join(', ')})
    public static let cableHandle: Double = ${num(G.cable.handle)}
    public static let cableRubber: (L: Double, C: Double) = (${G.cable.rubber.map(num).join(', ')})
    public static let cableShade: (drop: Double, width: Double, dx: Double, dy: Double) = (${G.cable.shade.map(num).join(', ')})
    public static let cableSheen: (width: Double, dx: Double, dy: Double, alpha: Double) = (${G.cable.sheen.map(num).join(', ')})
    public static let cableShadow: (blur: Double, dx: Double, dy: Double, alpha: Double) = (${G.cable.shadow.map(num).join(', ')})
    public static let cableSpring = MetalSprings.${G.cable.spring}
    public static let beeperAlone: Double = ${num(G.beeper.alone)}
    public static let beeperRadius: Double = ${num(G.beeper.radius)}
    public static let beeperSlots: Int = ${G.beeper.slots}
    public static let beeperSlot: (width: Double, height: Double) = (${G.beeper.slot.map(num).join(', ')})
    public static let beeperSpan: Double = ${num(G.beeper.span)}
    public static let beeperBrass: (L: Double, C: Double, H: Double) = (${G.beeper.brass.map(num).join(', ')})
    public static let beeperLitL: Double = ${num(G.beeper['lit-L'])}
    public static let beeperLift: Double = ${num(G.beeper.lift)}
    public static let beeperRiseMs: Double = ${num(G.beeper['rise-ms'])}
    public static let beeperFallMs: Double = ${num(G.beeper['fall-ms'])}
    public static let beeperSampleMs: Double = ${num(G.beeper['sample-ms'])}
    public static let beeperAspect: Double = ${num(G.parts.beeper.size[1] / G.parts.beeper.size[0])}
    public static let capRadius: Double = ${num(G.cap.radius)}
    public static let capSide: Double = ${num(G.cap.side)}
    public static let capSideDrop: Double = ${num(G.cap['side-drop'])}
    public static let capRibs: Int = ${G.cap.ribs}
    public static let capPitch: Double = ${num(G.cap.pitch)}
    public static let capSpan: Double = ${num(G.cap.span)}
    public static let capGroove: (width: Double, alpha: Double) = (${G.cap.groove.map(num).join(', ')})
    public static let capEdge: (width: Double, alpha: Double, dy: Double) = (${G.cap.edge.map(num).join(', ')})
    public static let capPointer: (from: Double, to: Double) = (${G.cap.pointer.map(num).join(', ')})
    public static let capPointerScale: Double = ${num(G.cap['pointer-scale'])}
    public static let capGrooveInk: (drop: Double, floor: Double, gain: Double, add: Double, max: Double) = (${G.cap['groove-ink'].map(num).join(', ')})
    public static let capEdgeInk: (lift: Double, chroma: Double) = (${G.cap['edge-ink'].map(num).join(', ')})
    public static let capPress: Double = ${num(G.cap.press)}
    public static let capPressShadow: Double = ${num(G.cap['press-shadow'])}
    public static let capPressSpring = MetalSprings.${G.cap['press-spring']}
    public static let capCeramic: (L: Double, C: Double) = (${G.cap.ceramic.map(num).join(', ')})
    public static let capAlone: Double = ${num(G.cap.alone)}
    public static let capShadow: (blur: Double, dx: Double, dy: Double, alpha: Double) = (${G.cap.shadow.map(num).join(', ')})
    public static let capSlot: (width: Double, pad: Double) = (${G.cap.slot.map(num).join(', ')})
    public static let detentSize: Double = ${num(G.drive['detent-size'])}
    public static let detentPitch: Double = ${num(G.drive['detent-pitch'])}
    public static let stopPitch: (bottom: Double, top: Double) = (${G.drive['stop-pitch'].map(num).join(', ')})
    public static let keyRadius: Double = ${num(G.key.radius)}
    public static let keySkirtDrop: Double = ${num(G.key['skirt-drop'])}
    public static let keyFace: (share: Double, radius: Double) = (${G.key.face.map(num).join(', ')})
    public static let keyFaceLift: Double = ${num(G.key['face-lift'])}
    public static let keyGlyph: Double = ${num(G.key.glyph)}
    public static let keyGlyphEdge: Double = ${num(G.key['glyph-edge'])}
    public static let keyGlyphAlpha: (ink: Double, edge: Double) = (${G.key['glyph-alpha'].map(num).join(', ')})
    public static let keyShadow: (blur: Double, dx: Double, dy: Double, alpha: Double) = (${G.key.shadow.map(num).join(', ')})
    public static let keyAlone: Double = ${num(G.key.alone)}
    public static let keyPress: (dy: Double, sx: Double, sy: Double) = (${G.key.press.map(num).join(', ')})
    public static let bezelWidth: Double = ${num(G.bezel.width)}
    public static let bezelOpeningRadius: Double = ${num(G.bezel['opening-radius'])}
    public static let bezelDepth: Double = ${num(G.bezel.depth)}
    public static let glassDepth: (centre: Double, rim: Double) = (${G.glass.depth.map(num).join(', ')})
    public static let glassRings: [Double] = [${G.glass.rings.map(num).join(', ')}]
    public static let glassLine: (width: Double, alpha: Double) = (${G.glass.line.map(num).join(', ')})
    public static let glassCross: Double = ${num(G.glass.cross)}
    public static let glassRim: (width: Double, alpha: Double) = (${G.glass.rim.map(num).join(', ')})
    public static let glassGlare: (cx: Double, cy: Double, width: Double, height: Double, alpha: Double) = (${G.glass.glare.map(num).join(', ')})
    public static let backlightGlow: Double = ${num(G.backlight.glow)}
    public static let backlightSpread: Double = ${num(G.backlight.spread)}
    public static let backlightSlices: Int = ${G.backlight.slices}
    public static let backlightLead: (width: Double, alpha: Double) = (${G.backlight.lead.map(num).join(', ')})
    /// A blip's hot core, a share of its radius.
    public static let backlightDot: Double = ${num(G.backlight.dot)}
    public static let backlightGlassLift: Double = ${num(G.backlight['glass-lift'])}
    public static let backlightAlpha: Double = ${num(G.backlight.alpha)}
    public static let backlightSliceAlpha: Double = ${num(G.backlight['slice-alpha'])}
    public static let backlightGlassChroma: Double = ${num(G.backlight['glass-chroma'])}
    /// A gadget lamp's lens [centre, edge] per signal, sRGB components.
    public static let lampColors: [String: ((Double, Double, Double), (Double, Double, Double))] = [${Object.entries(G.lamp).filter(([k]) => !k.startsWith('$')).map(([k, [a, b]]) => { const c = (h) => `(${[1, 3, 5].map((i) => num(parseInt(h.slice(i, i + 2), 16) / 255)).join(', ')})`; return `${JSON.stringify(k)}: (${c(a)}, ${c(b)})`; }).join(', ')}]
    public static let drumPitch: Double = ${num(G.drum.pitch)}
    public static let drumRadius: Double = ${num(G.drum.radius)}
    public static let drumGlyph: Double = ${num(G.drum.glyph)}
    public static let drumShade: (top: Double, bottom: Double) = (${G.drum.shade.map(num).join(', ')})
    public static let drumEdge: Double = ${num(G.drum.edge)}
    public static let drumGlint: (at: Double, width: Double, alpha: Double) = (${G.drum.glint.map(num).join(', ')})
    public static let drumAlone: Double = ${num(G.drum.alone)}
    public static let needleWidth: (base: Double, tip: Double) = (${num(G.needle.base)}, ${num(G.needle.tip)})
    public static let needleTail: Double = ${num(G.needle.tail)}
    public static let needleShadow: (blur: Double, dx: Double, dy: Double, alpha: Double) = (${G.needle.shadow.map(num).join(', ')})
    public static let needleCap: Double = ${num(G.needle.cap)}
    public static let needleScale: (inner: Double, outer: Double, major: Double) = (${G.needle.scale.map(num).join(', ')})
    public static let needleMajor: Int = ${G.needle.major}
    public static let needleLine: (width: Double, alpha: Double) = (${G.needle.line.map(num).join(', ')})
    public static let needleZone: (inner: Double, outer: Double, alpha: Double) = (${G.needle.zone.map(num).join(', ')})
    public static let needleMajorWidth: Double = ${num(G.needle['major-width'])}
    public static let needleCrown: Double = ${num(G.needle.crown)}
    public static let needleCapShadow: Double = ${num(G.needle['cap-shadow'])}
    public static let cellRadius: Double = ${num(G.cell.radius)}
    public static let cellDrop: Double = ${num(G.cell.drop)}
    public static let cellDepth: (share: Double, alpha: Double) = (${G.cell.depth.map(num).join(', ')})
    public static let cellLit: (lift: Double, chroma: Double, turn: Double) = (${G.cell.lit.map(num).join(', ')})
    public static let cellCore: (share: Double, lift: Double, turn: Double, chroma: Double) = (${G.cell.core.map(num).join(', ')})
    public static let cellHalo: (blur: Double, alpha: Double) = (${G.cell.halo.map(num).join(', ')})
    public static let cellShadow: (blur: Double, dx: Double, dy: Double, alpha: Double) = (${G.cell.shadow.map(num).join(', ')})
    public static let cellBacklight: (empty: Double, full: Double) = (${G.cell.backlight.map(num).join(', ')})
    public static let cellDye: Double = ${num(G.cell.dye)}
    public static let cellAlone: (side: Double, gap: Double) = (${G.cell.alone.map(num).join(', ')})
    public static let rigPitch: Double = ${num(G.rig.pitch)}
    public static let rigPadding: Double = ${num(G.rig.padding)}
    public static let rigRadius: Double = ${num(G.rig.radius)}
    public static let rigTray: Double = ${num(G.rig.tray)}
    public static let rigJack: Double = ${num(G.rig.jack)}
    public static let rigGap: Double = ${num(G.rig.gap)}
    public static let rigTop: Double = ${num(G.rig.top)}
    public static let rigSpacing: Double = ${num(G.rig.spacing)}
    public static let rigSlack: Double = ${num(G.rig.slack)}
    public static let rigTravel: Double = ${num(G.rig.travel)}
    public static let rigBead: (radius: Double, alpha: Double) = (${G.rig.bead.map(num).join(', ')})
    public static let rigVoices: Int = ${G.rig.voices}
    /// Each Part's footprint on the canvas, units: [width, height].
    public static let partSizes: [String: (Double, Double)] = [${Object.entries(G.parts).filter(([k]) => !k.startsWith('$')).map(([k, v]) => `${JSON.stringify(k)}: (${num(v.size[0])}, ${num(v.size[1])})`).join(', ')}]
    public static let jackKnurlWidth: Double = ${num(G.jack['knurl-width'])}
    public static let jackKnurlAlpha: Double = ${num(G.jack['knurl-alpha'])}
    public static let jackGlow: Double = ${num(G.jack.glow)}
    /// The jack's nut on the 400-unit canvas when a Part is drawn alone.
    public static let jackNut: Double = ${num(G.jack.alone)}
    public static let holeFloorDrop: Double = ${num(G.hole.floor.drop)}
    public static let holeFloorDepthDrop: Double = ${num(G.hole.floor['depth-drop'])}
    public static let holeFloorChroma: Double = ${num(G.hole.floor.chroma)}
    public static let holeLip: Double = ${num(G.hole.lip)}
    public static let holeLipAlpha: Double = ${num(G.hole['lip-alpha'])}
    public static let trayRadius: Double = ${num(G.hole['tray-radius'])}
    /// Default depth per cut kind, in units.
    public static let cutDepths: [String: Double] = [${Object.entries(G.hole.depths).map(([k, v]) => `${JSON.stringify(k)}: ${num(v)}`).join(', ')}]
    public static let glossElevation: Double = ${num(G.light['gloss-elevation'])}
    public static let litGain: Double = ${num(G.light['lit-gain'])}
    /// The shadow colour, sRGB components.
    public static let shadowColor: (red: Double, green: Double, blue: Double) = (${[1,3,5].map((i) => num(parseInt(G.light['shadow-color'].slice(i, i + 2), 16) / 255)).join(', ')})
    public static let grainLitGain: Double = ${num(G.surface['grain-lit-gain'])}
    public static let fleckGain: Double = ${num(G.surface.fleck.gain)}
    public static let fleckCut: Double = ${num(G.surface.fleck.cut)}
    public static let fleckScale: Double = ${num(G.surface.fleck.scale)}
    public static let fleckMax: Double = ${num(G.surface.fleck.max)}
    public static let fleckUniformCut: Double = ${num(G.surface.fleck['uniform-cut'])}
    public static let scatter: (Double, Double) = (${G.surface['translucent-core'].scatter.map(num).join(', ')})
}
`);

// ---------- Mechanisms (packages/metalui/gadgets/src/mechanisms/*.mjs) ----------
const { validateMechanism, compileMechanism } = await import(pathToFileURL(root('packages/metalui/gadgets/src/mechanism.mjs')).href);
const mechDir = root('packages/metalui/gadgets/src/mechanisms');
const MECHS = [];
for (const f of readdirSync(mechDir).filter((f) => f.endsWith('.mjs')).sort()) {
  const mod = await import(pathToFileURL(`${mechDir}/${f}`).href);
  for (const m of Object.values(mod)) {
    const bad = validateMechanism(m);
    if (bad.length) { console.error(`gadgets: mechanism ${f} breaks the contract\n  ${bad.join('\n  ')}`); process.exit(1); }
    MECHS.push(compileMechanism(m));
  }
}
// The shared sampler: a cubic-bezier easing between frames, the same maths the web player and
// MetalMechanismPlayer use. The samples are the parity fixture SwiftUI must reproduce.
const bez = ([x1, y1, x2, y2], x) => {
  if (x1 === y1 && x2 === y2) return x;
  let t = x;
  for (let i = 0; i < 8; i++) {
    const cx = 3 * x1 * t * (1 - t) ** 2 + 3 * x2 * t * t * (1 - t) + t ** 3 - x;
    const d = 3 * x1 * (1 - t) ** 2 + 6 * (x2 - x1) * t * (1 - t) + 3 * (1 - x2) * t * t;
    if (Math.abs(cx) < 1e-6 || d === 0) break;
    t = Math.min(1, Math.max(0, t - cx / d));
  }
  return 3 * y1 * t * (1 - t) ** 2 + 3 * y2 * t * t * (1 - t) + t ** 3;
};
const sample = (frames, at) => {
  let i = frames.findIndex((f) => f.at >= at);
  if (i <= 0) return frames[Math.max(0, i)];
  const a = frames[i - 1], b = frames[i], k = bez(a.ease, (at - a.at) / (b.at - a.at));
  const lerp = (u, v) => u + (v - u) * k;
  return { pose: Object.fromEntries(Object.keys(a.pose).map((c) => [c, lerp(a.pose[c], b.pose[c])])), opacity: a.opacity === null ? null : lerp(a.opacity, b.opacity ?? a.opacity) };
};
const samples = Object.fromEntries(MECHS.filter((m) => m.mode === 'momentary').map((m) => [m.name, Object.fromEntries(m.tracks.map((t) => {
  const out = [];
  for (let at = 0; at <= m.duration; at += 20) { const s = sample(t.frames, at); out.push([at, +s.pose.x.toFixed(4), +s.pose.y.toFixed(4), +s.pose.r.toFixed(4), +s.pose.sx.toFixed(4), +s.pose.sy.toFixed(4), s.opacity === null ? null : +s.opacity.toFixed(4)]); }
  return [t.part, out];
}))]));
emit('packages/metalui/src/gadgets/mechanisms.generated.ts', `// Generated by scripts/build-gadgets.mjs from packages/metalui/gadgets/src/mechanisms. Do not edit.
// How gadgets move when they act: tracks (poses as numbers, easings as cubic-bezier points), cues,
// held poses and what survives reduced motion. MetalMechanisms.generated.swift carries the same.
export const MECHANISMS = ${JSON.stringify(Object.fromEntries(MECHS.map((m) => [m.name, m])), null, 2)} as const;
`);
emit('packages/metalui/src/gadgets/fixtures/mechanism-samples.json', JSON.stringify(samples) + '\n');
const swiftPose = (p) => `.init(x: ${num(p.x)}, y: ${num(p.y)}, r: ${num(p.r)}, sx: ${num(p.sx)}, sy: ${num(p.sy)})`;
const swiftCue = (c) => `.init(at: ${c.at === undefined ? 'nil' : num(c.at)}, until: ${c.until === undefined ? 'nil' : num(c.until)}, kind: .${c.kind}, slot: ${c.slot ? JSON.stringify(c.slot) : 'nil'}, level: ${num(c.level ?? 1)}, pitch: ${num(c.pitch ?? 1)}, gesture: ${c.gesture ? `.${c.gesture}` : 'nil'})`;
emit('swift/Sources/MetalUI/Tokens/MetalMechanisms.generated.swift', `// Generated by scripts/build-gadgets.mjs from packages/metalui/gadgets/src/mechanisms. Do not edit.
// The same tracks and cues the web player runs (mechanisms.generated.ts).

extension MetalMechanism {
${MECHS.map((m) => `    /// ${m.caption}
    public static let ${m.name.replace(/-([a-z])/g, (_, c) => c.toUpperCase())} = MetalMechanism(
        name: ${JSON.stringify(m.name)}, momentary: ${m.mode === 'momentary'}, duration: ${num(m.duration)}, stagger: ${num(m.stagger ?? 0)}, loops: ${!!m.loop}, phased: [${Object.keys(m.phase ?? {}).map((k) => JSON.stringify(k)).join(', ')}], spring: .${m.spring},
        tracks: [
${m.tracks.map((t) => `            .init(part: ${JSON.stringify(t.part)}, frames: [${t.frames.map((f) => `.init(at: ${num(f.at)}, pose: ${swiftPose(f.pose)}, opacity: ${f.opacity === null ? 'nil' : num(f.opacity)}, ease: (${f.ease.map(num).join(', ')}))`).join(', ')}])`).join(',\n')}
        ],
        cues: [${m.cues.map(swiftCue).join(', ')}],
        states: [${Object.entries(m.states).map(([k, v]) => `${JSON.stringify(k)}: .init(hold: ${JSON.stringify(v.hold)}, pose: ${swiftPose({ x: 0, y: 0, r: 0, sx: 1, sy: 1, ...v.pose })})`).join(', ') || ':'}],
        reduced: [${m.reduced.map((r) => JSON.stringify(r)).join(', ')}],
        held: ${m.held ? `.init(slot: ${JSON.stringify(m.held.slot)}, from: ${swiftPose({ x: 0, y: 0, r: 0, sx: 1, sy: 1, ...m.held.from })}, to: ${swiftPose({ x: 0, y: 0, r: 0, sx: 1, sy: 1, ...m.held.to })}, detents: ${m.held.detents ?? 0}, stagger: ${num(m.held.stagger ?? 0)}, wall: ${num(m.held.wall ?? 0)}, impactFull: ${num(m.held.impactFull ?? 1)}, scrapeFull: ${num(m.held.scrapeFull ?? 1)}, tickMin: ${num(m.held.tickMin)}, tickGap: ${num(m.held.tickGap)}, step: ${num(m.held.step)}, roll: ${!!m.held.roll}, rest: ${num(m.held.rest ?? 0)})` : 'nil'}
    )`).join('\n\n')}

    public static let all: [MetalMechanism] = [${MECHS.map((m) => m.name.replace(/-([a-z])/g, (_, c) => c.toUpperCase())).join(', ')}]
}
`);

// The feel model, the job table, the accent and the set rules, for the Swift resolver.
const jobs = Object.entries(G.jobs).filter(([k]) => !k.startsWith('$'));
const rules = G.feel['material-rules'].map(([r, m]) => {
  const terms = r === '*' ? [] : r.split('&').map((t) => { const [, k, op, v] = t.match(/^([vaw])(>=|<=)([\d.]+)$/); return `(.${k}, ${op === '>=' ? 'true' : 'false'}, ${num(+v)})`; });
  return `        (rule: ${JSON.stringify(r)}, terms: [${terms.join(', ')}], material: .${m})`;
}).join(',\n');
emit('swift/Sources/MetalUI/Tokens/MetalGadgetFeel.generated.swift', `// Generated by scripts/build-gadgets.mjs from tokens/tokens.json (gadgets.feel, .jobs, .accent, .set). Do not edit.
// The feel model the Swift resolver runs; resolve.ts runs the same numbers.

/// What a gadget means: a closed list of verbs.
public enum MetalGadgetJob: String, CaseIterable, Sendable {
${jobs.map(([k]) => `    case ${k}`).join('\n')}

    /// Hue stations: a job owns its hues, so jobs never share one.
    public var stations: [Double] { switch self { ${jobs.map(([k, j]) => `case .${k}: return [${j.stations.map(num).join(', ')}]`).join('; ')} } }
    public var reach: MetalSoundReach { switch self { ${jobs.map(([k, j]) => `case .${k}: return .${j.reach}`).join('; ')} } }
    public var containers: [String] { switch self { ${jobs.map(([k, j]) => `case .${k}: return [${j.containers.map((c) => JSON.stringify(c)).join(', ')}]`).join('; ')} } }
    public var pin: MetalSoundMaterial? { switch self { ${jobs.map(([k, j]) => `case .${k}: return ${j.pin ? `.${j.pin}` : 'nil'}`).join('; ')} } }
    public var bodyChromaMax: Double? { switch self { ${jobs.map(([k, j]) => `case .${k}: return ${j['body-C-max'] !== undefined ? num(j['body-C-max']) : 'nil'}`).join('; ')} } }
}

public enum MetalGadgetFeelTokens {
    public static let lightness = (base: ${num(G.feel.L.base)}, weight: ${num(G.feel.L.W)}, valence: ${num(G.feel.L.V)})
    public static let chroma = (base: ${num(G.feel.C.base)}, arousal: ${num(G.feel.C.A)}, mix: (${G.feel.C['V-mix'].map(num).join(', ')}))
    public static let hue = (valence: ${num(G.feel.H.V)}, weight: ${num(G.feel.H.W)})
    /// First match wins. Each term: (axis, at least?, threshold).
    public static let materialRules: [(rule: String, terms: [(MetalGadgetAxis, Bool, Double)], material: MetalSoundMaterial)] = [
${rules}
    ]
    public static let registerThresholds: (Double, Double) = (${G.feel.register.thresholds.map(num).join(', ')})
    public static let registerMidi: (Int, Int, Int) = (${G.feel.register['base-midi'].join(', ')})
    public static let accentWarm: (L: Double, C: Double, H: Double) = (${G.accent.warm.map(num).join(', ')})
    public static let accentCool: (L: Double, C: Double, H: Double) = (${G.accent.cool.map(num).join(', ')})
    public static let accentFlipWithin: Double = ${num(G.accent['flip-within-deg'])}
    public static let accentFlipMinChroma: Double = ${num(G.accent['flip-min-C'])}
    /// A glass face's own ranges: light and icy, apart from a glass body's dark ones.
    public static let glassFaceLightness: (Double, Double) = (${G.materials.glass['face-L'].map(num).join(', ')})
    public static let glassFaceChromaCap: Double = ${num(G.materials.glass['face-C-cap'])}
    public static let accentMinChroma: Double = ${num(G.accent['min-C'])}
    public static let setHueGap: Double = ${num(G.set['hue-gap'])}
    public static let setHueMinChroma: Double = ${num(G.set['hue-min-C'])}
    public static let setBands: (Double, Double) = (${G.set.bands.map(num).join(', ')})
    public static let setDeltaE: Double = ${num(G.set['delta-e'])}
    public static let setCvdDeltaE: Double = ${num(G.set['cvd-delta-e'])}
    public static let setSlabRun: Int = ${G.set['slab-run']}
}
`);
finish('gadgets');
