// tokens/tokens.json (gadgets) → the gadget foundations for the web renderer and SwiftUI.
// `--check` fails instead of writing when an output is stale.
import { readFileSync } from 'node:fs';
import { root, emit, finish } from './lib/emit.mjs';

const T = JSON.parse(readFileSync(root('tokens/tokens.json'), 'utf8'));
const G = T.gadgets;

const camel = (k) => k.replace(/-([a-zA-Z0-9])/g, (_, c) => c.toUpperCase());
const strip = (v) => Array.isArray(v) ? v.map(strip)
  : v && typeof v === 'object' ? Object.fromEntries(Object.entries(v).filter(([k]) => !k.startsWith('$')).map(([k, x]) => [camel(k), strip(x)]))
  : v;
const num = (n) => (Number.isInteger(n) ? n.toFixed(1) : String(+n.toFixed(4)));
const keys = (o) => Object.keys(o).filter((k) => !k.startsWith('$'));

// One vocabulary: a material that looks has to sound, and the other way round.
const visual = keys(G.materials), acoustic = keys(T.sound.materials);
if (visual.join() !== acoustic.join()) {
  console.error(`gadgets: materials differ from sound.materials\n  gadgets: ${visual.join(', ')}\n  sound:   ${acoustic.join(', ')}`);
  process.exit(1);
}

emit('packages/metalui/src/gadgets/gadgets.generated.ts', `// Generated by scripts/build-gadgets.mjs from tokens/tokens.json (gadgets). Do not edit.
// The visual foundations of gadgets; the acoustic recipes are the sound foundation (same keys).
export const GADGETS = ${JSON.stringify(strip(G), null, 2)} as const;
export type GadgetMaterial = ${visual.map((m) => `'${m}'`).join(' | ')};
export const GADGET_MATERIALS: readonly GadgetMaterial[] = [${visual.map((m) => `'${m}'`).join(', ')}];
`);

const pair = (a) => `(${num(a[0])}, ${num(a[1])})`;
const shadow = ([b, x, y, a]) => `MetalGadgetShadow(blur: ${num(b)}, dx: ${num(x)}, dy: ${num(y)}, alpha: ${num(a)})`;
const material = ([k, m]) => `        case .${k}:
            return MetalGadgetFinish(
                lightness: ${pair(m.L)}, chromaCap: ${num(m['C-cap'])}, bevel: ${num(m.bevel)}, surfaceScale: ${num(m['surface-scale'])},
                diffuse: ${num(m.diffuse)}, glossExponent: ${num(m.gloss[0])}, glossStrength: ${num(m.gloss[1])},
                grainFrequency: ${num(m.grain[0])}, grainAmplitude: ${num(m.grain[1])}, grainDirectional: ${m['grain-direction'] !== undefined},
                flecks: ${num(m.flecks)}, translucency: ${num(m.translucency)},
                cast: ${shadow(m.shadow.cast)}, contact: ${shadow(m.shadow.contact)},
                sampleHue: ${num(m.sample)}, strikeTravel: ${num(G.strike.travel[k] ?? 0)}, strikeSquash: ${num(G.strike.squash[k] ?? 0)}
            )`;
emit('swift/Sources/MetalUI/Tokens/MetalGadgets.generated.swift', `// Generated by scripts/build-gadgets.mjs from tokens/tokens.json (gadgets). Do not edit.
// The visual foundations of gadgets; MetalSoundMaterial carries the acoustic recipes (same cases).

extension MetalSoundMaterial {
    /// The finish of a body cut from this material: how the one light shades it.
    public var finish: MetalGadgetFinish {
        switch self {
${Object.entries(G.materials).filter(([k]) => !k.startsWith('$')).map(material).join('\n')}
        }
    }
}

/// The gadget foundations that are not per material.
public enum MetalGadgetTokens {
    public static let canvas: Double = ${num(G.canvas.size)}
    public static let bodyRect: (x: Double, y: Double, width: Double, height: Double) = (${G.canvas.body.map(num).join(', ')})
    public static let bodyRadius: Double = ${num(G.canvas.radius)}
    public static let lightAzimuth: Double = ${num(G.light.azimuth)}
    public static let lightElevation: Double = ${num(G.light.elevation)}
    public static let partBevel: Double = ${num(G['part-scale'].bevel)}
    public static let partShadow: Double = ${num(G['part-scale'].shadow)}
    public static let holeBlur: Double = ${num(G.hole.blur)}
    public static let holeOffset: (dx: Double, dy: Double) = (${G.hole.offset.map(num).join(', ')})
    public static let holeAlpha: Double = ${num(G.hole.alpha)}
    public static let tierFull: Double = ${num(G.tiers.full)}
    public static let tierLite: Double = ${num(G.tiers.lite)}
    public static let liteBevel: Double = ${num(G.tiers['lite-bevel'])}
    public static let graphiteShadow: Double = ${num(G.host.graphite.shadow)}
    public static let graphiteBrightDrop: Double = ${num(G.host.graphite['bright-L-drop'])}
    public static let graphiteBrightAbove: Double = ${num(G.host.graphite['bright-L-above'])}
    public static let contrastShadow: Double = ${num(G.host.contrast.shadow)}
    public static let glintAbove: Double = ${num(G.strike['glint-above'])}
    public static let glintMs: Double = ${num(G.strike['glint-ms'])}
    public static let glossElevation: Double = ${num(G.light['gloss-elevation'])}
    public static let litGain: Double = ${num(G.light['lit-gain'])}
    /// The shadow colour, sRGB components.
    public static let shadowColor: (red: Double, green: Double, blue: Double) = (${[1,3,5].map((i) => num(parseInt(G.light['shadow-color'].slice(i, i + 2), 16) / 255)).join(', ')})
    public static let grainLitGain: Double = ${num(G.surface['grain-lit-gain'])}
    public static let fleckGain: Double = ${num(G.surface.fleck.gain)}
    public static let fleckCut: Double = ${num(G.surface.fleck.cut)}
    public static let fleckScale: Double = ${num(G.surface.fleck.scale)}
    public static let fleckMax: Double = ${num(G.surface.fleck.max)}
    public static let fleckUniformCut: Double = ${num(G.surface.fleck['uniform-cut'])}
    public static let scatter: (Double, Double) = (${G.surface['translucent-core'].scatter.map(num).join(', ')})
}
`);

finish('gadgets');
