// tokens/tokens.json → components/tokens.css + swift/Sources/MetalUI/Tokens/MetalTokens.generated.swift
// `--check` fails instead of writing when an output is stale.
import { readFileSync } from 'node:fs';
import { root, emit, finish } from './lib/emit.mjs';

const T = JSON.parse(readFileSync(root('tokens/tokens.json'), 'utf8'));

// ---------- CSS ----------
const decl = (obj, prefix = '') =>
  Object.entries(obj).map(([k, v]) => `  --mu-${prefix}${k}: ${v};`).join('\n');

const springs = Object.entries(T.springs)
  .map(([k, s]) => `  /* k=${s.stiffness} c=${s.damping}: ${s.use} */\n  --mu-spring-${k}: ${s.css};\n  --mu-spring-${k}-d: ${s.duration}s;`)
  .join('\n');
const caps = Object.entries(T.caps).map(([k, c]) => decl(c, `${k}-`)).join('\n');

const css = `/* Generated by scripts/build-tokens.mjs from tokens/tokens.json. Do not edit. */
/* Values are the approved Soft Hardware object sheet (Rev B). */
:root {
${decl(T.shared)}
${springs}
${caps}
}

:root,
[data-mu-colorway="bone"] {
  color-scheme: light;
${decl(T.colorways.bone)}
}

[data-mu-colorway="graphite"] {
  color-scheme: dark;
${decl(T.colorways.graphite)}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-mu-colorway="bone"]) {
    color-scheme: dark;
${decl(T.colorways.graphite).replace(/^/gm, '  ')}
  }
}
`;
emit('components/tokens.css', css);

// ---------- CSS value parsing (for Swift) ----------
function splitTop(s, sep = ',') {
  const out = []; let depth = 0, cur = '';
  for (const ch of s) {
    if (ch === '(') depth++;
    if (ch === ')') depth--;
    if (ch === sep && depth === 0) { out.push(cur.trim()); cur = ''; } else cur += ch;
  }
  if (cur.trim()) out.push(cur.trim());
  return out;
}
function color(s) {
  s = s.trim();
  let m = s.match(/^#([0-9a-f]{3}|[0-9a-f]{6})$/i);
  if (m) {
    const h = m[1].length === 3 ? [...m[1]].map((c) => c + c).join('') : m[1];
    return [0, 2, 4].map((i) => parseInt(h.slice(i, i + 2), 16)).concat(1);
  }
  m = s.match(/^rgba?\(([^)]*)\)$/);
  if (m) {
    const p = m[1].split(',').map((x) => parseFloat(x));
    return [p[0], p[1], p[2], p[3] ?? 1];
  }
  throw new Error(`unparsed color: ${s}`);
}
const num = (n) => (Number.isInteger(n) ? n.toFixed(1) : String(+n.toFixed(4)));
const rgbaSwift = ([r, g, b, a]) => `MetalRGBA(${r}, ${g}, ${b}, ${num(a)})`;

function shadows(s) {
  return splitTop(s).map((layer) => {
    const inset = /\binset\b/.test(layer);
    const rest = layer.replace(/\binset\b/, '').trim();
    const colorStart = rest.search(/(#|rgba?\()/);
    const lengths = rest.slice(0, colorStart).trim().split(/\s+/).map((x) => parseFloat(x));
    const [x = 0, y = 0, blur = 0, spread = 0] = lengths;
    return `MetalShadow(inset: ${inset}, x: ${num(x)}, y: ${num(y)}, blur: ${num(blur)}, spread: ${num(spread)}, color: ${rgbaSwift(color(rest.slice(colorStart)))})`;
  });
}
function linear(s) {
  const inner = s.match(/^linear-gradient\((.*)\)$/)[1];
  const parts = splitTop(inner);
  let angle = 180;
  if (/deg$/.test(parts[0])) angle = parseFloat(parts.shift());
  const stops = parts.map((p, i) => {
    const m = p.match(/^(.*?)(?:\s+([\d.]+)%)?$/);
    const loc = m[2] !== undefined ? +m[2] / 100 : i / Math.max(1, parts.length - 1);
    return `.init(${rgbaSwift(color(m[1]))}, ${num(loc)})`;
  });
  return `MetalGradient(angle: ${num(angle)}, stops: [${stops.join(', ')}])`;
}
function radial(s) {
  const inner = s.match(/^radial-gradient\((.*)\)$/)[1];
  const parts = splitTop(inner);
  const at = parts.shift().match(/at ([\d.]+)% ([\d.]+)%/);
  const stops = parts.map((p) => {
    const m = p.match(/^(#[0-9a-f]+|rgba?\([^)]*\))(?:\s+[\d.]+)?(?:\s+([\d.]+)%)?$/i);
    const pcts = p.match(/([\d.]+)%/g) ?? ['0%'];
    return `.init(${rgbaSwift(color(m[1]))}, ${num(parseFloat(pcts.at(-1)) / 100)})`;
  });
  return `MetalRadialGradient(center: .init(x: ${num(+at[1] / 100)}, y: ${num(+at[2] / 100)}), stops: [${stops.join(', ')}])`;
}
function swiftValue(v) {
  if (/^linear-gradient/.test(v)) return ['MetalGradient', linear(v)];
  if (/^radial-gradient/.test(v)) return ['MetalRadialGradient', radial(v)];
  if (/^-?[\d.]+$/.test(v)) return ['Double', num(+v)];
  if (/\d+px/.test(v) || /^inset|^0 /.test(v)) return ['[MetalShadow]', `[\n            ${shadows(v).join(',\n            ')},\n        ]`];
  return ['MetalRGBA', rgbaSwift(color(v))];
}
const camel = (k) => k.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());

// ---------- Swift ----------
const cwKeys = Object.keys(T.colorways.bone);
const cwFields = cwKeys.map((k) => `    public let ${camel(k)}: ${swiftValue(T.colorways.bone[k])[0]}`).join('\n');
const cwInstance = (cw) => `MetalColorwayTokens(\n${cwKeys.map((k) => `        ${camel(k)}: ${swiftValue(T.colorways[cw][k])[1]}`).join(',\n')}\n    )`;

const swiftShared = Object.entries(T.shared)
  .filter(([, v]) => !/^cubic-bezier|"|,\s*sans-serif|monospace/.test(v))
  .map(([k, v]) => { const [type, val] = swiftValue(v); return `    public static let ${camel(k)}: ${type} = ${val}`; })
  .join('\n');
const capKeys = Object.keys(T.caps.primary);
const swiftCaps = Object.entries(T.caps).map(([k, c]) =>
  `    public static let ${camel(k)} = MetalCapTokens(\n${capKeys.map((ck) => `        ${camel(ck)}: ${swiftValue(c[ck])[1]}`).join(',\n')}\n    )`).join('\n');
const swiftSprings = Object.entries(T.springs)
  .map(([k, s]) => `    /// ${s.use}\n    public static let ${k} = MetalSpring(stiffness: ${num(s.stiffness)}, damping: ${num(s.damping)}, duration: ${num(s.duration)})`)
  .join('\n');

const swift = `// Generated by scripts/build-tokens.mjs from tokens/tokens.json. Do not edit.
// Values are the approved Soft Hardware object sheet (Rev B); the CSS twin is components/tokens.css.

/// Every value one colorway supplies. Mirrors the \`--mu-*\` colorway custom properties.
public struct MetalColorwayTokens: Sendable {
${cwFields}
}

/// A signal cap (primary, destructive) that looks the same in both colorways.
public struct MetalCapTokens: Sendable {
${capKeys.map((k) => `    public let ${camel(k)}: ${swiftValue(T.caps.primary[k])[0]}`).join('\n')}
}

public enum MetalTokens {
    public static let bone = ${cwInstance('bone')}

    public static let graphite = ${cwInstance('graphite')}
}

public enum MetalShared {
${swiftShared}
}

public enum MetalCaps {
${swiftCaps}
}

public enum MetalSprings {
${swiftSprings}
}
`;
emit('swift/Sources/MetalUI/Tokens/MetalTokens.generated.swift', swift);
finish('tokens');
