// tokens/tokens.json (gadgets) → the gadget foundations for the web renderer and SwiftUI.
// `--check` fails instead of writing when an output is stale.
import { readFileSync, readdirSync } from 'node:fs';
import { pathToFileURL } from 'node:url';
import { root, emit, finish } from './lib/emit.mjs';

const T = JSON.parse(readFileSync(root('tokens/tokens.json'), 'utf8'));
const G = T.gadgets;

const camel = (k) => k.replace(/-([a-zA-Z0-9])/g, (_, c) => c.toUpperCase());
// Keys become camelCase, except names in the catalogs (parts, mechanisms, slots, jobs), which are looked up as written.
const NAMED = new Set(['parts', 'mechanisms', 'slots', 'jobs', 'materials']);
const strip = (v, named = false) => Array.isArray(v) ? v.map((x) => strip(x))
  : v && typeof v === 'object' ? Object.fromEntries(Object.entries(v).filter(([k]) => !k.startsWith('$')).map(([k, x]) => [named ? k : camel(k), strip(x, !named && NAMED.has(k))]))
  : v;
const num = (n) => (Number.isInteger(n) ? n.toFixed(1) : String(+n.toFixed(4)));
const keys = (o) => Object.keys(o).filter((k) => !k.startsWith('$'));

// One vocabulary: a material that looks has to sound, and the other way round.
const visual = keys(G.materials), acoustic = keys(T.sound.materials);
if (visual.join() !== acoustic.join()) {
  console.error(`gadgets: materials differ from sound.materials\n  gadgets: ${visual.join(', ')}\n  sound:   ${acoustic.join(', ')}`);
  process.exit(1);
}

emit('packages/metalui/src/gadgets/gadgets.generated.ts', `// Generated by scripts/build-gadgets.mjs from tokens/tokens.json (gadgets). Do not edit.
// The visual foundations of gadgets; the acoustic recipes are the sound foundation (same keys).
export const GADGETS = ${JSON.stringify(strip(G), null, 2)} as const;
export type GadgetMaterial = ${visual.map((m) => `'${m}'`).join(' | ')};
export const GADGET_MATERIALS: readonly GadgetMaterial[] = [${visual.map((m) => `'${m}'`).join(', ')}];
`);

const pair = (a) => `(${num(a[0])}, ${num(a[1])})`;
const shadow = ([b, x, y, a]) => `MetalGadgetShadow(blur: ${num(b)}, dx: ${num(x)}, dy: ${num(y)}, alpha: ${num(a)})`;
const material = ([k, m]) => `        case .${k}:
            return MetalGadgetFinish(
                lightness: ${pair(m.L)}, chromaCap: ${num(m['C-cap'])}, bevel: ${num(m.bevel)}, surfaceScale: ${num(m['surface-scale'])},
                diffuse: ${num(m.diffuse)}, glossExponent: ${num(m.gloss[0])}, glossStrength: ${num(m.gloss[1])},
                grainFrequency: ${num(m.grain[0])}, grainAmplitude: ${num(m.grain[1])}, grainDirectional: ${m['grain-direction'] !== undefined},
                flecks: ${num(m.flecks)}, translucency: ${num(m.translucency)},
                cast: ${shadow(m.shadow.cast)}, contact: ${shadow(m.shadow.contact)},
                sampleHue: ${num(m.sample)}, strikeTravel: ${num(G.strike.travel[k] ?? 0)}, strikeSquash: ${num(G.strike.squash[k] ?? 0)}
            )`;
emit('swift/Sources/MetalUI/Tokens/MetalGadgets.generated.swift', `// Generated by scripts/build-gadgets.mjs from tokens/tokens.json (gadgets). Do not edit.
// The visual foundations of gadgets; MetalSoundMaterial carries the acoustic recipes (same cases).

extension MetalSoundMaterial {
    /// The finish of a body cut from this material: how the one light shades it.
    public var finish: MetalGadgetFinish {
        switch self {
${Object.entries(G.materials).filter(([k]) => !k.startsWith('$')).map(material).join('\n')}
        }
    }
}

/// The gadget foundations that are not per material.
public enum MetalGadgetTokens {
    public static let canvas: Double = ${num(G.canvas.size)}
    public static let bodyRect: (x: Double, y: Double, width: Double, height: Double) = (${G.canvas.body.map(num).join(', ')})
    public static let bodyRadius: Double = ${num(G.canvas.radius)}
    public static let lightAzimuth: Double = ${num(G.light.azimuth)}
    public static let lightElevation: Double = ${num(G.light.elevation)}
    public static let partBevel: Double = ${num(G['part-scale'].bevel)}
    public static let partShadow: Double = ${num(G['part-scale'].shadow)}
    public static let holeBlur: Double = ${num(G.hole.blur)}
    public static let holeOffset: (dx: Double, dy: Double) = (${G.hole.offset.map(num).join(', ')})
    public static let holeAlpha: Double = ${num(G.hole.alpha)}
    public static let tierFull: Double = ${num(G.tiers.full)}
    public static let tierLite: Double = ${num(G.tiers.lite)}
    public static let liteBevel: Double = ${num(G.tiers['lite-bevel'])}
    public static let graphiteShadow: Double = ${num(G.host.graphite.shadow)}
    public static let graphiteBrightDrop: Double = ${num(G.host.graphite['bright-L-drop'])}
    public static let graphiteBrightAbove: Double = ${num(G.host.graphite['bright-L-above'])}
    public static let contrastShadow: Double = ${num(G.host.contrast.shadow)}
    public static let glintAbove: Double = ${num(G.strike['glint-above'])}
    public static let glintMs: Double = ${num(G.strike['glint-ms'])}
    public static let holeFloorDrop: Double = ${num(G.hole.floor.drop)}
    public static let holeFloorDepthDrop: Double = ${num(G.hole.floor['depth-drop'])}
    public static let holeFloorChroma: Double = ${num(G.hole.floor.chroma)}
    public static let holeLip: Double = ${num(G.hole.lip)}
    public static let holeLipAlpha: Double = ${num(G.hole['lip-alpha'])}
    public static let trayRadius: Double = ${num(G.hole['tray-radius'])}
    /// Default depth per cut kind, in units.
    public static let cutDepths: [String: Double] = [${Object.entries(G.hole.depths).map(([k, v]) => `${JSON.stringify(k)}: ${num(v)}`).join(', ')}]
    public static let glossElevation: Double = ${num(G.light['gloss-elevation'])}
    public static let litGain: Double = ${num(G.light['lit-gain'])}
    /// The shadow colour, sRGB components.
    public static let shadowColor: (red: Double, green: Double, blue: Double) = (${[1,3,5].map((i) => num(parseInt(G.light['shadow-color'].slice(i, i + 2), 16) / 255)).join(', ')})
    public static let grainLitGain: Double = ${num(G.surface['grain-lit-gain'])}
    public static let fleckGain: Double = ${num(G.surface.fleck.gain)}
    public static let fleckCut: Double = ${num(G.surface.fleck.cut)}
    public static let fleckScale: Double = ${num(G.surface.fleck.scale)}
    public static let fleckMax: Double = ${num(G.surface.fleck.max)}
    public static let fleckUniformCut: Double = ${num(G.surface.fleck['uniform-cut'])}
    public static let scatter: (Double, Double) = (${G.surface['translucent-core'].scatter.map(num).join(', ')})
}
`);

// ---------- Mechanisms (packages/metalui/gadgets/src/mechanisms/*.mjs) ----------
const { validateMechanism, compileMechanism } = await import(pathToFileURL(root('packages/metalui/gadgets/src/mechanism.mjs')).href);
const mechDir = root('packages/metalui/gadgets/src/mechanisms');
const MECHS = [];
for (const f of readdirSync(mechDir).filter((f) => f.endsWith('.mjs')).sort()) {
  const mod = await import(pathToFileURL(`${mechDir}/${f}`).href);
  for (const m of Object.values(mod)) {
    const bad = validateMechanism(m);
    if (bad.length) { console.error(`gadgets: mechanism ${f} breaks the contract\n  ${bad.join('\n  ')}`); process.exit(1); }
    MECHS.push(compileMechanism(m));
  }
}
// The shared sampler: a cubic-bezier easing between frames, the same maths the web player and
// MetalMechanismPlayer use. The samples are the parity fixture SwiftUI must reproduce.
const bez = ([x1, y1, x2, y2], x) => {
  if (x1 === y1 && x2 === y2) return x;
  let t = x;
  for (let i = 0; i < 8; i++) {
    const cx = 3 * x1 * t * (1 - t) ** 2 + 3 * x2 * t * t * (1 - t) + t ** 3 - x;
    const d = 3 * x1 * (1 - t) ** 2 + 6 * (x2 - x1) * t * (1 - t) + 3 * (1 - x2) * t * t;
    if (Math.abs(cx) < 1e-6 || d === 0) break;
    t = Math.min(1, Math.max(0, t - cx / d));
  }
  return 3 * y1 * t * (1 - t) ** 2 + 3 * y2 * t * t * (1 - t) + t ** 3;
};
const sample = (frames, at) => {
  let i = frames.findIndex((f) => f.at >= at);
  if (i <= 0) return frames[Math.max(0, i)];
  const a = frames[i - 1], b = frames[i], k = bez(a.ease, (at - a.at) / (b.at - a.at));
  const lerp = (u, v) => u + (v - u) * k;
  return { pose: Object.fromEntries(Object.keys(a.pose).map((c) => [c, lerp(a.pose[c], b.pose[c])])), opacity: a.opacity === null ? null : lerp(a.opacity, b.opacity ?? a.opacity) };
};
const samples = Object.fromEntries(MECHS.filter((m) => m.mode === 'momentary').map((m) => [m.name, Object.fromEntries(m.tracks.map((t) => {
  const out = [];
  for (let at = 0; at <= m.duration; at += 20) { const s = sample(t.frames, at); out.push([at, +s.pose.x.toFixed(4), +s.pose.y.toFixed(4), +s.pose.r.toFixed(4), +s.pose.sx.toFixed(4), +s.pose.sy.toFixed(4), s.opacity === null ? null : +s.opacity.toFixed(4)]); }
  return [t.part, out];
}))]));
emit('packages/metalui/src/gadgets/mechanisms.generated.ts', `// Generated by scripts/build-gadgets.mjs from packages/metalui/gadgets/src/mechanisms. Do not edit.
// How gadgets move when they act: tracks (poses as numbers, easings as cubic-bezier points), cues,
// held poses and what survives reduced motion. MetalMechanisms.generated.swift carries the same.
export const MECHANISMS = ${JSON.stringify(Object.fromEntries(MECHS.map((m) => [m.name, m])), null, 2)} as const;
`);
emit('packages/metalui/src/gadgets/fixtures/mechanism-samples.json', JSON.stringify(samples) + '\n');
const swiftPose = (p) => `.init(x: ${num(p.x)}, y: ${num(p.y)}, r: ${num(p.r)}, sx: ${num(p.sx)}, sy: ${num(p.sy)})`;
const swiftCue = (c) => `.init(at: ${c.at === undefined ? 'nil' : num(c.at)}, until: ${c.until === undefined ? 'nil' : num(c.until)}, kind: .${c.kind}, slot: ${c.slot ? JSON.stringify(c.slot) : 'nil'}, level: ${num(c.level ?? 1)}, pitch: ${num(c.pitch ?? 1)}, gesture: ${c.gesture ? `.${c.gesture}` : 'nil'})`;
emit('swift/Sources/MetalUI/Tokens/MetalMechanisms.generated.swift', `// Generated by scripts/build-gadgets.mjs from packages/metalui/gadgets/src/mechanisms. Do not edit.
// The same tracks and cues the web player runs (mechanisms.generated.ts).

extension MetalMechanism {
${MECHS.map((m) => `    /// ${m.caption}
    public static let ${m.name.replace(/-([a-z])/g, (_, c) => c.toUpperCase())} = MetalMechanism(
        name: ${JSON.stringify(m.name)}, momentary: ${m.mode === 'momentary'}, duration: ${num(m.duration)}, spring: .${m.spring},
        tracks: [
${m.tracks.map((t) => `            .init(part: ${JSON.stringify(t.part)}, frames: [${t.frames.map((f) => `.init(at: ${num(f.at)}, pose: ${swiftPose(f.pose)}, opacity: ${f.opacity === null ? 'nil' : num(f.opacity)}, ease: (${f.ease.map(num).join(', ')}))`).join(', ')}])`).join(',\n')}
        ],
        cues: [${m.cues.map(swiftCue).join(', ')}],
        states: [${Object.entries(m.states).map(([k, v]) => `${JSON.stringify(k)}: .init(hold: ${JSON.stringify(v.hold)}, pose: ${swiftPose({ x: 0, y: 0, r: 0, sx: 1, sy: 1, ...v.pose })})`).join(', ') || ':'}],
        reduced: [${m.reduced.map((r) => JSON.stringify(r)).join(', ')}]
    )`).join('\n\n')}

    public static let all: [MetalMechanism] = [${MECHS.map((m) => m.name.replace(/-([a-z])/g, (_, c) => c.toUpperCase())).join(', ')}]
}
`);

// The feel model, the job table, the accent and the set rules, for the Swift resolver.
const jobs = Object.entries(G.jobs).filter(([k]) => !k.startsWith('$'));
const rules = G.feel['material-rules'].map(([r, m]) => {
  const terms = r === '*' ? [] : r.split('&').map((t) => { const [, k, op, v] = t.match(/^([vaw])(>=|<=)([\d.]+)$/); return `(.${k}, ${op === '>=' ? 'true' : 'false'}, ${num(+v)})`; });
  return `        (rule: ${JSON.stringify(r)}, terms: [${terms.join(', ')}], material: .${m})`;
}).join(',\n');
emit('swift/Sources/MetalUI/Tokens/MetalGadgetFeel.generated.swift', `// Generated by scripts/build-gadgets.mjs from tokens/tokens.json (gadgets.feel, .jobs, .accent, .set). Do not edit.
// The feel model the Swift resolver runs; resolve.ts runs the same numbers.

/// What a gadget means: a closed list of verbs.
public enum MetalGadgetJob: String, CaseIterable, Sendable {
${jobs.map(([k]) => `    case ${k}`).join('\n')}

    /// Hue stations: a job owns its hues, so jobs never share one.
    public var stations: [Double] { switch self { ${jobs.map(([k, j]) => `case .${k}: return [${j.stations.map(num).join(', ')}]`).join('; ')} } }
    public var reach: MetalSoundReach { switch self { ${jobs.map(([k, j]) => `case .${k}: return .${j.reach}`).join('; ')} } }
    public var containers: [String] { switch self { ${jobs.map(([k, j]) => `case .${k}: return [${j.containers.map((c) => JSON.stringify(c)).join(', ')}]`).join('; ')} } }
    public var pin: MetalSoundMaterial? { switch self { ${jobs.map(([k, j]) => `case .${k}: return ${j.pin ? `.${j.pin}` : 'nil'}`).join('; ')} } }
    public var bodyChromaMax: Double? { switch self { ${jobs.map(([k, j]) => `case .${k}: return ${j['body-C-max'] !== undefined ? num(j['body-C-max']) : 'nil'}`).join('; ')} } }
}

public enum MetalGadgetFeelTokens {
    public static let lightness = (base: ${num(G.feel.L.base)}, weight: ${num(G.feel.L.W)}, valence: ${num(G.feel.L.V)})
    public static let chroma = (base: ${num(G.feel.C.base)}, arousal: ${num(G.feel.C.A)}, mix: (${G.feel.C['V-mix'].map(num).join(', ')}))
    public static let hue = (valence: ${num(G.feel.H.V)}, weight: ${num(G.feel.H.W)})
    /// First match wins. Each term: (axis, at least?, threshold).
    public static let materialRules: [(rule: String, terms: [(MetalGadgetAxis, Bool, Double)], material: MetalSoundMaterial)] = [
${rules}
    ]
    public static let registerThresholds: (Double, Double) = (${G.feel.register.thresholds.map(num).join(', ')})
    public static let registerMidi: (Int, Int, Int) = (${G.feel.register['base-midi'].join(', ')})
    public static let accentWarm: (L: Double, C: Double, H: Double) = (${G.accent.warm.map(num).join(', ')})
    public static let accentCool: (L: Double, C: Double, H: Double) = (${G.accent.cool.map(num).join(', ')})
    public static let accentFlipWithin: Double = ${num(G.accent['flip-within-deg'])}
    public static let accentMinChroma: Double = ${num(G.accent['min-C'])}
    public static let setHueGap: Double = ${num(G.set['hue-gap'])}
    public static let setBands: (Double, Double) = (${G.set.bands.map(num).join(', ')})
    public static let setDeltaE: Double = ${num(G.set['delta-e'])}
    public static let setCvdDeltaE: Double = ${num(G.set['cvd-delta-e'])}
    public static let setSlabRun: Int = ${G.set['slab-run']}
}
`);
finish('gadgets');
