import type * as React from 'react';
import type { RouteObject } from 'react-router';
import { Shell } from './Shell';
import { NotFound } from '../pages/NotFound';

/* Every page of the site, one table: the site mounts it on the browser's address (main.tsx), and the
 * feature slices mount the same table in memory at any route (slices/harness.tsx). */

const lazy = (load: () => Promise<{ default: React.ComponentType }>) => async () => ({ Component: (await load()).default });
export const routes: RouteObject[] = [
  { path: '/', lazy: lazy(() => import('../pages/Landing')), errorElement: <NotFound /> },
  {
    Component: Shell,
    errorElement: <NotFound />,
    children: [
      { path: 'overview', lazy: lazy(() => import('../pages/Home')) },
      { path: 'wip', lazy: lazy(() => import('../pages/Wip')) },
      { path: 'changelog', lazy: lazy(() => import('../pages/Changelog')) },
      { path: 'performance', lazy: lazy(() => import('../pages/Performance')) },
      { path: 'layers', lazy: lazy(() => import('../pages/Layers')) },
      { path: 'foundations', lazy: lazy(() => import('../pages/foundations/Principles')) },
      { path: 'foundations/color', lazy: lazy(() => import('../pages/foundations/Color')) },
      { path: 'foundations/typography', lazy: lazy(() => import('../pages/foundations/Typography')) },
      { path: 'foundations/radius', lazy: lazy(() => import('../pages/foundations/Radius')) },
      { path: 'foundations/spacing', lazy: lazy(() => import('../pages/foundations/Spacing')) },
      { path: 'foundations/sizing', lazy: lazy(() => import('../pages/foundations/Sizing')) },
      { path: 'foundations/elevation', lazy: lazy(() => import('../pages/foundations/Elevation')) },
      { path: 'foundations/materials', lazy: lazy(() => import('../pages/foundations/Materials')) },
      { path: 'foundations/sound', lazy: lazy(() => import('../pages/foundations/Sound')) },
      { path: 'foundations/motion', lazy: lazy(() => import('../pages/foundations/Motion')) },
      { path: 'foundations/transitions', lazy: lazy(() => import('../pages/foundations/Transitions')) },
      { path: 'components/button', lazy: lazy(() => import('../pages/components/Button')) },
      { path: 'components/toolbar', lazy: lazy(() => import('../pages/components/Toolbar')) },
      { path: 'components/command-palette', lazy: lazy(() => import('../pages/components/CommandPalette')) },
      { path: 'components/tooltip', lazy: lazy(() => import('../pages/components/Tooltip')) },
      { path: 'components/menu', lazy: lazy(() => import('../pages/components/Menu')) },
      { path: 'components/toast', lazy: lazy(() => import('../pages/components/Toast')) },
      { path: 'components/led', lazy: lazy(() => import('../pages/components/Led')) },
      { path: 'components/dot-display', lazy: lazy(() => import('../pages/components/DotDisplay')) },
      { path: 'components/status', lazy: lazy(() => import('../pages/components/Status')) },
      { path: 'components/kbd', lazy: lazy(() => import('../pages/components/Kbd')) },
      { path: 'components/switcher', lazy: lazy(() => import('../pages/components/Switcher')) },
      { path: 'components/fan', lazy: lazy(() => import('../pages/components/Fan')) },
      { path: 'components/swatch', lazy: lazy(() => import('../pages/components/Swatch')) },
      { path: 'components/row', lazy: lazy(() => import('../pages/components/Row')) },
      { path: 'components/checkbox', lazy: lazy(() => import('../pages/components/Checkbox')) },
      { path: 'components/radio', lazy: lazy(() => import('../pages/components/Radio')) },
      { path: 'components/textarea', lazy: lazy(() => import('../pages/components/Textarea')) },
      { path: 'components/enum-cue', lazy: lazy(() => import('../pages/components/EnumCue')) },
      { path: 'components/rename-editor', lazy: lazy(() => import('../pages/components/RenameEditor')) },
      { path: 'components/popover', lazy: lazy(() => import('../pages/components/Popover')) },
      { path: 'components/alert-dialog', lazy: lazy(() => import('../pages/components/AlertDialog')) },
      { path: 'components/progress', lazy: lazy(() => import('../pages/components/Progress')) },
      { path: 'components/spinner', lazy: lazy(() => import('../pages/components/Spinner')) },
      { path: 'components/number-field', lazy: lazy(() => import('../pages/components/NumberField')) },
      { path: 'components/toggle', lazy: lazy(() => import('../pages/components/Toggle')) },
      { path: 'components/accordion', lazy: lazy(() => import('../pages/components/Accordion')) },
      { path: 'components/meter', lazy: lazy(() => import('../pages/components/Meter')) },
      { path: 'components/sheet', lazy: lazy(() => import('../pages/components/Sheet')) },
      { path: 'components/scroll-area', lazy: lazy(() => import('../pages/components/ScrollArea')) },
      { path: 'components/checkbox-group', lazy: lazy(() => import('../pages/components/CheckboxGroup')) },
      { path: 'components/combobox', lazy: lazy(() => import('../pages/components/Combobox')) },
      { path: 'components/form-field', lazy: lazy(() => import('../pages/components/FormField')) },
      { path: 'components/skeleton', lazy: lazy(() => import('../pages/components/Skeleton')) },
      { path: 'components/link', lazy: lazy(() => import('../pages/components/Link')) },
      { path: 'components/button-group', lazy: lazy(() => import('../pages/components/ButtonGroup')) },
      { path: 'components/breadcrumbs', lazy: lazy(() => import('../pages/components/Breadcrumbs')) },
      { path: 'components/pagination', lazy: lazy(() => import('../pages/components/Pagination')) },
      { path: 'components/menubar', lazy: lazy(() => import('../pages/components/Menubar')) },
      { path: 'components/navigation-menu', lazy: lazy(() => import('../pages/components/NavigationMenu')) },
      { path: 'components/preview-card', lazy: lazy(() => import('../pages/components/PreviewCard')) },
      { path: 'components/calendar', lazy: lazy(() => import('../pages/components/Calendar')) },
      { path: 'components/avatar', lazy: lazy(() => import('../pages/components/Avatar')) },
      { path: 'components/card', lazy: lazy(() => import('../pages/components/Card')) },
      { path: 'components/attachment', lazy: lazy(() => import('../pages/components/Attachment')) },
      { path: 'blocks/studio-week', lazy: lazy(() => import('../pages/blocks/StudioWeek')) },
      { path: 'blocks/ai-composer', lazy: lazy(() => import('../pages/blocks/AiComposer')) },
      { path: 'blocks/share-panel', lazy: lazy(() => import('../pages/blocks/SharePanel')) },
      { path: 'blocks/availability-picker', lazy: lazy(() => import('../pages/blocks/AvailabilityPicker')) },
      { path: 'blocks/task-inbox', lazy: lazy(() => import('../pages/blocks/TaskInbox')) },
      { path: 'blocks/settings', lazy: lazy(() => import('../pages/blocks/Settings')) },
      { path: 'components/table', lazy: lazy(() => import('../pages/components/Table')) },
      { path: 'components/empty-state', lazy: lazy(() => import('../pages/components/EmptyState')) },
      { path: 'components/split-pane', lazy: lazy(() => import('../pages/components/SplitPane')) },
      { path: 'components/sidebar', lazy: lazy(() => import('../pages/components/Sidebar')) },
      { path: 'components/drop-zone', lazy: lazy(() => import('../pages/components/DropZone')) },
      { path: 'components/slider', lazy: lazy(() => import('../pages/components/Slider')) },
      { path: 'components/icon-button', lazy: lazy(() => import('../pages/components/IconButton')) },
      { path: 'components/field', lazy: lazy(() => import('../pages/components/Field')) },
      { path: 'components/dialog', lazy: lazy(() => import('../pages/components/Dialog')) },
      { path: 'components/link-card', lazy: lazy(() => import('../pages/components/LinkCard')) },
      { path: 'components/weather', lazy: lazy(() => import('../pages/components/Weather')) },
      { path: 'components/day', lazy: lazy(() => import('../pages/components/Day')) },
      { path: 'components/size-readout', lazy: lazy(() => import('../pages/components/SizeReadout')) },
      { path: 'components/tool-strip', lazy: lazy(() => import('../pages/components/ToolStrip')) },
      { path: 'components/past-banner', lazy: lazy(() => import('../pages/components/PastBanner')) },
      { path: 'components/memory-scrubber', lazy: lazy(() => import('../pages/components/MemoryScrubber')) },
      { path: 'components/lens-bar', lazy: lazy(() => import('../pages/components/LensBar')) },
      { path: 'components/region', lazy: lazy(() => import('../pages/components/Region')) },
      { path: 'components/provenance-tooltip', lazy: lazy(() => import('../pages/components/ProvenanceTooltip')) },
      { path: 'components/hover-engraving', lazy: lazy(() => import('../pages/components/HoverEngraving')) },
      { path: 'components/suggestion-chip', lazy: lazy(() => import('../pages/components/SuggestionChip')) },
      { path: 'components/colour-cue', lazy: lazy(() => import('../pages/components/ColourCue')) },
      { path: 'components/date-cue', lazy: lazy(() => import('../pages/components/DateCue')) },
      { path: 'components/numeric-cue', lazy: lazy(() => import('../pages/components/NumericCue')) },
      { path: 'components/tag-cue', lazy: lazy(() => import('../pages/components/TagCue')) },
      { path: 'components/cue', lazy: lazy(() => import('../pages/components/CueFamily')) },
      { path: 'components/selection-frame', lazy: lazy(() => import('../pages/components/SelectionFrame')) },
      { path: 'components/snap-guides', lazy: lazy(() => import('../pages/components/SnapGuides')) },
      { path: 'components/lasso', lazy: lazy(() => import('../pages/components/Lasso')) },
      { path: 'components/block-silhouette', lazy: lazy(() => import('../pages/components/BlockSilhouette')) },
      { path: 'components/code-card', lazy: lazy(() => import('../pages/components/CodeCard')) },
      { path: 'components/switch', lazy: lazy(() => import('../pages/components/Switch')) },
      { path: 'components/settings', lazy: lazy(() => import('../pages/components/Settings')) },
      { path: 'components/brush-cursor', lazy: lazy(() => import('../pages/components/BrushCursor')) },
      { path: 'components/draw-tools', lazy: lazy(() => import('../pages/components/DrawTools')) },
      { path: 'components/connector', lazy: lazy(() => import('../pages/components/Connector')) },
      { path: 'components/perfect-preview', lazy: lazy(() => import('../pages/components/PerfectPreview')) },
      { path: 'components/line-handles', lazy: lazy(() => import('../pages/components/LineHandles')) },
      { path: 'components/folder', lazy: lazy(() => import('../pages/components/Folder')) },
      { path: 'components/select', lazy: lazy(() => import('../pages/components/Select')) },
      { path: 'components/tabs', lazy: lazy(() => import('../pages/components/Tabs')) },
      { path: 'icons', lazy: lazy(() => import('../pages/Icons')) },
      { path: 'icons/life', lazy: lazy(() => import('../pages/IconsLife')) },
      { path: '*', Component: NotFound },
    ],
  },
];
