// Generated by scripts/build-gadgets.mjs from tokens/tokens.json (gadgets). Do not edit.
// The visual foundations of gadgets; the acoustic recipes are the sound foundation (same keys).
export const GADGETS = {
  "canvas": {
    "size": 400,
    "body": [
      40,
      36,
      320,
      320
    ],
    "radius": 76,
    "lamp": [
      313,
      78
    ]
  },
  "light": {
    "azimuth": 225,
    "elevation": 62,
    "color": {
      "bone": "#FFFFFF",
      "graphite": "#F2F3F6"
    },
    "glossElevation": 52,
    "litGain": 1.01,
    "shadowColor": "#2B2723"
  },
  "materials": {
    "clay": {
      "L": [
        0.55,
        0.88
      ],
      "CCap": 0.1,
      "bevel": 6,
      "surfaceScale": 5,
      "diffuse": 1.12,
      "gloss": [
        0,
        0
      ],
      "grain": [
        1.1,
        0.025
      ],
      "flecks": 0.5,
      "translucency": 0,
      "shadow": {
        "cast": [
          16,
          6,
          18,
          0.24
        ],
        "contact": [
          3,
          1,
          4,
          0.14
        ]
      },
      "sample": 80
    },
    "ceramic": {
      "L": [
        0.8,
        0.92
      ],
      "CCap": 0.12,
      "bevel": 5,
      "surfaceScale": 4,
      "diffuse": 1.1,
      "gloss": [
        40,
        0.35
      ],
      "grain": [
        0.6,
        0.008
      ],
      "flecks": 0,
      "translucency": 0.05,
      "shadow": {
        "cast": [
          14,
          6,
          16,
          0.22
        ],
        "contact": [
          3,
          1,
          4,
          0.14
        ]
      },
      "sample": 330
    },
    "resin": {
      "L": [
        0.7,
        0.9
      ],
      "CCap": 0.2,
      "bevel": 7,
      "surfaceScale": 5,
      "diffuse": 1.08,
      "gloss": [
        24,
        0.25
      ],
      "grain": [
        0.9,
        0.012
      ],
      "flecks": 0.3,
      "translucency": 0.6,
      "shadow": {
        "cast": [
          14,
          6,
          16,
          0.2
        ],
        "contact": [
          3,
          1,
          4,
          0.12
        ]
      },
      "sample": 55
    },
    "stone": {
      "L": [
        0.45,
        0.75
      ],
      "CCap": 0.05,
      "bevel": 8,
      "surfaceScale": 6,
      "diffuse": 1.14,
      "gloss": [
        6,
        0.08
      ],
      "grain": [
        1.6,
        0.04
      ],
      "flecks": 1.2,
      "translucency": 0,
      "shadow": {
        "cast": [
          18,
          6,
          20,
          0.28
        ],
        "contact": [
          3,
          1,
          4,
          0.16
        ]
      },
      "sample": 195
    },
    "glass": {
      "L": [
        0.22,
        0.45
      ],
      "faceL": [
        0.75,
        0.88
      ],
      "CCap": 0.06,
      "faceCCap": 0.1,
      "bevel": 3,
      "surfaceScale": 3,
      "diffuse": 1,
      "gloss": [
        80,
        0.6
      ],
      "grain": [
        0,
        0
      ],
      "flecks": 0,
      "translucency": 0.8,
      "shadow": {
        "cast": [
          12,
          5,
          14,
          0.24
        ],
        "contact": [
          2,
          1,
          3,
          0.18
        ]
      },
      "sample": 260
    },
    "metal": {
      "L": [
        0.4,
        0.8
      ],
      "CCap": 0.08,
      "bevel": 4,
      "surfaceScale": 4,
      "diffuse": 1.05,
      "gloss": [
        60,
        0.5
      ],
      "grain": [
        2.4,
        0.02
      ],
      "grainDirection": 0,
      "flecks": 0,
      "translucency": 0,
      "shadow": {
        "cast": [
          12,
          5,
          14,
          0.26
        ],
        "contact": [
          2,
          1,
          3,
          0.18
        ]
      },
      "sample": 230
    },
    "rubber": {
      "L": [
        0.22,
        0.4
      ],
      "CCap": 0.03,
      "bevel": 9,
      "surfaceScale": 6,
      "diffuse": 1.15,
      "gloss": [
        0,
        0
      ],
      "grain": [
        1.3,
        0.03
      ],
      "flecks": 0,
      "translucency": 0,
      "shadow": {
        "cast": [
          20,
          6,
          22,
          0.32
        ],
        "contact": [
          4,
          1,
          5,
          0.18
        ]
      },
      "sample": 25
    }
  },
  "partScale": {
    "bevel": 0.55,
    "shadow": 0.6
  },
  "hole": {
    "blur": 4,
    "offset": [
      3,
      6
    ],
    "alpha": 0.55,
    "lip": 1,
    "floor": {
      "drop": 0.16,
      "depthDrop": 0.2,
      "chroma": 0.7
    },
    "depths": {
      "slot": 14,
      "hole": 18,
      "tray": 10,
      "well": 6
    },
    "lipAlpha": 0.5,
    "trayRadius": 20
  },
  "jack": {
    "hole": 0.44,
    "knurls": 12,
    "knurl": [
      0.66,
      0.88
    ],
    "metal": [
      0.78,
      0.012,
      230
    ],
    "floor": 0.24,
    "alone": 260,
    "knurlWidth": 0.07,
    "knurlAlpha": 0.22,
    "glow": 0.8
  },
  "plug": {
    "side": 0.15,
    "skirt": 0.12,
    "knurls": 6,
    "knurl": [
      0.62,
      0.86
    ],
    "knurlAlpha": 0.2,
    "boss": 0.4,
    "stub": [
      0.9,
      0.5
    ],
    "shadow": [
      0.26,
      0.3,
      0.5,
      0.42
    ],
    "alone": 180,
    "face": 0.94,
    "centreY": 196,
    "stubFrom": 0.7,
    "stubL": 0.34,
    "stubC": 0.01,
    "faceClay": 0.9,
    "faceC": 0.012,
    "bossDrop": 0.04,
    "knurlWidth": 0.1
  },
  "cable": {
    "width": 13.5,
    "sag": [
      0.18,
      24,
      90
    ],
    "handle": 0.3,
    "rubber": [
      0.3,
      0.012
    ],
    "shade": [
      0.07,
      0.5,
      0.1,
      0.13
    ],
    "sheen": [
      0.2,
      -0.16,
      -0.2,
      0.22
    ],
    "shadow": [
      0.35,
      0.25,
      0.45,
      0.4
    ],
    "spring": "hinge",
    "seatReach": 30
  },
  "beeper": {
    "alone": 240,
    "radius": 0.3,
    "slots": 5,
    "slot": [
      0.075,
      0.6
    ],
    "span": 0.72,
    "brass": [
      0.5,
      0.075,
      82
    ],
    "litL": 0.8,
    "lift": 0.023,
    "riseMs": 12,
    "fallMs": 70,
    "sampleMs": 10
  },
  "cap": {
    "radius": 13,
    "side": 4,
    "sideDrop": 0.1,
    "ribs": 3,
    "pitch": 8,
    "span": 0.57,
    "groove": [
      2.4,
      0.24
    ],
    "edge": [
      1.1,
      0.7,
      1.8
    ],
    "pointer": [
      0.3,
      0.78
    ],
    "press": 2.5,
    "pressShadow": 0.55,
    "pressSpring": "release",
    "ceramic": [
      0.93,
      0.008
    ],
    "alone": 200,
    "shadow": [
      0.16,
      0.1,
      0.22,
      0.36
    ],
    "pointerScale": 1.4,
    "grooveInk": [
      0.45,
      0.2,
      1.3,
      0.02,
      0.12
    ],
    "edgeInk": [
      0.1,
      0.5
    ],
    "slot": [
      18,
      20
    ]
  },
  "key": {
    "radius": 0.21,
    "skirtDrop": 0.11,
    "face": [
      0.8,
      0.21
    ],
    "faceLift": 0.062,
    "glyph": 0.46,
    "glyphEdge": 1.2,
    "glyphAlpha": [
      0.5,
      0.85
    ],
    "shadow": [
      0.1,
      0.06,
      0.12,
      0.34
    ],
    "alone": 220,
    "press": [
      6,
      1.02,
      0.96
    ]
  },
  "bezel": {
    "width": 22,
    "openingRadius": 0.2,
    "depth": 12
  },
  "glass": {
    "depth": [
      0.05,
      0.09
    ],
    "rings": [
      0.36,
      0.68
    ],
    "line": [
      1.4,
      0.24
    ],
    "cross": 0.14,
    "rim": [
      0.07,
      0.28
    ],
    "glare": [
      0.36,
      0.3,
      0.68,
      0.4,
      0.4
    ]
  },
  "backlight": {
    "glow": 0.5,
    "spread": 70,
    "slices": 14,
    "lead": [
      2.4,
      0.95
    ],
    "dot": 0.35,
    "glassLift": 0.14,
    "alpha": 0.85,
    "sliceAlpha": 0.75,
    "glassChroma": 1.4
  },
  "lamp": {
    "off": [
      "#8B8B8E",
      "#4A4A4D"
    ],
    "live": [
      "#D9FFE9",
      "#2FB673"
    ],
    "link": [
      "#D8E6FF",
      "#2457F2"
    ],
    "waiting": [
      "#FFF1CF",
      "#C98A18"
    ],
    "failed": [
      "#FFD9D2",
      "#D5392A"
    ]
  },
  "drum": {
    "pitch": 36,
    "radius": 4,
    "glyph": 0.8,
    "weight": 600,
    "shade": [
      0.36,
      0.44
    ],
    "edge": 0.34,
    "glint": [
      0.24,
      0.05,
      0.28
    ],
    "alone": 150
  },
  "drive": {
    "detentSize": 0.33,
    "detentPitch": 1.6,
    "stopPitch": [
      0.94,
      1.08
    ]
  },
  "surface": {
    "grainOctaves": 2,
    "grainSeed": 3,
    "directionalRatio": 0.01,
    "fleck": {
      "frequency": 0.62,
      "seed": 9,
      "gain": 22,
      "cut": -15.6,
      "scale": 0.45,
      "max": 0.75,
      "uniformCut": 0.985
    },
    "translucentCore": {
      "L": 0.08,
      "H": 10,
      "edgeL": -0.06,
      "scatter": [
        0.3,
        0.7
      ]
    },
    "grainLitGain": 3
  },
  "tiers": {
    "full": 96,
    "lite": 48,
    "liteBevel": 0.6
  },
  "host": {
    "bone": {
      "shadow": 1,
      "idleLamp": 0.78
    },
    "graphite": {
      "shadow": 1.35,
      "brightLDrop": 0.04,
      "brightLAbove": 0.84,
      "idleLamp": 0.86
    },
    "contrast": {
      "edge": 1,
      "translucencyMax": 0.2,
      "shadow": 1.2
    },
    "reducedTransparency": {
      "glowAlpha": 0.35
    }
  },
  "strike": {
    "travel": {
      "clay": 1,
      "ceramic": 0.5,
      "resin": 0.75,
      "stone": 0.5,
      "glass": 0.25,
      "metal": 0.25,
      "rubber": 2
    },
    "squash": {
      "rubber": 0.03,
      "clay": 0.008
    },
    "glintAbove": 0.2,
    "glintMs": 420
  },
  "feel": {
    "L": {
      "base": 0.88,
      "W": -0.56,
      "V": 0.05
    },
    "C": {
      "base": 0.015,
      "A": 0.2,
      "VMix": [
        0.6,
        0.4
      ]
    },
    "H": {
      "V": 12,
      "W": -8
    },
    "materialRules": [
      [
        "w>=0.8&v<=0.4",
        "rubber"
      ],
      [
        "w>=0.8",
        "glass"
      ],
      [
        "w>=0.5&a>=0.6",
        "metal"
      ],
      [
        "w>=0.5",
        "stone"
      ],
      [
        "a>=0.6",
        "resin"
      ],
      [
        "v>=0.7&w<=0.3",
        "ceramic"
      ],
      [
        "*",
        "clay"
      ]
    ],
    "register": {
      "thresholds": [
        0.33,
        0.66
      ],
      "baseMidi": [
        84,
        72,
        60
      ]
    },
    "scales": {
      "major": [
        0,
        2,
        4,
        7,
        9
      ],
      "minor": [
        0,
        3,
        5,
        7,
        10
      ]
    }
  },
  "jobs": {
    "tune": {
      "stations": [
        80
      ],
      "reach": "own",
      "containers": [
        "slab"
      ],
      "bodyCMax": 0.025
    },
    "command": {
      "stations": [
        95
      ],
      "reach": "own",
      "containers": [
        "slab"
      ],
      "pin": "ceramic"
    },
    "link": {
      "stations": [
        195,
        230
      ],
      "reach": "world",
      "containers": [
        "slab",
        "free"
      ]
    },
    "keep": {
      "stations": [
        140,
        300
      ],
      "reach": "own",
      "containers": [
        "slab",
        "inset"
      ]
    },
    "identify": {
      "stations": [
        260
      ],
      "reach": "others",
      "containers": [
        "inset"
      ],
      "pin": "glass"
    },
    "destroy": {
      "stations": [
        25
      ],
      "reach": "own",
      "containers": [
        "slab"
      ],
      "bodyCMax": 0.02
    },
    "take": {
      "stations": [
        55
      ],
      "reach": "world",
      "containers": [
        "inset"
      ]
    },
    "find": {
      "stations": [
        250
      ],
      "reach": "world",
      "containers": [
        "inset"
      ],
      "pin": "stone"
    },
    "make": {
      "stations": [
        330
      ],
      "reach": "own",
      "containers": [
        "slab",
        "free"
      ]
    },
    "signal": {
      "stations": [
        55,
        80
      ],
      "reach": "own",
      "containers": [
        "slab",
        "inset",
        "free"
      ]
    }
  },
  "accent": {
    "warm": [
      0.72,
      0.19,
      45
    ],
    "cool": [
      0.75,
      0.13,
      235
    ],
    "flipWithinDeg": 40,
    "minC": 0.13,
    "flipMinC": 0.04
  },
  "set": {
    "hueGap": 30,
    "bands": [
      0.78,
      0.5
    ],
    "deltaE": 0.08,
    "cvdDeltaE": 0.06,
    "slabRun": 3,
    "panelLGap": 0.06,
    "hueMinC": 0.04
  },
  "parts": {
    "slab": {
      "size": [
        320,
        320
      ],
      "materials": [
        "clay",
        "stone",
        "ceramic",
        "rubber",
        "metal",
        "resin"
      ],
      "params": {
        "cut": [
          "enum",
          "none",
          "slot",
          "hole",
          "tray",
          "well"
        ],
        "depth": [
          "number",
          0,
          24
        ],
        "radius": [
          "number",
          4,
          160
        ]
      },
      "strike": [
        "body",
        0.6
      ]
    },
    "bezel": {
      "size": [
        320,
        320
      ],
      "materials": [
        "stone",
        "metal",
        "clay"
      ],
      "params": {
        "width": [
          "number",
          16,
          32
        ],
        "face": [
          "enum",
          "glass-face",
          "cell",
          "backlight"
        ],
        "opening": [
          "enum",
          "round",
          "square"
        ]
      },
      "strike": [
        "frame",
        0.5
      ]
    },
    "glass-face": {
      "size": [
        276,
        276
      ],
      "materials": [
        "glass"
      ],
      "params": {
        "shape": [
          "enum",
          "round",
          "square"
        ]
      },
      "strike": [
        "face",
        0.5
      ],
      "round": "shape"
    },
    "backlight": {
      "size": [
        200,
        200
      ],
      "materials": [
        "lamp"
      ],
      "params": {
        "alpha": [
          "number",
          0,
          1
        ],
        "color": [
          "enum",
          "signal",
          "accent",
          "glass"
        ],
        "shape": [
          "enum",
          "glow",
          "beam",
          "dot"
        ]
      },
      "round": true
    },
    "led": {
      "size": [
        22,
        22
      ],
      "materials": [
        "lamp"
      ],
      "params": {},
      "round": true
    },
    "key": {
      "size": [
        112,
        112
      ],
      "materials": [
        "clay",
        "ceramic",
        "accent"
      ],
      "params": {
        "glyph": [
          "string"
        ]
      },
      "strike": [
        "face",
        1
      ]
    },
    "cap": {
      "size": [
        60,
        44
      ],
      "materials": [
        "clay",
        "ceramic",
        "accent"
      ],
      "params": {
        "ribs": [
          "number",
          2,
          5
        ],
        "shape": [
          "enum",
          "fader",
          "knob"
        ],
        "value": [
          "number",
          0,
          1
        ]
      },
      "strike": [
        "face",
        0.8
      ]
    },
    "jack": {
      "size": [
        68,
        68
      ],
      "materials": [
        "metal"
      ],
      "params": {
        "knurls": [
          "number",
          8,
          16
        ]
      },
      "strike": [
        "nut",
        0.7
      ],
      "round": true
    },
    "plug": {
      "size": [
        54,
        54
      ],
      "materials": [
        "clay",
        "accent"
      ],
      "params": {
        "stub": [
          "enum",
          "up",
          "left",
          "right",
          "none"
        ]
      },
      "strike": [
        "body",
        0.85
      ],
      "round": true
    },
    "cable": {
      "size": [
        0,
        0
      ],
      "materials": [
        "rubber"
      ],
      "params": {
        "sag": [
          "number",
          0,
          90
        ],
        "from": [
          "ref"
        ],
        "to": [
          "ref"
        ]
      },
      "strike": [
        "tube",
        0.2
      ]
    },
    "cell": {
      "size": [
        44,
        44
      ],
      "materials": [
        "resin"
      ],
      "params": {
        "cols": [
          "number",
          1,
          8
        ],
        "rows": [
          "number",
          1,
          8
        ],
        "gap": [
          "number",
          6,
          14
        ]
      },
      "strike": [
        "cells",
        0.5
      ]
    },
    "drum": {
      "size": [
        52,
        88
      ],
      "materials": [
        "clay",
        "ceramic",
        "accent"
      ],
      "params": {
        "digits": [
          "number",
          10,
          10
        ],
        "face": [
          "enum",
          "ceramic",
          "clay"
        ],
        "glyphs": [
          "enum",
          "digits",
          "ticks"
        ]
      },
      "strike": [
        "strip",
        0.35
      ]
    },
    "needle": {
      "size": [
        96,
        8
      ],
      "materials": [
        "metal"
      ],
      "params": {
        "arc": [
          "number",
          90,
          150
        ],
        "ticks": [
          "number",
          5,
          21
        ],
        "threshold": [
          "number",
          0,
          1
        ]
      }
    },
    "lid": {
      "size": [
        240,
        160
      ],
      "materials": [
        "rubber",
        "clay"
      ],
      "params": {
        "hinge": [
          "enum",
          "back",
          "left"
        ],
        "armed": [
          "boolean"
        ]
      },
      "strike": [
        "lid",
        0.9
      ]
    },
    "pull": {
      "size": [
        96,
        14
      ],
      "materials": [
        "metal",
        "clay"
      ],
      "params": {
        "style": [
          "enum",
          "bar",
          "recess"
        ]
      },
      "strike": [
        "pull",
        0.5
      ]
    },
    "lens": {
      "size": [
        184,
        184
      ],
      "materials": [
        "glass",
        "accent"
      ],
      "params": {
        "ticks": [
          "number",
          12,
          36
        ],
        "iris": [
          "number",
          0,
          1
        ]
      },
      "strike": [
        "ring",
        0.3
      ]
    },
    "nib": {
      "size": [
        70,
        20
      ],
      "materials": [
        "metal"
      ],
      "params": {
        "angle": [
          "number",
          -30,
          30
        ]
      },
      "strike": [
        "nib",
        0.3
      ]
    },
    "beeper": {
      "size": [
        44,
        24
      ],
      "materials": [
        "metal",
        "clay"
      ],
      "params": {
        "slots": [
          "number",
          3,
          7
        ]
      }
    },
    "label": {
      "size": [
        80,
        16
      ],
      "materials": [
        "clay"
      ],
      "params": {
        "text": [
          "string"
        ]
      }
    },
    "glyph": {
      "size": [
        24,
        24
      ],
      "materials": [
        "clay"
      ],
      "params": {
        "name": [
          "string"
        ]
      }
    }
  },
  "mechanisms": {
    "press": {
      "mode": "momentary",
      "slots": {
        "keys": {
          "parts": [
            "key",
            "cap"
          ],
          "many": true
        },
        "lamp": {
          "parts": [
            "led"
          ]
        }
      }
    },
    "slide": {
      "mode": "held",
      "drive": [
        "number",
        "count"
      ],
      "detents": true,
      "slots": {
        "caps": {
          "parts": [
            "cap"
          ],
          "many": true
        },
        "slot": {
          "parts": [
            "slab"
          ]
        },
        "lamp": {
          "parts": [
            "led"
          ]
        }
      }
    },
    "seat": {
      "mode": "momentary",
      "slots": {
        "plug": {
          "parts": [
            "plug"
          ]
        },
        "socket": {
          "parts": [
            "jack"
          ]
        },
        "lamp": {
          "parts": [
            "led"
          ]
        },
        "beeper": {
          "parts": [
            "beeper"
          ],
          "optional": true
        }
      }
    },
    "turn": {
      "mode": "held",
      "drive": [
        "number",
        "count"
      ],
      "detents": true,
      "slots": {
        "ring": {
          "parts": [
            "lens",
            "cap"
          ]
        },
        "lamp": {
          "parts": [
            "led"
          ]
        }
      }
    },
    "flip": {
      "mode": "held",
      "drive": [
        "boolean",
        "state"
      ],
      "slots": {
        "lid": {
          "parts": [
            "lid",
            "cap"
          ]
        },
        "lamp": {
          "parts": [
            "led"
          ]
        }
      }
    },
    "sweep": {
      "mode": "momentary",
      "slots": {
        "beam": {
          "parts": [
            "backlight"
          ]
        },
        "face": {
          "parts": [
            "glass-face"
          ]
        },
        "blips": {
          "parts": [
            "backlight"
          ],
          "many": true,
          "optional": true
        },
        "lamp": {
          "parts": [
            "led"
          ]
        }
      }
    },
    "roll": {
      "mode": "held",
      "drive": [
        "count"
      ],
      "detents": true,
      "slots": {
        "drums": {
          "parts": [
            "drum"
          ],
          "many": true
        },
        "window": {
          "parts": [
            "slab"
          ]
        },
        "lamp": {
          "parts": [
            "led"
          ]
        }
      }
    },
    "swing": {
      "mode": "held",
      "drive": [
        "number"
      ],
      "slots": {
        "needle": {
          "parts": [
            "needle"
          ]
        },
        "face": {
          "parts": [
            "glass-face",
            "bezel"
          ]
        },
        "lamp": {
          "parts": [
            "led"
          ]
        },
        "beeper": {
          "parts": [
            "beeper"
          ],
          "optional": true
        }
      }
    },
    "glow": {
      "mode": "held",
      "drive": [
        "number",
        "count"
      ],
      "slots": {
        "light": {
          "parts": [
            "backlight"
          ]
        },
        "cells": {
          "parts": [
            "cell"
          ],
          "many": true
        },
        "lamp": {
          "parts": [
            "led"
          ]
        }
      }
    },
    "slide-out": {
      "mode": "momentary",
      "slots": {
        "tray": {
          "parts": [
            "slab"
          ]
        },
        "pull": {
          "parts": [
            "pull"
          ]
        },
        "lamp": {
          "parts": [
            "led"
          ]
        }
      }
    },
    "dip": {
      "mode": "momentary",
      "slots": {
        "nib": {
          "parts": [
            "nib"
          ]
        },
        "well": {
          "parts": [
            "slab"
          ]
        },
        "lamp": {
          "parts": [
            "led"
          ]
        }
      }
    }
  },
  "spec": {
    "parts": [
      2,
      24
    ],
    "states": 8,
    "ports": 4,
    "nameMax": 32,
    "pose": {
      "x": 100,
      "y": 100,
      "r": 180,
      "s": [
        0.5,
        1.5
      ]
    },
    "detents": [
      2,
      60
    ],
    "rigGrid": [
      4,
      3
    ],
    "rigGadgets": [
      2,
      8
    ],
    "cables": [
      1,
      12
    ],
    "fanOut": 3
  }
} as const;
export type GadgetMaterial = 'clay' | 'ceramic' | 'resin' | 'stone' | 'glass' | 'metal' | 'rubber';
export const GADGET_MATERIALS: readonly GadgetMaterial[] = ['clay', 'ceramic', 'resin', 'stone', 'glass', 'metal', 'rubber'];
