// Generated by scripts/build-gadgets.mjs from packages/metalui/gadgets/src/mechanisms. Do not edit.
// How gadgets move when they act: tracks (poses as numbers, easings as cubic-bezier points), cues,
// held poses and what survives reduced motion. MetalMechanisms.generated.swift carries the same.
export const MECHANISMS = {
  "seat": {
    "name": "seat",
    "mode": "momentary",
    "duration": 910,
    "caption": "The plug lifts, its shadow opens, and it seats again with a click.",
    "stages": [
      "Lift",
      "Hang",
      "Seat"
    ],
    "spring": "part",
    "slots": {
      "plug": "actor",
      "socket": "trim",
      "lamp": "lamp",
      "beeper": "trim?"
    },
    "tracks": [
      {
        "part": "plug",
        "origin": "centre",
        "frames": [
          {
            "at": 0,
            "pose": {
              "x": 0,
              "y": 0,
              "r": 0,
              "sx": 1,
              "sy": 1
            },
            "opacity": null,
            "ease": [
              0.55,
              0,
              0.85,
              0.45
            ]
          },
          {
            "at": 140,
            "pose": {
              "x": 0,
              "y": -14,
              "r": 0,
              "sx": 1.04,
              "sy": 1.04
            },
            "opacity": null,
            "ease": [
              0.4,
              0,
              0.2,
              1
            ]
          },
          {
            "at": 300,
            "pose": {
              "x": 0,
              "y": -14,
              "r": 0,
              "sx": 1.04,
              "sy": 1.04
            },
            "opacity": null,
            "ease": [
              0.16,
              0.75,
              0.3,
              0.95
            ]
          },
          {
            "at": 605,
            "pose": {
              "x": 0,
              "y": 1.2189,
              "r": 0,
              "sx": 0.9965,
              "sy": 0.9965
            },
            "opacity": null,
            "ease": [
              0.37,
              0,
              0.63,
              1
            ]
          },
          {
            "at": 910,
            "pose": {
              "x": 0,
              "y": 0,
              "r": 0,
              "sx": 1,
              "sy": 1
            },
            "opacity": null,
            "ease": [
              0,
              0,
              1,
              1
            ]
          }
        ]
      },
      {
        "part": "plug.shadow",
        "origin": "centre",
        "frames": [
          {
            "at": 0,
            "pose": {
              "x": 0,
              "y": 0,
              "r": 0,
              "sx": 1,
              "sy": 1
            },
            "opacity": 1,
            "ease": [
              0,
              0,
              1,
              1
            ]
          },
          {
            "at": 140,
            "pose": {
              "x": 6,
              "y": 10,
              "r": 0,
              "sx": 1.25,
              "sy": 1.25
            },
            "opacity": 0.55,
            "ease": [
              0,
              0,
              1,
              1
            ]
          },
          {
            "at": 300,
            "pose": {
              "x": 6,
              "y": 10,
              "r": 0,
              "sx": 1.25,
              "sy": 1.25
            },
            "opacity": 0.55,
            "ease": [
              0,
              0,
              1,
              1
            ]
          },
          {
            "at": 517,
            "pose": {
              "x": 0,
              "y": 0,
              "r": 0,
              "sx": 1,
              "sy": 1
            },
            "opacity": 1,
            "ease": [
              0,
              0,
              1,
              1
            ]
          },
          {
            "at": 910,
            "pose": {
              "x": 0,
              "y": 0,
              "r": 0,
              "sx": 1,
              "sy": 1
            },
            "opacity": 1,
            "ease": [
              0,
              0,
              1,
              1
            ]
          }
        ]
      }
    ],
    "cues": [
      {
        "at": 120,
        "kind": "strike",
        "slot": "plug",
        "level": 0.2,
        "pitch": 0.8
      },
      {
        "at": 517,
        "kind": "strike",
        "slot": "plug",
        "level": 0.85,
        "pitch": 1
      },
      {
        "at": 517,
        "kind": "lamp",
        "gesture": "flicker"
      },
      {
        "at": 537,
        "kind": "beep"
      }
    ],
    "states": {
      "half": {
        "hold": "plug",
        "pose": {
          "y": -7
        }
      },
      "out": {
        "hold": "plug",
        "pose": {
          "x": -22,
          "y": -46,
          "r": -14
        }
      }
    },
    "reduced": [
      "lamp",
      "sound"
    ],
    "held": null
  },
  "slide": {
    "name": "slide",
    "mode": "held",
    "duration": 0,
    "caption": "Caps travel along their slots to a new mix, one after another; they scrape as they go, tick past each detent, and knock if they reach the end.",
    "stages": [
      "Push",
      "Travel",
      "Settle"
    ],
    "spring": "part",
    "slots": {
      "caps": "actor",
      "slot": "cut",
      "lamp": "lamp"
    },
    "tracks": [],
    "cues": [
      {
        "kind": "friction",
        "slot": "caps",
        "level": 0.5
      },
      {
        "kind": "detent",
        "slot": "caps",
        "level": 0.25
      },
      {
        "kind": "stop",
        "slot": "caps",
        "level": 0.8
      }
    ],
    "states": {},
    "reduced": [
      "lamp",
      "sound"
    ],
    "held": {
      "drive": "number",
      "slot": "caps",
      "from": {
        "y": 92
      },
      "to": {
        "y": -92
      },
      "detents": 8,
      "stagger": 40,
      "wall": 0.25,
      "impactFull": 2.5,
      "scrapeFull": 3,
      "tickMin": 0.15,
      "tickGap": 40,
      "step": 240
    }
  }
} as const;
