// Generated by scripts/build-tokens.mjs from tokens/tokens.json. Do not edit.
// Values are the approved Soft Hardware object sheet (Rev B); the CSS twin is components/tokens.css.

/// Every value one colorway supplies. Mirrors the `--mu-*` colorway custom properties.
public struct MetalColorwayTokens: Sendable {
    public let sHi: MetalRGBA
    public let s: MetalRGBA
    public let sLo: MetalRGBA
    public let wellTop: MetalRGBA
    public let wellBot: MetalRGBA
    public let ink: MetalRGBA
    public let ink2: MetalRGBA
    public let ink3: MetalRGBA
    public let icon: MetalRGBA
    public let engrave: MetalRGBA
    public let lip: MetalRGBA
    public let rule: MetalRGBA
    public let ruleLip: MetalRGBA
    public let thumbHi: MetalRGBA
    public let thumbLo: MetalRGBA
    public let frost: MetalRGBA
    public let frostStrong: MetalRGBA
    public let frostOpaque: MetalRGBA
    public let contrastEdge: MetalRGBA
    public let presenceDot: MetalRGBA
    public let raise: [MetalShadow]
    public let raiseSm: [MetalShadow]
    public let well: [MetalShadow]
    public let capBg: MetalGradient
    public let capSh: [MetalShadow]
    public let btnBg: MetalGradient
    public let btnSh: [MetalShadow]
    public let pressedBg: MetalGradient
    public let pressedSh: [MetalShadow]
    public let duoK: Double
    public let tintEmber: MetalRGBA
    public let tintBlush: MetalRGBA
    public let tintTide: MetalRGBA
    public let tintSpark: MetalRGBA
    public let tintGraphite: MetalRGBA
    public let tintDusk: MetalRGBA
    public let tintIris: MetalRGBA
}

/// A signal cap (primary, destructive) that looks the same in both colorways.
public struct MetalCapTokens: Sendable {
    public let bg: MetalGradient
    public let sh: [MetalShadow]
    public let pressedBg: MetalGradient
    public let pressedSh: [MetalShadow]
    public let ink: MetalRGBA
}

public enum MetalTokens {
    public static let bone = MetalColorwayTokens(
        sHi: MetalRGBA(252, 251, 249, 1.0),
        s: MetalRGBA(246, 245, 242, 1.0),
        sLo: MetalRGBA(240, 239, 235, 1.0),
        wellTop: MetalRGBA(230, 229, 225, 1.0),
        wellBot: MetalRGBA(236, 235, 231, 1.0),
        ink: MetalRGBA(27, 27, 29, 1.0),
        ink2: MetalRGBA(92, 92, 96, 1.0),
        ink3: MetalRGBA(130, 130, 133, 1.0),
        icon: MetalRGBA(58, 58, 61, 1.0),
        engrave: MetalRGBA(40, 38, 32, 0.56),
        lip: MetalRGBA(255, 255, 255, 0.55),
        rule: MetalRGBA(0, 0, 0, 0.06),
        ruleLip: MetalRGBA(255, 255, 255, 0.5),
        thumbHi: MetalRGBA(255, 255, 255, 1.0),
        thumbLo: MetalRGBA(247, 246, 243, 1.0),
        frost: MetalRGBA(250, 249, 246, 0.68),
        frostStrong: MetalRGBA(251, 250, 248, 0.8),
        frostOpaque: MetalRGBA(244, 243, 240, 1.0),
        contrastEdge: MetalRGBA(0, 0, 0, 0.45),
        presenceDot: MetalRGBA(40, 38, 32, 0.18),
        raise: [
            MetalShadow(inset: true, x: 0.0, y: 0.0, blur: 6.0, spread: 2.0, color: MetalRGBA(255, 255, 255, 0.75)),
            MetalShadow(inset: true, x: 2.0, y: 3.0, blur: 3.0, spread: -1.0, color: MetalRGBA(255, 255, 255, 0.95)),
            MetalShadow(inset: true, x: -1.0, y: -3.0, blur: 5.0, spread: -2.0, color: MetalRGBA(110, 100, 80, 0.07)),
            MetalShadow(inset: false, x: 0.0, y: 0.0, blur: 0.0, spread: 0.5, color: MetalRGBA(24, 22, 16, 0.045)),
            MetalShadow(inset: false, x: 0.0, y: 1.0, blur: 2.0, spread: 0.0, color: MetalRGBA(24, 22, 16, 0.05)),
            MetalShadow(inset: false, x: 0.0, y: 8.0, blur: 18.0, spread: -6.0, color: MetalRGBA(24, 22, 16, 0.08)),
            MetalShadow(inset: false, x: 0.0, y: 26.0, blur: 50.0, spread: -16.0, color: MetalRGBA(24, 22, 16, 0.13)),
            MetalShadow(inset: false, x: 0.0, y: 52.0, blur: 96.0, spread: -36.0, color: MetalRGBA(24, 22, 16, 0.13)),
        ],
        raiseSm: [
            MetalShadow(inset: true, x: 0.0, y: 0.0, blur: 4.0, spread: 1.0, color: MetalRGBA(255, 255, 255, 0.85)),
            MetalShadow(inset: true, x: 1.0, y: 2.0, blur: 2.0, spread: -1.0, color: MetalRGBA(255, 255, 255, 1.0)),
            MetalShadow(inset: false, x: 0.0, y: 0.0, blur: 0.0, spread: 0.5, color: MetalRGBA(24, 22, 16, 0.05)),
            MetalShadow(inset: false, x: 0.0, y: 1.0, blur: 2.0, spread: 0.0, color: MetalRGBA(24, 22, 16, 0.07)),
            MetalShadow(inset: false, x: 0.0, y: 5.0, blur: 12.0, spread: -4.0, color: MetalRGBA(24, 22, 16, 0.09)),
        ],
        well: [
            MetalShadow(inset: true, x: 0.0, y: 2.0, blur: 6.0, spread: -1.0, color: MetalRGBA(60, 55, 40, 0.1)),
            MetalShadow(inset: true, x: 0.0, y: 0.0, blur: 0.0, spread: 0.5, color: MetalRGBA(0, 0, 0, 0.03)),
            MetalShadow(inset: true, x: 0.0, y: -2.0, blur: 4.0, spread: -2.0, color: MetalRGBA(255, 255, 255, 0.95)),
        ],
        capBg: MetalGradient(angle: 180.0, stops: [.init(MetalRGBA(255, 255, 255, 1.0), 0.0), .init(MetalRGBA(245, 244, 241, 1.0), 1.0)]),
        capSh: [
            MetalShadow(inset: true, x: 0.0, y: 0.0, blur: 3.0, spread: 1.0, color: MetalRGBA(255, 255, 255, 0.9)),
            MetalShadow(inset: false, x: 0.0, y: 0.0, blur: 0.0, spread: 0.5, color: MetalRGBA(0, 0, 0, 0.07)),
            MetalShadow(inset: false, x: 0.0, y: 1.0, blur: 2.0, spread: 0.0, color: MetalRGBA(0, 0, 0, 0.07)),
        ],
        btnBg: MetalGradient(angle: 180.0, stops: [.init(MetalRGBA(255, 255, 255, 1.0), 0.0), .init(MetalRGBA(244, 243, 240, 1.0), 1.0)]),
        btnSh: [
            MetalShadow(inset: true, x: 0.0, y: 0.0, blur: 4.0, spread: 1.0, color: MetalRGBA(255, 255, 255, 0.9)),
            MetalShadow(inset: true, x: 1.0, y: 2.0, blur: 2.0, spread: -1.0, color: MetalRGBA(255, 255, 255, 1.0)),
            MetalShadow(inset: false, x: 0.0, y: 0.0, blur: 0.0, spread: 0.5, color: MetalRGBA(0, 0, 0, 0.06)),
            MetalShadow(inset: false, x: 0.0, y: 1.0, blur: 2.0, spread: 0.0, color: MetalRGBA(0, 0, 0, 0.06)),
            MetalShadow(inset: false, x: 0.0, y: 4.0, blur: 9.0, spread: -3.0, color: MetalRGBA(0, 0, 0, 0.08)),
        ],
        pressedBg: MetalGradient(angle: 180.0, stops: [.init(MetalRGBA(233, 232, 228, 1.0), 0.0), .init(MetalRGBA(239, 238, 234, 1.0), 1.0)]),
        pressedSh: [
            MetalShadow(inset: true, x: 0.0, y: 2.0, blur: 5.0, spread: -1.0, color: MetalRGBA(60, 55, 40, 0.14)),
            MetalShadow(inset: true, x: 0.0, y: 0.0, blur: 0.0, spread: 0.5, color: MetalRGBA(0, 0, 0, 0.035)),
            MetalShadow(inset: true, x: 0.0, y: -2.0, blur: 3.0, spread: -2.0, color: MetalRGBA(255, 255, 255, 0.9)),
        ],
        duoK: 1.0,
        tintEmber: MetalRGBA(208, 86, 14, 1.0),
        tintBlush: MetalRGBA(213, 68, 135, 1.0),
        tintTide: MetalRGBA(16, 138, 139, 1.0),
        tintSpark: MetalRGBA(182, 83, 197, 1.0),
        tintGraphite: MetalRGBA(92, 92, 96, 1.0),
        tintDusk: MetalRGBA(15, 125, 220, 1.0),
        tintIris: MetalRGBA(115, 106, 236, 1.0)
    )

    public static let graphite = MetalColorwayTokens(
        sHi: MetalRGBA(44, 44, 47, 1.0),
        s: MetalRGBA(37, 37, 39, 1.0),
        sLo: MetalRGBA(32, 32, 34, 1.0),
        wellTop: MetalRGBA(20, 20, 21, 1.0),
        wellBot: MetalRGBA(24, 24, 26, 1.0),
        ink: MetalRGBA(242, 242, 240, 1.0),
        ink2: MetalRGBA(166, 166, 169, 1.0),
        ink3: MetalRGBA(119, 119, 123, 1.0),
        icon: MetalRGBA(214, 214, 216, 1.0),
        engrave: MetalRGBA(255, 255, 255, 0.38),
        lip: MetalRGBA(0, 0, 0, 0.35),
        rule: MetalRGBA(0, 0, 0, 0.45),
        ruleLip: MetalRGBA(255, 255, 255, 0.035),
        thumbHi: MetalRGBA(58, 58, 61, 1.0),
        thumbLo: MetalRGBA(46, 46, 49, 1.0),
        frost: MetalRGBA(36, 36, 39, 0.66),
        frostStrong: MetalRGBA(34, 34, 37, 0.78),
        frostOpaque: MetalRGBA(37, 37, 40, 1.0),
        contrastEdge: MetalRGBA(255, 255, 255, 0.45),
        presenceDot: MetalRGBA(255, 255, 255, 0.18),
        raise: [
            MetalShadow(inset: true, x: 0.0, y: 0.0, blur: 6.0, spread: 2.0, color: MetalRGBA(255, 255, 255, 0.055)),
            MetalShadow(inset: true, x: 1.5, y: 2.5, blur: 3.0, spread: -1.0, color: MetalRGBA(255, 255, 255, 0.1)),
            MetalShadow(inset: true, x: -1.0, y: -3.0, blur: 5.0, spread: -2.0, color: MetalRGBA(0, 0, 0, 0.35)),
            MetalShadow(inset: false, x: 0.0, y: 0.0, blur: 0.0, spread: 0.5, color: MetalRGBA(0, 0, 0, 0.45)),
            MetalShadow(inset: false, x: 0.0, y: 1.0, blur: 2.0, spread: 0.0, color: MetalRGBA(0, 0, 0, 0.22)),
            MetalShadow(inset: false, x: 0.0, y: 8.0, blur: 18.0, spread: -6.0, color: MetalRGBA(0, 0, 0, 0.2)),
            MetalShadow(inset: false, x: 0.0, y: 26.0, blur: 50.0, spread: -16.0, color: MetalRGBA(0, 0, 0, 0.34)),
            MetalShadow(inset: false, x: 0.0, y: 52.0, blur: 96.0, spread: -36.0, color: MetalRGBA(0, 0, 0, 0.3)),
        ],
        raiseSm: [
            MetalShadow(inset: true, x: 0.0, y: 0.0, blur: 4.0, spread: 1.0, color: MetalRGBA(255, 255, 255, 0.06)),
            MetalShadow(inset: true, x: 1.0, y: 2.0, blur: 2.0, spread: -1.0, color: MetalRGBA(255, 255, 255, 0.12)),
            MetalShadow(inset: false, x: 0.0, y: 0.0, blur: 0.0, spread: 0.5, color: MetalRGBA(0, 0, 0, 0.55)),
            MetalShadow(inset: false, x: 0.0, y: 1.0, blur: 2.0, spread: 0.0, color: MetalRGBA(0, 0, 0, 0.3)),
            MetalShadow(inset: false, x: 0.0, y: 5.0, blur: 12.0, spread: -4.0, color: MetalRGBA(0, 0, 0, 0.3)),
        ],
        well: [
            MetalShadow(inset: true, x: 0.0, y: 2.0, blur: 6.0, spread: -1.0, color: MetalRGBA(0, 0, 0, 0.6)),
            MetalShadow(inset: true, x: 0.0, y: 0.0, blur: 0.0, spread: 0.5, color: MetalRGBA(0, 0, 0, 0.35)),
            MetalShadow(inset: true, x: 0.0, y: -2.0, blur: 4.0, spread: -2.0, color: MetalRGBA(255, 255, 255, 0.05)),
        ],
        capBg: MetalGradient(angle: 180.0, stops: [.init(MetalRGBA(53, 53, 58, 1.0), 0.0), .init(MetalRGBA(42, 42, 45, 1.0), 1.0)]),
        capSh: [
            MetalShadow(inset: true, x: 0.0, y: 0.0, blur: 3.0, spread: 1.0, color: MetalRGBA(255, 255, 255, 0.06)),
            MetalShadow(inset: false, x: 0.0, y: 0.0, blur: 0.0, spread: 0.5, color: MetalRGBA(0, 0, 0, 0.6)),
            MetalShadow(inset: false, x: 0.0, y: 1.0, blur: 2.0, spread: 0.0, color: MetalRGBA(0, 0, 0, 0.3)),
        ],
        btnBg: MetalGradient(angle: 180.0, stops: [.init(MetalRGBA(49, 49, 52, 1.0), 0.0), .init(MetalRGBA(40, 40, 43, 1.0), 1.0)]),
        btnSh: [
            MetalShadow(inset: true, x: 0.0, y: 0.0, blur: 4.0, spread: 1.0, color: MetalRGBA(255, 255, 255, 0.05)),
            MetalShadow(inset: true, x: 1.0, y: 2.0, blur: 2.0, spread: -1.0, color: MetalRGBA(255, 255, 255, 0.1)),
            MetalShadow(inset: false, x: 0.0, y: 0.0, blur: 0.0, spread: 0.5, color: MetalRGBA(0, 0, 0, 0.6)),
            MetalShadow(inset: false, x: 0.0, y: 1.0, blur: 2.0, spread: 0.0, color: MetalRGBA(0, 0, 0, 0.3)),
            MetalShadow(inset: false, x: 0.0, y: 4.0, blur: 9.0, spread: -3.0, color: MetalRGBA(0, 0, 0, 0.3)),
        ],
        pressedBg: MetalGradient(angle: 180.0, stops: [.init(MetalRGBA(24, 24, 26, 1.0), 0.0), .init(MetalRGBA(28, 28, 30, 1.0), 1.0)]),
        pressedSh: [
            MetalShadow(inset: true, x: 0.0, y: 2.0, blur: 5.0, spread: -1.0, color: MetalRGBA(0, 0, 0, 0.65)),
            MetalShadow(inset: true, x: 0.0, y: 0.0, blur: 0.0, spread: 0.5, color: MetalRGBA(0, 0, 0, 0.5)),
            MetalShadow(inset: true, x: 0.0, y: -2.0, blur: 3.0, spread: -2.0, color: MetalRGBA(255, 255, 255, 0.05)),
        ],
        duoK: 1.3,
        tintEmber: MetalRGBA(251, 121, 74, 1.0),
        tintBlush: MetalRGBA(237, 107, 162, 1.0),
        tintTide: MetalRGBA(37, 194, 195, 1.0),
        tintSpark: MetalRGBA(206, 118, 220, 1.0),
        tintGraphite: MetalRGBA(166, 166, 169, 1.0),
        tintDusk: MetalRGBA(62, 155, 250, 1.0),
        tintIris: MetalRGBA(137, 134, 250, 1.0)
    )
}

public enum MetalShared {
    public static let page: MetalRGBA = MetalRGBA(243, 243, 241, 1.0)
    public static let pageDark: MetalRGBA = MetalRGBA(14, 14, 15, 1.0)
    public static let green: MetalRGBA = MetalRGBA(120, 214, 165, 1.0)
    public static let greenDeep: MetalRGBA = MetalRGBA(63, 185, 122, 1.0)
    public static let orange: MetalRGBA = MetalRGBA(255, 107, 61, 1.0)
    public static let blue: MetalRGBA = MetalRGBA(36, 87, 242, 1.0)
    public static let red: MetalRGBA = MetalRGBA(216, 69, 59, 1.0)
    public static let gold: MetalRGBA = MetalRGBA(199, 167, 107, 1.0)
    public static let ledGreen: MetalRadialGradient = MetalRadialGradient(center: .init(x: 0.4, y: 0.35), stops: [.init(MetalRGBA(217, 255, 233, 1.0), 0.18), .init(MetalRGBA(123, 234, 174, 1.0), 0.42), .init(MetalRGBA(47, 182, 115, 1.0), 1.0)])
    public static let ledRed: MetalRadialGradient = MetalRadialGradient(center: .init(x: 0.4, y: 0.35), stops: [.init(MetalRGBA(255, 217, 210, 1.0), 0.18), .init(MetalRGBA(255, 122, 102, 1.0), 0.45), .init(MetalRGBA(213, 57, 42, 1.0), 1.0)])
    public static let ledAmber: MetalRadialGradient = MetalRadialGradient(center: .init(x: 0.4, y: 0.35), stops: [.init(MetalRGBA(255, 241, 207, 1.0), 0.18), .init(MetalRGBA(245, 191, 85, 1.0), 0.45), .init(MetalRGBA(201, 138, 24, 1.0), 1.0)])
    public static let ledBlue: MetalRadialGradient = MetalRadialGradient(center: .init(x: 0.4, y: 0.35), stops: [.init(MetalRGBA(216, 230, 255, 1.0), 0.18), .init(MetalRGBA(111, 155, 255, 1.0), 0.45), .init(MetalRGBA(36, 87, 242, 1.0), 1.0)])
    public static let ledOff: MetalRadialGradient = MetalRadialGradient(center: .init(x: 0.4, y: 0.35), stops: [.init(MetalRGBA(139, 139, 142, 1.0), 0.18), .init(MetalRGBA(106, 106, 109, 1.0), 0.5), .init(MetalRGBA(74, 74, 77, 1.0), 1.0)])
    public static let ledRing: [MetalShadow] = [
            MetalShadow(inset: false, x: 0.0, y: 0.0, blur: 0.0, spread: 0.5, color: MetalRGBA(0, 0, 0, 0.25)),
        ]
    public static let success: MetalRGBA = MetalRGBA(170, 212, 124, 1.0)
    public static let warning: MetalRGBA = MetalRGBA(228, 178, 94, 1.0)
    public static let photon: MetalRGBA = MetalRGBA(243, 217, 164, 1.0)
    public static let focus: MetalRGBA = MetalRGBA(63, 185, 122, 1.0)
}

public enum MetalCaps {
    public static let primary = MetalCapTokens(
        bg: MetalGradient(angle: 180.0, stops: [.init(MetalRGBA(56, 56, 60, 1.0), 0.0), .init(MetalRGBA(37, 37, 40, 1.0), 1.0)]),
        sh: [
            MetalShadow(inset: true, x: 0.0, y: 0.0, blur: 5.0, spread: 1.0, color: MetalRGBA(255, 255, 255, 0.07)),
            MetalShadow(inset: true, x: 1.0, y: 2.0, blur: 2.0, spread: -1.0, color: MetalRGBA(255, 255, 255, 0.18)),
            MetalShadow(inset: false, x: 0.0, y: 0.0, blur: 0.0, spread: 0.5, color: MetalRGBA(0, 0, 0, 0.5)),
            MetalShadow(inset: false, x: 0.0, y: 1.0, blur: 2.0, spread: 0.0, color: MetalRGBA(0, 0, 0, 0.15)),
            MetalShadow(inset: false, x: 0.0, y: 5.0, blur: 12.0, spread: -4.0, color: MetalRGBA(0, 0, 0, 0.22)),
        ],
        pressedBg: MetalGradient(angle: 180.0, stops: [.init(MetalRGBA(28, 28, 30, 1.0), 0.0), .init(MetalRGBA(36, 36, 39, 1.0), 1.0)]),
        pressedSh: [
            MetalShadow(inset: true, x: 0.0, y: 1.0, blur: 3.0, spread: 0.0, color: MetalRGBA(0, 0, 0, 0.6)),
            MetalShadow(inset: false, x: 0.0, y: 0.0, blur: 0.0, spread: 0.5, color: MetalRGBA(0, 0, 0, 0.7)),
        ],
        ink: MetalRGBA(255, 255, 255, 1.0)
    )
    public static let destructive = MetalCapTokens(
        bg: MetalGradient(angle: 180.0, stops: [.init(MetalRGBA(230, 89, 78, 1.0), 0.0), .init(MetalRGBA(208, 67, 58, 1.0), 1.0)]),
        sh: [
            MetalShadow(inset: true, x: 0.0, y: 0.0, blur: 6.0, spread: 1.0, color: MetalRGBA(255, 255, 255, 0.14)),
            MetalShadow(inset: true, x: 1.0, y: 2.0, blur: 2.0, spread: -1.0, color: MetalRGBA(255, 255, 255, 0.32)),
            MetalShadow(inset: false, x: 0.0, y: 0.0, blur: 0.0, spread: 0.5, color: MetalRGBA(120, 20, 10, 0.3)),
            MetalShadow(inset: false, x: 0.0, y: 1.0, blur: 2.0, spread: 0.0, color: MetalRGBA(110, 10, 0, 0.14)),
            MetalShadow(inset: false, x: 0.0, y: 5.0, blur: 12.0, spread: -4.0, color: MetalRGBA(170, 30, 20, 0.24)),
        ],
        pressedBg: MetalGradient(angle: 180.0, stops: [.init(MetalRGBA(190, 53, 44, 1.0), 0.0), .init(MetalRGBA(207, 66, 56, 1.0), 1.0)]),
        pressedSh: [
            MetalShadow(inset: true, x: 0.0, y: 1.0, blur: 3.0, spread: 0.0, color: MetalRGBA(80, 0, 0, 0.45)),
            MetalShadow(inset: false, x: 0.0, y: 0.0, blur: 0.0, spread: 0.5, color: MetalRGBA(110, 10, 0, 0.55)),
        ],
        ink: MetalRGBA(255, 255, 255, 1.0)
    )
}

public enum MetalSprings {
    /// parts you touch: thumbs, toggles, keys, detents; may overshoot against a stop
    public static let part = MetalSpring(stiffness: 170.0, damping: 16.0, duration: 0.6)
    /// objects landing on the table: a dropped block settling in a region, folder cards, a stack opening; a stop, and rare by design
    public static let object = MetalSpring(stiffness: 120.0, damping: 13.0, duration: 0.92)
    /// anything on a hinge: flaps, lids, drawers that tilt
    public static let hinge = MetalSpring(stiffness: 120.0, damping: 14.0, duration: 0.94)
    /// floating surfaces (menus, palettes, toasts, dialogs) rising and settling; no stop, so no overshoot
    public static let surface = MetalSpring(stiffness: 220.0, damping: 28.0, duration: 0.5)
    /// arrivals and footprints: content coming into place, a control growing to new content, the hover lift (T5a)
    public static let settle = MetalSpring(stiffness: 380.0, damping: 36.0, duration: 0.44)
    /// departures and letting go: content leaving, a pressed cap returning
    public static let release = MetalSpring(stiffness: 500.0, damping: 40.0, duration: 0.3)
    /// a refusal shake: released from one nest aside, it rings against the nest walls and dies out
    public static let refusal = MetalSpring(stiffness: 900.0, damping: 12.0, duration: 1.1)
}

/// How a spring class resolves under Reduce Motion (foundations.reduced-motion).
public enum MetalReducedMotion: String, Sendable {
    /// Plays as authored: the motion is feedback, not decoration.
    case unchanged
    /// Travel and scale go; opacity stays and rides the crossfade spring.
    case crossfade
    /// The new state applies at once.
    case instant
}

/// The mass classes. Pick the class; the spring and its Reduce Motion policy follow.
public enum MetalSpringClass: String, CaseIterable, Sendable {
    /// parts you touch: thumbs, toggles, keys, detents; may overshoot against a stop
    case part
    /// objects landing on the table: a dropped block settling in a region, folder cards, a stack opening; a stop, and rare by design
    case object
    /// anything on a hinge: flaps, lids, drawers that tilt
    case hinge
    /// floating surfaces (menus, palettes, toasts, dialogs) rising and settling; no stop, so no overshoot
    case surface
    /// arrivals and footprints: content coming into place, a control growing to new content, the hover lift (T5a)
    case settle
    /// departures and letting go: content leaving, a pressed cap returning
    case release
    /// a refusal shake: released from one nest aside, it rings against the nest walls and dies out
    case refusal

    public var spring: MetalSpring {
        switch self {
        case .part: return MetalSprings.part
        case .object: return MetalSprings.object
        case .hinge: return MetalSprings.hinge
        case .surface: return MetalSprings.surface
        case .settle: return MetalSprings.settle
        case .release: return MetalSprings.release
        case .refusal: return MetalSprings.refusal
        }
    }

    public var reducedMotion: MetalReducedMotion {
        switch self {
        case .part: return .instant
        case .object: return .instant
        case .hinge: return .instant
        case .surface: return .crossfade
        case .settle: return .crossfade
        case .release: return .unchanged
        case .refusal: return .instant
        }
    }

    /// The class whose spring carries a crossfade under Reduce Motion.
    public static let crossfade: MetalSpringClass = .settle
}

/// Feelings tints color the glyph's stroke, so the line itself evokes the feeling; a tinted glyph's vessel is not filled, and any other duotone part follows the stroke at its usual opacity. A tint names the kind of feeling (joy, affection, calm, wonder, neutral, low, tension), never its strength, which the glyph's shape shows. Every stroke speaks at the orange's voice (chroma about 0.19) and clears 3.3:1 on bone and 4.5:1 on graphite. Glyphs only, never words, never status or intent; off under Increase Contrast and inside data-mu-untinted.
public enum MetalTint: String, CaseIterable, Sendable {
    /// joy: happy, excited, energised, proud, party
    case ember
    /// affection: loved, grateful, date, friend, family, gift
    case blush
    /// calm: calm, rested, hopeful
    case tide
    /// wonder: curious
    case spark
    /// neutral: focused, distracted, bored
    case graphite
    /// low: dull, lonely, sad, drained, tired
    case dusk
    /// tension: anxious, angry, stressed, frustrated, overwhelmed
    case iris

    /// The stroke color in a colorway; the glyph's duotone body follows it.
    public func color(in colorway: MetalColorway) -> MetalRGBA {
        switch self {
        case .ember: return colorway.tokens.tintEmber
        case .blush: return colorway.tokens.tintBlush
        case .tide: return colorway.tokens.tintTide
        case .spark: return colorway.tokens.tintSpark
        case .graphite: return colorway.tokens.tintGraphite
        case .dusk: return colorway.tokens.tintDusk
        case .iris: return colorway.tokens.tintIris
        }
    }

    /// The kind of feeling the tint names.
    public var kind: String {
        switch self {
        case .ember: return "joy"
        case .blush: return "affection"
        case .tide: return "calm"
        case .spark: return "wonder"
        case .graphite: return "neutral"
        case .dusk: return "low"
        case .iris: return "tension"
        }
    }

    public var valence: String {
        switch self {
        case .ember: return "pleasant"
        case .blush: return "pleasant"
        case .tide: return "pleasant"
        case .spark: return "pleasant"
        case .graphite: return "neutral"
        case .dusk: return "unpleasant"
        case .iris: return "unpleasant"
        }
    }
}

/// E2 floating: a surface above other objects blurs what is behind it, lays a translucent fill over the blur, and wears its recipe's shadow stack. Every frosted recipe has an opaque twin: under Reduce Transparency (prefers-reduced-transparency, or data-mu-transparency="reduce" on any ancestor) the fill turns opaque and the blur goes. Under Increase Contrast a contrast-edge hairline rims the surface. A fill or opaque value that names a colorway key follows the colorway; anything else is the same in both.
public enum MetalFrost: String, CaseIterable, Sendable {
    /// A frosted toolbar strip in the colorway (KAMUI-01/02).
    case strip
    /// Floating plates: command palette, menus, popovers, the lens bar and panel (KAMUI-06).
    case plate
    /// Dense dark chrome that stays graphite in both colorways: the selection tool strip, the medium toolbar, tooltips, the past banner.
    case graphite

    /// The blur behind every frosted recipe (CSS `--mu-backdrop`).
    public static let blur: Double = 22.0
    public static let saturation: Double = 1.6

    /// The recipe in a colorway: translucent fill, shadow stack, backdrop, opaque twin and contrast edge.
    public func recipe(in colorway: MetalColorway) -> MetalRecipe {
        let t = colorway.tokens
        switch self {
        case .strip:
            return MetalRecipe(
                fill: .solid(t.frost),
                shadows: t.raise,
                backdrop: MetalBackdrop(blur: Self.blur, saturation: Self.saturation, dark: colorway == .graphite),
                opaqueFill: .solid(t.frostOpaque),
                contrastEdge: t.contrastEdge
            )
        case .plate:
            return MetalRecipe(
                fill: .solid(t.frostStrong),
                shadows: t.raise,
                backdrop: MetalBackdrop(blur: Self.blur, saturation: Self.saturation, dark: colorway == .graphite),
                opaqueFill: .solid(t.frostOpaque),
                contrastEdge: t.contrastEdge
            )
        case .graphite:
            return MetalRecipe(
                fill: MetalGradient(angle: 180.0, stops: [.init(MetalRGBA(40, 40, 43, 0.94), 0.0), .init(MetalRGBA(27, 27, 29, 0.96), 1.0)]),
                shadows: [
                    MetalShadow(inset: true, x: 0.0, y: 0.0, blur: 6.0, spread: 2.0, color: MetalRGBA(255, 255, 255, 0.055)),
                    MetalShadow(inset: true, x: 1.5, y: 2.5, blur: 3.0, spread: -1.0, color: MetalRGBA(255, 255, 255, 0.1)),
                    MetalShadow(inset: true, x: -1.0, y: -3.0, blur: 5.0, spread: -2.0, color: MetalRGBA(0, 0, 0, 0.35)),
                    MetalShadow(inset: false, x: 0.0, y: 0.0, blur: 0.0, spread: 0.5, color: MetalRGBA(0, 0, 0, 0.45)),
                    MetalShadow(inset: false, x: 0.0, y: 1.0, blur: 2.0, spread: 0.0, color: MetalRGBA(0, 0, 0, 0.2)),
                    MetalShadow(inset: false, x: 0.0, y: 12.0, blur: 28.0, spread: -10.0, color: MetalRGBA(0, 0, 0, 0.34)),
                    MetalShadow(inset: false, x: 0.0, y: 30.0, blur: 60.0, spread: -24.0, color: MetalRGBA(0, 0, 0, 0.3)),
                ],
                backdrop: MetalBackdrop(blur: Self.blur, saturation: Self.saturation, dark: true),
                opaqueFill: MetalGradient(angle: 180.0, stops: [.init(MetalRGBA(40, 40, 43, 1.0), 0.0), .init(MetalRGBA(27, 27, 29, 1.0), 1.0)]),
                contrastEdge: MetalTokens.graphite.contrastEdge
            )
        }
    }
}

/// KAMUI-14, the one selection for every kind of object, and the presence around a borderless one. The ring sits at ring.select-offset from the object (radius + offset), a flat collar outside it; eight handles sit on the ring line (round caps at the corners, capsules at the edge midpoints; on text, the n and s capsules are grips that move the object); a graphite readout under the object reads its measured frame. Hover shows only faint corner dots, and an edge light where the pointer enters the band. Values are the object sheet (Rev B, the precision pass) and Kamui's KamuiSoftHardware.Presence.
public enum MetalPresence {
    public static let ringWidth: Double = 1.25
    public static let ring: MetalRGBA = MetalRGBA(63, 185, 122, 1.0)
    public static let ringDark: MetalRGBA = MetalRGBA(120, 214, 165, 1.0)
    public static let collarWidth: Double = 3.5
    public static let collar: MetalRGBA = MetalRGBA(120, 214, 165, 0.16)
    public static let liteWidth: Double = 1.0
    public static let lite: MetalRGBA = MetalRGBA(63, 185, 122, 0.55)
    public static let enterScale: Double = 1.02
    public static let bandOutside: Double = 10.0
    public static let bandInside: Double = 6.0
    public static let edgeLightWidth: Double = 1.5
    public static let edgeLight: MetalRGBA = MetalRGBA(120, 214, 165, 0.55)
    public static let hoverDot: Double = 5.0
    public static let handle: Double = 10.0
    public static let handleBg: MetalRadialGradient = MetalRadialGradient(center: .init(x: 0.38, y: 0.32), stops: [.init(MetalRGBA(255, 255, 255, 1.0), 0.0), .init(MetalRGBA(237, 237, 234, 1.0), 0.7)])
    public static let handleSh: [MetalShadow] = [
        MetalShadow(inset: false, x: 0.0, y: 0.0, blur: 0.0, spread: 1.0, color: MetalRGBA(63, 185, 122, 1.0)),
        MetalShadow(inset: true, x: 0.0, y: 0.0, blur: 2.0, spread: 1.0, color: MetalRGBA(255, 255, 255, 0.9)),
        MetalShadow(inset: false, x: 0.0, y: 1.0, blur: 2.0, spread: 0.0, color: MetalRGBA(0, 0, 0, 0.18)),
        MetalShadow(inset: false, x: 0.0, y: 3.0, blur: 6.0, spread: -2.0, color: MetalRGBA(0, 0, 0, 0.14)),
    ]
    public static let capsuleLength: Double = 18.0
    public static let capsuleThickness: Double = 6.0
    public static let gripBg: MetalGradient = MetalGradient(angle: 180.0, stops: [.init(MetalRGBA(255, 255, 255, 1.0), 0.0), .init(MetalRGBA(237, 236, 232, 1.0), 1.0)])
    public static let gripSh: [MetalShadow] = [
        MetalShadow(inset: false, x: 0.0, y: 0.0, blur: 0.0, spread: 1.0, color: MetalRGBA(63, 185, 122, 0.75)),
        MetalShadow(inset: false, x: 0.0, y: 1.0, blur: 2.0, spread: 0.0, color: MetalRGBA(0, 0, 0, 0.18)),
    ]
    public static let handleHit: Double = 7.0
    public static let readoutHeight: Double = 24.0
    public static let readoutGap: Double = 16.0
    public static let readoutPadStart: Double = 10.0
    public static let readoutPadEnd: Double = 11.0
    public static let readoutGapInner: Double = 7.0
    public static let readoutBg: MetalGradient = MetalGradient(angle: 180.0, stops: [.init(MetalRGBA(42, 42, 45, 1.0), 0.0), .init(MetalRGBA(27, 27, 29, 1.0), 1.0)])
    public static let readoutSh: [MetalShadow] = [
        MetalShadow(inset: true, x: 0.0, y: 0.0, blur: 5.0, spread: 1.0, color: MetalRGBA(255, 255, 255, 0.06)),
        MetalShadow(inset: true, x: 1.0, y: 2.0, blur: 2.0, spread: -1.0, color: MetalRGBA(255, 255, 255, 0.14)),
        MetalShadow(inset: false, x: 0.0, y: 0.0, blur: 0.0, spread: 0.5, color: MetalRGBA(0, 0, 0, 0.4)),
        MetalShadow(inset: false, x: 0.0, y: 2.0, blur: 4.0, spread: 0.0, color: MetalRGBA(0, 0, 0, 0.14)),
        MetalShadow(inset: false, x: 0.0, y: 8.0, blur: 16.0, spread: -6.0, color: MetalRGBA(0, 0, 0, 0.2)),
    ]
    public static let readoutInk: MetalRGBA = MetalRGBA(233, 233, 231, 1.0)
    public static let readoutDim: MetalRGBA = MetalRGBA(110, 110, 114, 1.0)
    /// In em.
    public static let readoutTracking: Double = 0.04
    public static let readoutLed: Double = 4.0
    public static let readoutWriting: Double = 0.78
    public static let copiedMs: Double = 900.0

    /// The ring colour in a colorway: green-deep on bone, green on graphite.
    public static func ringColor(in colorway: MetalColorway) -> MetalRGBA { colorway == .graphite ? ringDark : ring }
}
