// Generated by scripts/build-tokens.mjs from tokens/tokens.json (sound). Do not edit.
// The recipes MetalSound plays; recipes.generated.ts carries the same table for Web Audio.

/// The materials a part can be cut from, as they sound when struck.
public enum MetalSoundMaterial: String, CaseIterable, Sendable {
    case clay
    case ceramic
    case resin
    case stone
    case glass
    case metal
    case rubber

    public var recipe: MetalMaterialSound {
        switch self {
        case .clay: // A soft, short, damp knock.
            return MetalMaterialSound(
                f0x: 0.9, tone: 0.8, loud: 0.6, attackMs: 3.0, maxMs: 150.0,
                noisyModes: false, thump: true,
                modes: [.init(ratio: 1.0, gain: 1.0, decayMs: 70.0, glideTo: nil, glideMs: nil), .init(ratio: 1.58, gain: 0.35, decayMs: 40.0, glideTo: nil, glideMs: nil), .init(ratio: 2.2, gain: 0.15, decayMs: 25.0, glideTo: nil, glideMs: nil)],
                noise: [.init(kind: .bandpass, frequency: 1500.0, q: 1.2, ms: 18.0, gain: 0.81), .init(kind: .lowpass, frequency: 700.0, q: nil, ms: 25.0, gain: 0.36)],
                grit: nil,
                bounce: nil
            )
        case .ceramic: // A bright tink, like a cup.
            return MetalMaterialSound(
                f0x: 1.3, tone: 1.0, loud: 1.0, attackMs: 1.5, maxMs: 450.0,
                noisyModes: false, thump: true,
                modes: [.init(ratio: 1.0, gain: 1.0, decayMs: 320.0, glideTo: nil, glideMs: nil), .init(ratio: 2.4, gain: 0.5, decayMs: 200.0, glideTo: nil, glideMs: nil), .init(ratio: 4.6, gain: 0.2, decayMs: 120.0, glideTo: nil, glideMs: nil)],
                noise: [.init(kind: .bandpass, frequency: 4500.0, q: 3.0, ms: 20.0, gain: 0.81)],
                grit: nil,
                bounce: nil
            )
        case .resin: // A hard, short, slightly hollow tock, like tapping a thick acrylic block.
            return MetalMaterialSound(
                f0x: 1.1, tone: 0.9, loud: 0.8, attackMs: 1.5, maxMs: 220.0,
                noisyModes: false, thump: true,
                modes: [.init(ratio: 1.0, gain: 1.0, decayMs: 150.0, glideTo: nil, glideMs: nil), .init(ratio: 2.61, gain: 0.35, decayMs: 90.0, glideTo: nil, glideMs: nil), .init(ratio: 4.9, gain: 0.12, decayMs: 50.0, glideTo: nil, glideMs: nil)],
                noise: [.init(kind: .bandpass, frequency: 3000.0, q: 1.5, ms: 12.0, gain: 0.72)],
                grit: nil,
                bounce: nil
            )
        case .stone: // A dead, gritty knock that stops almost at once.
            return MetalMaterialSound(
                f0x: 0.8, tone: 0.8, loud: 0.55, attackMs: 1.0, maxMs: 120.0,
                noisyModes: true, thump: true,
                modes: [.init(ratio: 1.0, gain: 1.0, decayMs: 35.0, glideTo: nil, glideMs: nil), .init(ratio: 1.73, gain: 0.6, decayMs: 25.0, glideTo: nil, glideMs: nil), .init(ratio: 2.91, gain: 0.35, decayMs: 18.0, glideTo: nil, glideMs: nil), .init(ratio: 4.14, gain: 0.2, decayMs: 12.0, glideTo: nil, glideMs: nil)],
                noise: [.init(kind: .lowpass, frequency: 900.0, q: nil, ms: 30.0, gain: 0.9), .init(kind: .highpass, frequency: 3000.0, q: nil, ms: 8.0, gain: 0.18)],
                grit: .init(count: 5, spreadMs: 22.0, frequency: 2200.0, level: 0.22),
                bounce: nil
            )
        case .glass: // A short, high, pure tink.
            return MetalMaterialSound(
                f0x: 2.1, tone: 1.0, loud: 1.0, attackMs: 0.6, maxMs: 320.0,
                noisyModes: false, thump: true,
                modes: [.init(ratio: 1.0, gain: 1.0, decayMs: 260.0, glideTo: nil, glideMs: nil), .init(ratio: 2.32, gain: 0.4, decayMs: 150.0, glideTo: nil, glideMs: nil), .init(ratio: 4.25, gain: 0.2, decayMs: 80.0, glideTo: nil, glideMs: nil)],
                noise: [.init(kind: .bandpass, frequency: 8500.0, q: 5.0, ms: 7.0, gain: 0.72)],
                grit: nil,
                bounce: nil
            )
        case .metal: // A lower clang that hangs on and beats.
            return MetalMaterialSound(
                f0x: 0.7, tone: 1.0, loud: 1.0, attackMs: 0.5, maxMs: 1200.0,
                noisyModes: false, thump: true,
                modes: [.init(ratio: 1.0, gain: 1.0, decayMs: 1100.0, glideTo: nil, glideMs: nil), .init(ratio: 1.006, gain: 0.8, decayMs: 1100.0, glideTo: nil, glideMs: nil), .init(ratio: 2.76, gain: 0.7, decayMs: 800.0, glideTo: nil, glideMs: nil), .init(ratio: 2.781, gain: 0.5, decayMs: 800.0, glideTo: nil, glideMs: nil), .init(ratio: 5.4, gain: 0.45, decayMs: 600.0, glideTo: nil, glideMs: nil), .init(ratio: 8.93, gain: 0.25, decayMs: 400.0, glideTo: nil, glideMs: nil), .init(ratio: 13.34, gain: 0.12, decayMs: 250.0, glideTo: nil, glideMs: nil)],
                noise: [.init(kind: .bandpass, frequency: 3500.0, q: 1.2, ms: 10.0, gain: 1.08)],
                grit: nil,
                bounce: nil
            )
        case .rubber: // A short, dull pock with a little give, and a small second bounce.
            return MetalMaterialSound(
                f0x: 0.95, tone: 0.7, loud: 0.7, attackMs: 1.5, maxMs: 120.0,
                noisyModes: false, thump: false,
                modes: [.init(ratio: 1.0, gain: 1.0, decayMs: 45.0, glideTo: 0.93, glideMs: 18.0), .init(ratio: 2.3, gain: 0.3, decayMs: 22.0, glideTo: nil, glideMs: nil)],
                noise: [.init(kind: .bandpass, frequency: 1200.0, q: 0.9, ms: 12.0, gain: 0.9), .init(kind: .lowpass, frequency: 600.0, q: nil, ms: 16.0, gain: 0.315)],
                grit: nil,
                bounce: .init(ms: 70.0, level: 0.25)
            )
        }
    }
}

/// Where an act goes: toward yourself it is dry and close; toward others or the world it has room.
public enum MetalSoundReach: String, CaseIterable, Sendable {
    case own
    case others
    case world

    public var send: Double { switch self { case .own: return 0.05; case .others: return 0.22; case .world: return 0.4 } }
    public var pan: Double { switch self { case .own: return 0.0; case .others: return 0.15; case .world: return 0.25 } }
}

/// How each material sounds sliding: its contact band, and the grit a rough surface adds.
public struct MetalScrapeRecipe: Sendable { public let f: Double, q: Double, gain: Double, grit: Double, gritLevel: Double }
extension MetalSoundMaterial {
    public var scrape: MetalScrapeRecipe {
        switch self {
        case .clay: return .init(f: 1400.0, q: 1.0, gain: 1.0, grit: 24.0, gritLevel: 0.5)
        case .ceramic: return .init(f: 3600.0, q: 2.2, gain: 0.6, grit: 0.0, gritLevel: 0.0)
        case .resin: return .init(f: 2400.0, q: 1.4, gain: 0.7, grit: 8.0, gritLevel: 0.3)
        case .stone: return .init(f: 1000.0, q: 0.8, gain: 1.1, grit: 60.0, gritLevel: 0.7)
        case .glass: return .init(f: 5200.0, q: 3.5, gain: 0.45, grit: 0.0, gritLevel: 0.0)
        case .metal: return .init(f: 2900.0, q: 1.8, gain: 0.75, grit: 4.0, gritLevel: 0.25)
        case .rubber: return .init(f: 650.0, q: 0.7, gain: 0.9, grit: 0.0, gritLevel: 0.0)
        }
    }
}

/// The beeper's messages: a change of state, never an act.
public enum MetalEarcon: String, CaseIterable, Sendable {
    case done
    case failed
    case waiting
    case ready

    public var label: String { switch self { case .done: return "Done"; case .failed: return "Failed"; case .waiting: return "Waiting"; case .ready: return "Ready" } }
    /// [midi, at ms, length ms, level]
    public var notes: [MetalEarconNote] {
        switch self {
        case .done: return [.init(midi: 79, atMs: 0.0, lengthMs: 90.0, level: 1.0), .init(midi: 86, atMs: 120.0, lengthMs: 90.0, level: 1.0)]
        case .failed: return [.init(midi: 67, atMs: 0.0, lengthMs: 90.0, level: 1.2), .init(midi: 67, atMs: 150.0, lengthMs: 120.0, level: 0.8), .init(midi: 68, atMs: 150.0, lengthMs: 120.0, level: 0.8)]
        case .waiting: return [.init(midi: 76, atMs: 0.0, lengthMs: 90.0, level: 1.0), .init(midi: 76, atMs: 300.0, lengthMs: 90.0, level: 1.0)]
        case .ready: return [.init(midi: 72, atMs: 0.0, lengthMs: 90.0, level: 1.0), .init(midi: 76, atMs: 60.0, lengthMs: 90.0, level: 1.0), .init(midi: 79, atMs: 120.0, lengthMs: 160.0, level: 1.0)]
        }
    }
    public var levelDb: Double { switch self { case .done: return -20.0; case .failed: return -20.0; case .waiting: return -20.0; case .ready: return -20.0 } }
}

/// The rest of the sound foundation: policy, pitch, room, thump and the beeper's timbre.
public enum MetalSoundTokens {
    public static let gapMs: Double = 1500.0
    public static let burst: Int = 3
    public static let burstWindowMs: Double = 10000.0
    public static let varyF0: Double = 0.03
    public static let varyDecay: Double = 0.1
    public static let varyFilter: Double = 0.06
    /// [plays, dB]: a part that has played this often in a session plays this much quieter.
    public static let decayAfter: [(plays: Int, db: Double)] = [(20, -2.0), (60, -4.0)]
    public static let actDb: Double = -17.0
    public static let limitDb: Double = -20.0
    /// [rendered size in points, gain]
    public static let sizeGain: [(size: Double, gain: Double)] = [(32.0, 0.55), (64.0, 0.75), (160.0, 1.0)]
    public static let pitchBase: Double = 2400.0
    public static let pitchRef: Double = 16.0
    public static let pitchHeavy: Double = 0.35
    public static let bodySize: Double = 320.0
    public static let roomSeconds: Double = 1.6
    public static let roomCurve: Double = 3.2
    public static let thumpFrom: Double = 150.0
    public static let thumpTo: Double = 60.0
    public static let thumpMs: Double = 90.0
    public static let thumpAbove: Double = 0.5
    public static let thumpLevel: Double = 0.36
    public static let contactAttackMs: Double = 0.8
    public static let bandQ: Double = 2.2
    public static let bandGain: Double = 1.6
    public static let gritQ: Double = 3.0
    public static let gritMs: Double = 3.0
    public static let gritSpread: Double = 0.3
    public static let bouncePitch: Double = 1.04
    public static let ceilingHz: Double = 16000.0
    public static let beeperResonance: Double = 3200.0
    public static let beeperQ: Double = 6.0
    public static let beeperBoostDb: Double = 9.0
    public static let beeperSquare: Double = 0.02
    public static let beeperAttackMs: Double = 2.0
    /// A part sliding: level at full speed, how fast the level follows the speed and dies away, and how much the band rises with speed.
    public static let scrapeLevelDb: Double = -24.0
    public static let scrapeSmoothMs: Double = 30.0
    public static let scrapeReleaseMs: Double = 80.0
    public static let scrapeSpeedPitch: Double = 0.35
    public static let scrapeGritMs: Double = 3.0
    public static let scrapeGritBand: Double = 1.6
}
