// Generated by scripts/build-gadgets.mjs from tokens/tokens.json (gadgets). Do not edit.
// The visual foundations of gadgets; MetalSoundMaterial carries the acoustic recipes (same cases).

extension MetalSoundMaterial {
    /// The finish of a body cut from this material: how the one light shades it.
    public var finish: MetalGadgetFinish {
        switch self {
        case .clay:
            return MetalGadgetFinish(
                lightness: (0.55, 0.88), chromaCap: 0.1, bevel: 6.0, surfaceScale: 5.0,
                diffuse: 1.12, glossExponent: 0.0, glossStrength: 0.0,
                grainFrequency: 1.1, grainAmplitude: 0.025, grainDirectional: false,
                flecks: 0.5, translucency: 0.0,
                cast: MetalGadgetShadow(blur: 16.0, dx: 6.0, dy: 18.0, alpha: 0.24), contact: MetalGadgetShadow(blur: 3.0, dx: 1.0, dy: 4.0, alpha: 0.14),
                sampleHue: 80.0, strikeTravel: 1.0, strikeSquash: 0.008
            )
        case .ceramic:
            return MetalGadgetFinish(
                lightness: (0.8, 0.92), chromaCap: 0.12, bevel: 5.0, surfaceScale: 4.0,
                diffuse: 1.1, glossExponent: 40.0, glossStrength: 0.35,
                grainFrequency: 0.6, grainAmplitude: 0.008, grainDirectional: false,
                flecks: 0.0, translucency: 0.05,
                cast: MetalGadgetShadow(blur: 14.0, dx: 6.0, dy: 16.0, alpha: 0.22), contact: MetalGadgetShadow(blur: 3.0, dx: 1.0, dy: 4.0, alpha: 0.14),
                sampleHue: 330.0, strikeTravel: 0.5, strikeSquash: 0.0
            )
        case .resin:
            return MetalGadgetFinish(
                lightness: (0.7, 0.9), chromaCap: 0.2, bevel: 7.0, surfaceScale: 5.0,
                diffuse: 1.08, glossExponent: 24.0, glossStrength: 0.25,
                grainFrequency: 0.9, grainAmplitude: 0.012, grainDirectional: false,
                flecks: 0.3, translucency: 0.6,
                cast: MetalGadgetShadow(blur: 14.0, dx: 6.0, dy: 16.0, alpha: 0.2), contact: MetalGadgetShadow(blur: 3.0, dx: 1.0, dy: 4.0, alpha: 0.12),
                sampleHue: 55.0, strikeTravel: 0.75, strikeSquash: 0.0
            )
        case .stone:
            return MetalGadgetFinish(
                lightness: (0.45, 0.75), chromaCap: 0.05, bevel: 8.0, surfaceScale: 6.0,
                diffuse: 1.14, glossExponent: 6.0, glossStrength: 0.08,
                grainFrequency: 1.6, grainAmplitude: 0.04, grainDirectional: false,
                flecks: 1.2, translucency: 0.0,
                cast: MetalGadgetShadow(blur: 18.0, dx: 6.0, dy: 20.0, alpha: 0.28), contact: MetalGadgetShadow(blur: 3.0, dx: 1.0, dy: 4.0, alpha: 0.16),
                sampleHue: 195.0, strikeTravel: 0.5, strikeSquash: 0.0
            )
        case .glass:
            return MetalGadgetFinish(
                lightness: (0.22, 0.45), chromaCap: 0.06, bevel: 3.0, surfaceScale: 3.0,
                diffuse: 1.0, glossExponent: 80.0, glossStrength: 0.6,
                grainFrequency: 0.0, grainAmplitude: 0.0, grainDirectional: false,
                flecks: 0.0, translucency: 0.8,
                cast: MetalGadgetShadow(blur: 12.0, dx: 5.0, dy: 14.0, alpha: 0.24), contact: MetalGadgetShadow(blur: 2.0, dx: 1.0, dy: 3.0, alpha: 0.18),
                sampleHue: 260.0, strikeTravel: 0.25, strikeSquash: 0.0
            )
        case .metal:
            return MetalGadgetFinish(
                lightness: (0.4, 0.8), chromaCap: 0.08, bevel: 4.0, surfaceScale: 4.0,
                diffuse: 1.05, glossExponent: 60.0, glossStrength: 0.5,
                grainFrequency: 2.4, grainAmplitude: 0.02, grainDirectional: true,
                flecks: 0.0, translucency: 0.0,
                cast: MetalGadgetShadow(blur: 12.0, dx: 5.0, dy: 14.0, alpha: 0.26), contact: MetalGadgetShadow(blur: 2.0, dx: 1.0, dy: 3.0, alpha: 0.18),
                sampleHue: 230.0, strikeTravel: 0.25, strikeSquash: 0.0
            )
        case .rubber:
            return MetalGadgetFinish(
                lightness: (0.22, 0.4), chromaCap: 0.03, bevel: 9.0, surfaceScale: 6.0,
                diffuse: 1.15, glossExponent: 0.0, glossStrength: 0.0,
                grainFrequency: 1.3, grainAmplitude: 0.03, grainDirectional: false,
                flecks: 0.0, translucency: 0.0,
                cast: MetalGadgetShadow(blur: 20.0, dx: 6.0, dy: 22.0, alpha: 0.32), contact: MetalGadgetShadow(blur: 4.0, dx: 1.0, dy: 5.0, alpha: 0.18),
                sampleHue: 25.0, strikeTravel: 2.0, strikeSquash: 0.03
            )
        }
    }
}

/// The gadget foundations that are not per material.
public enum MetalGadgetTokens {
    public static let canvas: Double = 400.0
    public static let bodyRect: (x: Double, y: Double, width: Double, height: Double) = (40.0, 36.0, 320.0, 320.0)
    public static let bodyRadius: Double = 76.0
    public static let lightAzimuth: Double = 225.0
    public static let lightElevation: Double = 62.0
    public static let partBevel: Double = 0.55
    public static let partShadow: Double = 0.6
    public static let holeBlur: Double = 4.0
    public static let holeOffset: (dx: Double, dy: Double) = (3.0, 6.0)
    public static let holeAlpha: Double = 0.55
    public static let tierFull: Double = 96.0
    public static let tierLite: Double = 48.0
    public static let liteBevel: Double = 0.6
    public static let graphiteShadow: Double = 1.35
    public static let graphiteBrightDrop: Double = 0.04
    public static let graphiteBrightAbove: Double = 0.84
    public static let contrastShadow: Double = 1.2
    public static let glintAbove: Double = 0.2
    public static let glintMs: Double = 420.0
    public static let jackHole: Double = 0.44
    public static let jackKnurls: Double = 12.0
    public static let jackKnurl: (Double, Double) = (0.66, 0.88)
    public static let jackMetal: (L: Double, C: Double, H: Double) = (0.78, 0.012, 230.0)
    public static let jackFloor: Double = 0.24
    public static let plugSide: Double = 0.15
    public static let plugSkirt: Double = 0.12
    public static let plugKnurls: Int = 6
    public static let plugKnurl: (Double, Double) = (0.62, 0.86)
    public static let plugKnurlAlpha: Double = 0.2
    public static let plugBoss: Double = 0.4
    public static let plugStub: (length: Double, width: Double) = (0.9, 0.5)
    public static let plugShadow: (blur: Double, dx: Double, dy: Double, alpha: Double) = (0.26, 0.3, 0.5, 0.42)
    public static let plugAlone: Double = 180.0
    public static let plugFace: Double = 0.94
    public static let plugCentreY: Double = 196.0
    public static let plugStubFrom: Double = 0.7
    public static let plugStubL: Double = 0.34
    public static let plugStubChroma: Double = 0.01
    public static let plugFaceClay: Double = 0.9
    public static let plugFaceChroma: Double = 0.012
    public static let plugBossDrop: Double = 0.04
    public static let plugKnurlWidth: Double = 0.1
    public static let cableWidth: Double = 13.5
    public static let cableSag: (share: Double, min: Double, max: Double) = (0.18, 24.0, 90.0)
    public static let cableHandle: Double = 0.3
    public static let cableRubber: (L: Double, C: Double) = (0.3, 0.012)
    public static let cableShade: (drop: Double, width: Double, dx: Double, dy: Double) = (0.07, 0.5, 0.1, 0.13)
    public static let cableSheen: (width: Double, dx: Double, dy: Double, alpha: Double) = (0.2, -0.16, -0.2, 0.22)
    public static let cableShadow: (blur: Double, dx: Double, dy: Double, alpha: Double) = (0.35, 0.25, 0.45, 0.4)
    public static let cableSpring = MetalSprings.hinge
    public static let beeperAlone: Double = 240.0
    public static let beeperRadius: Double = 0.3
    public static let beeperSlots: Int = 5
    public static let beeperSlot: (width: Double, height: Double) = (0.075, 0.6)
    public static let beeperSpan: Double = 0.72
    public static let beeperBrass: (L: Double, C: Double, H: Double) = (0.5, 0.075, 82.0)
    public static let beeperLitL: Double = 0.8
    public static let beeperLift: Double = 0.023
    public static let beeperRiseMs: Double = 12.0
    public static let beeperFallMs: Double = 70.0
    public static let beeperSampleMs: Double = 10.0
    public static let beeperAspect: Double = 0.5455
    public static let capRadius: Double = 13.0
    public static let capSide: Double = 4.0
    public static let capSideDrop: Double = 0.1
    public static let capRibs: Int = 3
    public static let capPitch: Double = 8.0
    public static let capSpan: Double = 0.57
    public static let capGroove: (width: Double, alpha: Double) = (2.4, 0.24)
    public static let capEdge: (width: Double, alpha: Double, dy: Double) = (1.1, 0.7, 1.8)
    public static let capPointer: (from: Double, to: Double) = (0.3, 0.78)
    public static let capPointerScale: Double = 1.4
    public static let capGrooveInk: (drop: Double, floor: Double, gain: Double, add: Double, max: Double) = (0.45, 0.2, 1.3, 0.02, 0.12)
    public static let capEdgeInk: (lift: Double, chroma: Double) = (0.1, 0.5)
    public static let capPress: Double = 2.5
    public static let capPressShadow: Double = 0.55
    public static let capPressSpring = MetalSprings.release
    public static let capCeramic: (L: Double, C: Double) = (0.93, 0.008)
    public static let capAlone: Double = 200.0
    public static let capShadow: (blur: Double, dx: Double, dy: Double, alpha: Double) = (0.16, 0.1, 0.22, 0.36)
    public static let capSlot: (width: Double, pad: Double) = (18.0, 20.0)
    public static let detentSize: Double = 0.33
    public static let detentPitch: Double = 1.6
    public static let stopPitch: (bottom: Double, top: Double) = (0.94, 1.08)
    public static let keyRadius: Double = 0.21
    public static let keySkirtDrop: Double = 0.11
    public static let keyFace: (share: Double, radius: Double) = (0.8, 0.21)
    public static let keyFaceLift: Double = 0.062
    public static let keyGlyph: Double = 0.46
    public static let keyGlyphEdge: Double = 1.2
    public static let keyGlyphAlpha: (ink: Double, edge: Double) = (0.5, 0.85)
    public static let keyShadow: (blur: Double, dx: Double, dy: Double, alpha: Double) = (0.1, 0.06, 0.12, 0.34)
    public static let keyAlone: Double = 220.0
    public static let keyPress: (dy: Double, sx: Double, sy: Double) = (6.0, 1.02, 0.96)
    public static let bezelWidth: Double = 22.0
    public static let bezelOpeningRadius: Double = 0.2
    public static let bezelDepth: Double = 12.0
    public static let glassDepth: (centre: Double, rim: Double) = (0.05, 0.09)
    public static let glassRings: [Double] = [0.36, 0.68]
    public static let glassLine: (width: Double, alpha: Double) = (1.4, 0.24)
    public static let glassCross: Double = 0.14
    public static let glassRim: (width: Double, alpha: Double) = (0.07, 0.28)
    public static let glassGlare: (cx: Double, cy: Double, width: Double, height: Double, alpha: Double) = (0.36, 0.3, 0.68, 0.4, 0.4)
    public static let backlightGlow: Double = 0.5
    public static let backlightSpread: Double = 70.0
    public static let backlightSlices: Int = 14
    public static let backlightLead: (width: Double, alpha: Double) = (2.4, 0.95)
    /// A blip's hot core, a share of its radius.
    public static let backlightDot: Double = 0.35
    public static let backlightGlassLift: Double = 0.14
    public static let backlightAlpha: Double = 0.85
    public static let backlightSliceAlpha: Double = 0.75
    public static let backlightGlassChroma: Double = 1.4
    /// A gadget lamp's lens [centre, edge] per signal, sRGB components.
    public static let lampColors: [String: ((Double, Double, Double), (Double, Double, Double))] = ["off": ((0.5451, 0.5451, 0.5569), (0.2902, 0.2902, 0.302)), "live": ((0.851, 1.0, 0.9137), (0.1843, 0.7137, 0.451)), "link": ((0.8471, 0.902, 1.0), (0.1412, 0.3412, 0.949)), "waiting": ((1.0, 0.9451, 0.8118), (0.7882, 0.5412, 0.0941)), "failed": ((1.0, 0.851, 0.8235), (0.8353, 0.2235, 0.1647))]
    public static let drumPitch: Double = 36.0
    public static let drumRadius: Double = 4.0
    public static let drumGlyph: Double = 0.8
    public static let drumShade: (top: Double, bottom: Double) = (0.36, 0.44)
    public static let drumEdge: Double = 0.34
    public static let drumGlint: (at: Double, width: Double, alpha: Double) = (0.24, 0.05, 0.28)
    public static let drumAlone: Double = 150.0
    public static let needleWidth: (base: Double, tip: Double) = (7.0, 2.4)
    public static let needleTail: Double = 0.16
    public static let needleShadow: (blur: Double, dx: Double, dy: Double, alpha: Double) = (1.6, 3.0, 5.0, 0.3)
    public static let needleCap: Double = 13.0
    public static let needleScale: (inner: Double, outer: Double, major: Double) = (0.9, 1.02, 0.84)
    public static let needleMajor: Int = 2
    public static let needleLine: (width: Double, alpha: Double) = (2.4, 0.6)
    public static let needleZone: (inner: Double, outer: Double, alpha: Double) = (0.88, 1.03, 0.5)
    public static let needleMajorWidth: Double = 1.3
    public static let needleCrown: Double = 0.14
    public static let needleCapShadow: Double = 0.4
    public static let cellRadius: Double = 0.23
    public static let cellDrop: Double = 0.05
    public static let cellDepth: (share: Double, alpha: Double) = (0.4, 0.1)
    public static let cellLit: (lift: Double, chroma: Double, turn: Double) = (0.1, 1.25, 14.0)
    public static let cellCore: (share: Double, lift: Double, turn: Double, chroma: Double) = (0.4, 0.2, 34.0, 0.95)
    public static let cellHalo: (blur: Double, alpha: Double) = (0.32, 0.5)
    public static let cellShadow: (blur: Double, dx: Double, dy: Double, alpha: Double) = (0.09, 0.04, 0.1, 0.3)
    public static let cellBacklight: (empty: Double, full: Double) = (0.08, 0.92)
    public static let cellDye: Double = 0.13
    public static let cellAlone: (side: Double, gap: Double) = (64.0, 10.0)
    public static let rigPitch: Double = 440.0
    public static let rigPadding: Double = 40.0
    public static let rigRadius: Double = 91.0
    public static let rigTray: Double = 8.0
    public static let rigJack: Double = 40.0
    public static let rigGap: Double = 28.0
    public static let rigTop: Double = 110.0
    public static let rigSpacing: Double = 52.0
    public static let rigSlack: Double = 120.0
    public static let rigTravel: Double = 260.0
    public static let rigBead: (radius: Double, alpha: Double) = (7.0, 0.95)
    public static let rigVoices: Int = 3
    /// Each Part's footprint on the canvas, units: [width, height].
    public static let partSizes: [String: (Double, Double)] = ["slab": (320.0, 320.0), "bezel": (320.0, 320.0), "glass-face": (276.0, 276.0), "backlight": (200.0, 200.0), "led": (22.0, 22.0), "key": (112.0, 112.0), "cap": (60.0, 44.0), "jack": (68.0, 68.0), "plug": (54.0, 54.0), "cable": (0.0, 0.0), "cell": (44.0, 44.0), "drum": (52.0, 88.0), "needle": (96.0, 8.0), "lid": (240.0, 160.0), "pull": (96.0, 14.0), "lens": (184.0, 184.0), "nib": (70.0, 20.0), "beeper": (44.0, 24.0), "label": (80.0, 16.0), "glyph": (24.0, 24.0)]
    public static let jackKnurlWidth: Double = 0.07
    public static let jackKnurlAlpha: Double = 0.22
    public static let jackGlow: Double = 0.8
    /// The jack's nut on the 400-unit canvas when a Part is drawn alone.
    public static let jackNut: Double = 260.0
    public static let holeFloorDrop: Double = 0.16
    public static let holeFloorDepthDrop: Double = 0.2
    public static let holeFloorChroma: Double = 0.7
    public static let holeLip: Double = 1.0
    public static let holeLipAlpha: Double = 0.5
    public static let trayRadius: Double = 20.0
    /// Default depth per cut kind, in units.
    public static let cutDepths: [String: Double] = ["slot": 14.0, "hole": 18.0, "tray": 10.0, "well": 6.0]
    public static let glossElevation: Double = 52.0
    public static let litGain: Double = 1.01
    /// The shadow colour, sRGB components.
    public static let shadowColor: (red: Double, green: Double, blue: Double) = (0.1686, 0.1529, 0.1373)
    public static let grainLitGain: Double = 3.0
    public static let fleckGain: Double = 22.0
    public static let fleckCut: Double = -15.6
    public static let fleckScale: Double = 0.45
    public static let fleckMax: Double = 0.75
    public static let fleckUniformCut: Double = 0.985
    public static let scatter: (Double, Double) = (0.3, 0.7)
}
