// Generated by scripts/build-gadgets.mjs from tokens/tokens.json (gadgets). Do not edit.
// The visual foundations of gadgets; MetalSoundMaterial carries the acoustic recipes (same cases).

extension MetalSoundMaterial {
    /// The finish of a body cut from this material: how the one light shades it.
    public var finish: MetalGadgetFinish {
        switch self {
        case .clay:
            return MetalGadgetFinish(
                lightness: (0.55, 0.88), chromaCap: 0.1, bevel: 6.0, surfaceScale: 5.0,
                diffuse: 1.12, glossExponent: 0.0, glossStrength: 0.0,
                grainFrequency: 1.1, grainAmplitude: 0.025, grainDirectional: false,
                flecks: 0.5, translucency: 0.0,
                cast: MetalGadgetShadow(blur: 16.0, dx: 6.0, dy: 18.0, alpha: 0.24), contact: MetalGadgetShadow(blur: 3.0, dx: 1.0, dy: 4.0, alpha: 0.14),
                sampleHue: 80.0, strikeTravel: 1.0, strikeSquash: 0.008
            )
        case .ceramic:
            return MetalGadgetFinish(
                lightness: (0.8, 0.92), chromaCap: 0.12, bevel: 5.0, surfaceScale: 4.0,
                diffuse: 1.1, glossExponent: 40.0, glossStrength: 0.35,
                grainFrequency: 0.6, grainAmplitude: 0.008, grainDirectional: false,
                flecks: 0.0, translucency: 0.05,
                cast: MetalGadgetShadow(blur: 14.0, dx: 6.0, dy: 16.0, alpha: 0.22), contact: MetalGadgetShadow(blur: 3.0, dx: 1.0, dy: 4.0, alpha: 0.14),
                sampleHue: 330.0, strikeTravel: 0.5, strikeSquash: 0.0
            )
        case .resin:
            return MetalGadgetFinish(
                lightness: (0.7, 0.9), chromaCap: 0.2, bevel: 7.0, surfaceScale: 5.0,
                diffuse: 1.08, glossExponent: 24.0, glossStrength: 0.25,
                grainFrequency: 0.9, grainAmplitude: 0.012, grainDirectional: false,
                flecks: 0.3, translucency: 0.6,
                cast: MetalGadgetShadow(blur: 14.0, dx: 6.0, dy: 16.0, alpha: 0.2), contact: MetalGadgetShadow(blur: 3.0, dx: 1.0, dy: 4.0, alpha: 0.12),
                sampleHue: 55.0, strikeTravel: 0.75, strikeSquash: 0.0
            )
        case .stone:
            return MetalGadgetFinish(
                lightness: (0.45, 0.75), chromaCap: 0.05, bevel: 8.0, surfaceScale: 6.0,
                diffuse: 1.14, glossExponent: 6.0, glossStrength: 0.08,
                grainFrequency: 1.6, grainAmplitude: 0.04, grainDirectional: false,
                flecks: 1.2, translucency: 0.0,
                cast: MetalGadgetShadow(blur: 18.0, dx: 6.0, dy: 20.0, alpha: 0.28), contact: MetalGadgetShadow(blur: 3.0, dx: 1.0, dy: 4.0, alpha: 0.16),
                sampleHue: 195.0, strikeTravel: 0.5, strikeSquash: 0.0
            )
        case .glass:
            return MetalGadgetFinish(
                lightness: (0.22, 0.45), chromaCap: 0.06, bevel: 3.0, surfaceScale: 3.0,
                diffuse: 1.0, glossExponent: 80.0, glossStrength: 0.6,
                grainFrequency: 0.0, grainAmplitude: 0.0, grainDirectional: false,
                flecks: 0.0, translucency: 0.8,
                cast: MetalGadgetShadow(blur: 12.0, dx: 5.0, dy: 14.0, alpha: 0.24), contact: MetalGadgetShadow(blur: 2.0, dx: 1.0, dy: 3.0, alpha: 0.18),
                sampleHue: 260.0, strikeTravel: 0.25, strikeSquash: 0.0
            )
        case .metal:
            return MetalGadgetFinish(
                lightness: (0.4, 0.8), chromaCap: 0.08, bevel: 4.0, surfaceScale: 4.0,
                diffuse: 1.05, glossExponent: 60.0, glossStrength: 0.5,
                grainFrequency: 2.4, grainAmplitude: 0.02, grainDirectional: true,
                flecks: 0.0, translucency: 0.0,
                cast: MetalGadgetShadow(blur: 12.0, dx: 5.0, dy: 14.0, alpha: 0.26), contact: MetalGadgetShadow(blur: 2.0, dx: 1.0, dy: 3.0, alpha: 0.18),
                sampleHue: 230.0, strikeTravel: 0.25, strikeSquash: 0.0
            )
        case .rubber:
            return MetalGadgetFinish(
                lightness: (0.22, 0.4), chromaCap: 0.03, bevel: 9.0, surfaceScale: 6.0,
                diffuse: 1.15, glossExponent: 0.0, glossStrength: 0.0,
                grainFrequency: 1.3, grainAmplitude: 0.03, grainDirectional: false,
                flecks: 0.0, translucency: 0.0,
                cast: MetalGadgetShadow(blur: 20.0, dx: 6.0, dy: 22.0, alpha: 0.32), contact: MetalGadgetShadow(blur: 4.0, dx: 1.0, dy: 5.0, alpha: 0.18),
                sampleHue: 25.0, strikeTravel: 2.0, strikeSquash: 0.03
            )
        }
    }
}

/// The gadget foundations that are not per material.
public enum MetalGadgetTokens {
    public static let canvas: Double = 400.0
    public static let bodyRect: (x: Double, y: Double, width: Double, height: Double) = (40.0, 36.0, 320.0, 320.0)
    public static let bodyRadius: Double = 76.0
    public static let lightAzimuth: Double = 225.0
    public static let lightElevation: Double = 62.0
    public static let partBevel: Double = 0.55
    public static let partShadow: Double = 0.6
    public static let holeBlur: Double = 4.0
    public static let holeOffset: (dx: Double, dy: Double) = (3.0, 6.0)
    public static let holeAlpha: Double = 0.55
    public static let tierFull: Double = 96.0
    public static let tierLite: Double = 48.0
    public static let liteBevel: Double = 0.6
    public static let graphiteShadow: Double = 1.35
    public static let graphiteBrightDrop: Double = 0.04
    public static let graphiteBrightAbove: Double = 0.84
    public static let contrastShadow: Double = 1.2
    public static let glintAbove: Double = 0.2
    public static let glintMs: Double = 420.0
    public static let glossElevation: Double = 52.0
    public static let litGain: Double = 1.01
    /// The shadow colour, sRGB components.
    public static let shadowColor: (red: Double, green: Double, blue: Double) = (0.1686, 0.1529, 0.1373)
    public static let grainLitGain: Double = 3.0
    public static let fleckGain: Double = 22.0
    public static let fleckCut: Double = -15.6
    public static let fleckScale: Double = 0.45
    public static let fleckMax: Double = 0.75
    public static let fleckUniformCut: Double = 0.985
    public static let scatter: (Double, Double) = (0.3, 0.7)
}
