// Generated by scripts/build-tokens.mjs from tokens/tokens.json (status.gestures). Do not edit.
// The same keyframes the web plays as @keyframes mu-led-*.

/// How a lamp behaves over time.
public enum MetalLampGesture: String, CaseIterable, Sendable {
    case steady
    case flicker
    case breathe
    case blink2
    case rise

    /// Seconds for one run (0: holds).
    public var duration: Double { switch self { case .steady: return 0.0; case .flicker: return 0.8; case .breathe: return 2.4; case .blink2: return 0.46; case .rise: return 1.2 } }
    public var loops: Bool { switch self { case .steady: return false; case .flicker: return false; case .breathe: return true; case .blink2: return false; case .rise: return false } }
    /// (progress 0–1, level 0–1)
    public var keys: [(Double, Double)] { switch self { case .steady: return [(0.0, 1.0), (1.0, 1.0)]; case .flicker: return [(0.0, 0.78), (0.1, 1.0), (0.22, 0.5), (0.34, 1.0), (0.46, 0.62), (0.6, 1.0), (1.0, 1.0)]; case .breathe: return [(0.0, 0.55), (0.5, 1.0), (1.0, 0.55)]; case .blink2: return [(0.0, 1.0), (0.19, 1.0), (0.2, 0.25), (0.5, 0.25), (0.51, 1.0), (0.7, 1.0), (0.71, 0.25), (0.99, 0.25), (1.0, 1.0)]; case .rise: return [(0.0, 0.0), (1.0, 1.0)] } }
    /// Eased in and out between keys (breathe, rise), or linear.
    public var eased: Bool { switch self { case .steady: return false; case .flicker: return false; case .breathe: return true; case .blink2: return false; case .rise: return true } }
}

public enum MetalLampDim {
    public static let brightness: Double = 0.38
    public static let saturate: Double = 0.55
}
