// Generated by scripts/build-gadgets.mjs from packages/metalui/gadgets/src/mechanisms. Do not edit.
// The same tracks and cues the web player runs (mechanisms.generated.ts).

extension MetalMechanism {
    /// The plug lifts, its shadow opens, and it seats again with a click.
    public static let seat = MetalMechanism(
        name: "seat", momentary: true, duration: 910.0, spring: .part,
        tracks: [
            .init(part: "plug", frames: [.init(at: 0.0, pose: .init(x: 0.0, y: 0.0, r: 0.0, sx: 1.0, sy: 1.0), opacity: nil, ease: (0.55, 0.0, 0.85, 0.45)), .init(at: 140.0, pose: .init(x: 0.0, y: -14.0, r: 0.0, sx: 1.04, sy: 1.04), opacity: nil, ease: (0.4, 0.0, 0.2, 1.0)), .init(at: 300.0, pose: .init(x: 0.0, y: -14.0, r: 0.0, sx: 1.04, sy: 1.04), opacity: nil, ease: (0.16, 0.75, 0.3, 0.95)), .init(at: 605.0, pose: .init(x: 0.0, y: 1.2189, r: 0.0, sx: 0.9965, sy: 0.9965), opacity: nil, ease: (0.37, 0.0, 0.63, 1.0)), .init(at: 910.0, pose: .init(x: 0.0, y: 0.0, r: 0.0, sx: 1.0, sy: 1.0), opacity: nil, ease: (0.0, 0.0, 1.0, 1.0))]),
            .init(part: "plug.shadow", frames: [.init(at: 0.0, pose: .init(x: 0.0, y: 0.0, r: 0.0, sx: 1.0, sy: 1.0), opacity: 1.0, ease: (0.0, 0.0, 1.0, 1.0)), .init(at: 140.0, pose: .init(x: 6.0, y: 10.0, r: 0.0, sx: 1.25, sy: 1.25), opacity: 0.55, ease: (0.0, 0.0, 1.0, 1.0)), .init(at: 300.0, pose: .init(x: 6.0, y: 10.0, r: 0.0, sx: 1.25, sy: 1.25), opacity: 0.55, ease: (0.0, 0.0, 1.0, 1.0)), .init(at: 517.0, pose: .init(x: 0.0, y: 0.0, r: 0.0, sx: 1.0, sy: 1.0), opacity: 1.0, ease: (0.0, 0.0, 1.0, 1.0)), .init(at: 910.0, pose: .init(x: 0.0, y: 0.0, r: 0.0, sx: 1.0, sy: 1.0), opacity: 1.0, ease: (0.0, 0.0, 1.0, 1.0))])
        ],
        cues: [.init(at: 120.0, until: nil, kind: .strike, slot: "plug", level: 0.2, pitch: 0.8, gesture: nil), .init(at: 517.0, until: nil, kind: .strike, slot: "plug", level: 0.85, pitch: 1.0, gesture: nil), .init(at: 517.0, until: nil, kind: .lamp, slot: nil, level: 1.0, pitch: 1.0, gesture: .flicker), .init(at: 537.0, until: nil, kind: .beep, slot: nil, level: 1.0, pitch: 1.0, gesture: nil)],
        states: ["half": .init(hold: "plug", pose: .init(x: 0.0, y: -7.0, r: 0.0, sx: 1.0, sy: 1.0)), "out": .init(hold: "plug", pose: .init(x: -22.0, y: -46.0, r: -14.0, sx: 1.0, sy: 1.0))],
        reduced: ["lamp", "sound"]
    )

    public static let all: [MetalMechanism] = [seat]
}
