// Generated by scripts/build-gadgets.mjs from tokens/tokens.json (gadgets.feel, .jobs, .accent, .set). Do not edit.
// The feel model the Swift resolver runs; resolve.ts runs the same numbers.

/// What a gadget means: a closed list of verbs.
public enum MetalGadgetJob: String, CaseIterable, Sendable {
    case tune
    case command
    case link
    case keep
    case identify
    case destroy
    case take
    case find
    case make
    case signal

    /// Hue stations: a job owns its hues, so jobs never share one.
    public var stations: [Double] { switch self { case .tune: return [80.0]; case .command: return [95.0]; case .link: return [195.0, 230.0]; case .keep: return [140.0, 300.0]; case .identify: return [260.0]; case .destroy: return [25.0]; case .take: return [55.0]; case .find: return [220.0]; case .make: return [330.0]; case .signal: return [55.0, 80.0] } }
    public var reach: MetalSoundReach { switch self { case .tune: return .own; case .command: return .own; case .link: return .world; case .keep: return .own; case .identify: return .others; case .destroy: return .own; case .take: return .world; case .find: return .world; case .make: return .own; case .signal: return .own } }
    public var containers: [String] { switch self { case .tune: return ["slab"]; case .command: return ["slab"]; case .link: return ["slab", "free"]; case .keep: return ["slab", "inset"]; case .identify: return ["inset"]; case .destroy: return ["slab"]; case .take: return ["inset"]; case .find: return ["inset"]; case .make: return ["slab", "free"]; case .signal: return ["slab", "inset", "free"] } }
    public var pin: MetalSoundMaterial? { switch self { case .tune: return nil; case .command: return .ceramic; case .link: return nil; case .keep: return nil; case .identify: return .glass; case .destroy: return nil; case .take: return nil; case .find: return .stone; case .make: return nil; case .signal: return nil } }
    public var bodyChromaMax: Double? { switch self { case .tune: return 0.025; case .command: return nil; case .link: return nil; case .keep: return nil; case .identify: return nil; case .destroy: return 0.02; case .take: return nil; case .find: return nil; case .make: return nil; case .signal: return nil } }
}

public enum MetalGadgetFeelTokens {
    public static let lightness = (base: 0.88, weight: -0.56, valence: 0.05)
    public static let chroma = (base: 0.015, arousal: 0.2, mix: (0.6, 0.4))
    public static let hue = (valence: 12.0, weight: -8.0)
    /// First match wins. Each term: (axis, at least?, threshold).
    public static let materialRules: [(rule: String, terms: [(MetalGadgetAxis, Bool, Double)], material: MetalSoundMaterial)] = [
        (rule: "w>=0.8&v<=0.4", terms: [(.w, true, 0.8), (.v, false, 0.4)], material: .rubber),
        (rule: "w>=0.8", terms: [(.w, true, 0.8)], material: .glass),
        (rule: "w>=0.5&a>=0.6", terms: [(.w, true, 0.5), (.a, true, 0.6)], material: .metal),
        (rule: "w>=0.5", terms: [(.w, true, 0.5)], material: .stone),
        (rule: "a>=0.6", terms: [(.a, true, 0.6)], material: .resin),
        (rule: "v>=0.7&w<=0.3", terms: [(.v, true, 0.7), (.w, false, 0.3)], material: .ceramic),
        (rule: "*", terms: [], material: .clay)
    ]
    public static let registerThresholds: (Double, Double) = (0.33, 0.66)
    public static let registerMidi: (Int, Int, Int) = (84, 72, 60)
    public static let accentWarm: (L: Double, C: Double, H: Double) = (0.72, 0.19, 45.0)
    public static let accentCool: (L: Double, C: Double, H: Double) = (0.75, 0.13, 235.0)
    public static let accentFlipWithin: Double = 40.0
    public static let accentFlipMinChroma: Double = 0.04
    public static let accentMinChroma: Double = 0.13
    public static let setHueGap: Double = 30.0
    public static let setBands: (Double, Double) = (0.78, 0.5)
    public static let setDeltaE: Double = 0.08
    public static let setCvdDeltaE: Double = 0.06
    public static let setSlabRun: Int = 3
}
