// Generated by scripts/build-tokens.mjs from tokens/tokens.json (foundations). Do not edit.
// The same ladders the CSS reads: FOUNDATIONS.md §1–7.

/// The radius ladder in points. Nest a radius inside another by subtracting `nest`.
public enum MetalRadius {
    public static let key: Double = 6.0
    public static let row: Double = 12.0
    public static let plate: Double = 18.0
    public static let card: Double = 24.0
    public static let hero: Double = 30.0
    public static let device: Double = 36.0
    public static let pill: Double = 999.0
    /// The inset between a radius and the one nested inside it.
    public static let nest: Double = 6.0
}

/// The spacing ladder in points (4 pt base, with 2 and 6 for tight optics).
public enum MetalSpace {
    public static let steps: [Double] = [0.0, 2.0, 4.0, 6.0, 8.0, 12.0, 16.0, 20.0, 24.0, 32.0, 40.0, 48.0, 64.0, 80.0]
    public static let s0: Double = 0.0
    public static let s2: Double = 2.0
    public static let s4: Double = 4.0
    public static let s6: Double = 6.0
    public static let s8: Double = 8.0
    public static let s12: Double = 12.0
    public static let s16: Double = 16.0
    public static let s20: Double = 20.0
    public static let s24: Double = 24.0
    public static let s32: Double = 32.0
    public static let s40: Double = 40.0
    public static let s48: Double = 48.0
    public static let s64: Double = 64.0
    public static let s80: Double = 80.0
}

/// Control heights in points.
public enum MetalHeight {
    public static let steps: [Double] = [20.0, 24.0, 28.0, 32.0, 36.0, 40.0, 44.0]
    public static let h20: Double = 20.0
    public static let h24: Double = 24.0
    public static let h28: Double = 28.0
    public static let h32: Double = 32.0
    public static let h36: Double = 36.0
    public static let h40: Double = 40.0
    public static let h44: Double = 44.0
}

/// Icon size by the height of the control that holds it.
public enum MetalIconSize {
    public static let byControlHeight: [Double: Double] = [20.0: 12.0, 24.0: 12.0, 28.0: 14.0, 32.0: 14.0, 36.0: 16.0, 40.0: 16.0, 44.0: 20.0]

    /// The icon size for a control height; heights between steps take the step below.
    public static func forControl(height: Double) -> Double {
        let keys = byControlHeight.keys.sorted()
        let step = keys.last(where: { $0 <= height }) ?? keys[0]
        return byControlHeight[step]!
    }
}

/// Focus and selection rings in points.
public enum MetalRing {
    public static let focusOffset: Double = 2.0
    public static let focusWidth: Double = 2.0
    public static let selectOffset: Double = 6.0
}

/// The type roles: the only sizes, weights and trackings components use.
public enum MetalType {
    /// 18/24 · 600
    public static let display = MetalTypeRole(
        name: "display", family: .sans, size: 18.0, line: 24.0, weight: 600,
        tracking: -0.022, stretch: 1.0, uppercase: false, tabular: false, maxSize: nil
    )
    /// 15/20 · 500
    public static let content = MetalTypeRole(
        name: "content", family: .sans, size: 15.0, line: 20.0, weight: 500,
        tracking: -0.012, stretch: 1.0, uppercase: false, tabular: false, maxSize: nil
    )
    /// 13.5/18 · 600
    public static let title = MetalTypeRole(
        name: "title", family: .sans, size: 13.5, line: 18.0, weight: 600,
        tracking: -0.01, stretch: 1.0, uppercase: false, tabular: false, maxSize: nil
    )
    /// 13.5/20 · 500
    public static let lead = MetalTypeRole(
        name: "lead", family: .sans, size: 13.5, line: 20.0, weight: 500,
        tracking: -0.01, stretch: 1.0, uppercase: false, tabular: false, maxSize: nil
    )
    /// 12.5/16 · 500
    public static let ui = MetalTypeRole(
        name: "ui", family: .sans, size: 12.5, line: 16.0, weight: 500,
        tracking: -0.005, stretch: 1.0, uppercase: false, tabular: false, maxSize: nil
    )
    /// 12.5/18 · 400
    public static let body = MetalTypeRole(
        name: "body", family: .sans, size: 12.5, line: 18.0, weight: 400,
        tracking: -0.005, stretch: 1.0, uppercase: false, tabular: false, maxSize: nil
    )
    /// 11/14 · 400
    public static let meta = MetalTypeRole(
        name: "meta", family: .sans, size: 11.0, line: 14.0, weight: 400,
        tracking: 0.0, stretch: 1.0, uppercase: false, tabular: false, maxSize: nil
    )
    /// 9/12 · 400 · scales with the host's text size up to 11 pt
    public static let label = MetalTypeRole(
        name: "label", family: .mono, size: 9.0, line: 12.0, weight: 400,
        tracking: 0.11, stretch: 1.0, uppercase: true, tabular: false, maxSize: 11.0
    )
    /// 10.5/14 · 500
    public static let readout = MetalTypeRole(
        name: "readout", family: .mono, size: 10.5, line: 14.0, weight: 500,
        tracking: 0.02, stretch: 1.0, uppercase: false, tabular: true, maxSize: nil
    )
    /// 10.5/17 · 400
    public static let code = MetalTypeRole(
        name: "code", family: .mono, size: 10.5, line: 17.0, weight: 400,
        tracking: 0.0, stretch: 1.0, uppercase: false, tabular: false, maxSize: nil
    )
    /// 40/44 · 700
    public static let pixel = MetalTypeRole(
        name: "pixel", family: .pixel, size: 40.0, line: 44.0, weight: 700,
        tracking: 0.0, stretch: 1.0, uppercase: false, tabular: false, maxSize: nil
    )

    public static let all: [MetalTypeRole] = [display, content, title, lead, ui, body, meta, label, readout, code, pixel]
}
