// Generated by scripts/build-tokens.mjs from tokens/tokens.json. Do not edit.
// Values are the approved Soft Hardware object sheet (Rev B); the CSS twin is components/tokens.css.

/// Every value one colorway supplies. Mirrors the `--mu-*` colorway custom properties.
public struct MetalColorwayTokens: Sendable {
    public let sHi: MetalRGBA
    public let s: MetalRGBA
    public let sLo: MetalRGBA
    public let wellTop: MetalRGBA
    public let wellBot: MetalRGBA
    public let ink: MetalRGBA
    public let ink2: MetalRGBA
    public let ink3: MetalRGBA
    public let icon: MetalRGBA
    public let engrave: MetalRGBA
    public let lip: MetalRGBA
    public let rule: MetalRGBA
    public let ruleLip: MetalRGBA
    public let thumbHi: MetalRGBA
    public let thumbLo: MetalRGBA
    public let frost: MetalRGBA
    public let frostStrong: MetalRGBA
    public let raise: [MetalShadow]
    public let raiseSm: [MetalShadow]
    public let well: [MetalShadow]
    public let capBg: MetalGradient
    public let capSh: [MetalShadow]
    public let btnBg: MetalGradient
    public let btnSh: [MetalShadow]
    public let pressedBg: MetalGradient
    public let pressedSh: [MetalShadow]
    public let duoK: Double
}

/// A signal cap (primary, destructive) that looks the same in both colorways.
public struct MetalCapTokens: Sendable {
    public let bg: MetalGradient
    public let sh: [MetalShadow]
    public let pressedBg: MetalGradient
    public let pressedSh: [MetalShadow]
    public let ink: MetalRGBA
}

public enum MetalTokens {
    public static let bone = MetalColorwayTokens(
        sHi: MetalRGBA(252, 251, 249, 1.0),
        s: MetalRGBA(246, 245, 242, 1.0),
        sLo: MetalRGBA(240, 239, 235, 1.0),
        wellTop: MetalRGBA(230, 229, 225, 1.0),
        wellBot: MetalRGBA(236, 235, 231, 1.0),
        ink: MetalRGBA(27, 27, 29, 1.0),
        ink2: MetalRGBA(92, 92, 96, 1.0),
        ink3: MetalRGBA(154, 154, 157, 1.0),
        icon: MetalRGBA(58, 58, 61, 1.0),
        engrave: MetalRGBA(40, 38, 32, 0.46),
        lip: MetalRGBA(255, 255, 255, 0.55),
        rule: MetalRGBA(0, 0, 0, 0.06),
        ruleLip: MetalRGBA(255, 255, 255, 0.5),
        thumbHi: MetalRGBA(255, 255, 255, 1.0),
        thumbLo: MetalRGBA(247, 246, 243, 1.0),
        frost: MetalRGBA(250, 249, 246, 0.68),
        frostStrong: MetalRGBA(251, 250, 248, 0.8),
        raise: [
            MetalShadow(inset: true, x: 0.0, y: 0.0, blur: 6.0, spread: 2.0, color: MetalRGBA(255, 255, 255, 0.75)),
            MetalShadow(inset: true, x: 2.0, y: 3.0, blur: 3.0, spread: -1.0, color: MetalRGBA(255, 255, 255, 0.95)),
            MetalShadow(inset: true, x: -1.0, y: -3.0, blur: 5.0, spread: -2.0, color: MetalRGBA(110, 100, 80, 0.07)),
            MetalShadow(inset: false, x: 0.0, y: 0.0, blur: 0.0, spread: 0.5, color: MetalRGBA(24, 22, 16, 0.045)),
            MetalShadow(inset: false, x: 0.0, y: 1.0, blur: 2.0, spread: 0.0, color: MetalRGBA(24, 22, 16, 0.05)),
            MetalShadow(inset: false, x: 0.0, y: 8.0, blur: 18.0, spread: -6.0, color: MetalRGBA(24, 22, 16, 0.08)),
            MetalShadow(inset: false, x: 0.0, y: 26.0, blur: 50.0, spread: -16.0, color: MetalRGBA(24, 22, 16, 0.13)),
            MetalShadow(inset: false, x: 0.0, y: 52.0, blur: 96.0, spread: -36.0, color: MetalRGBA(24, 22, 16, 0.13)),
        ],
        raiseSm: [
            MetalShadow(inset: true, x: 0.0, y: 0.0, blur: 4.0, spread: 1.0, color: MetalRGBA(255, 255, 255, 0.85)),
            MetalShadow(inset: true, x: 1.0, y: 2.0, blur: 2.0, spread: -1.0, color: MetalRGBA(255, 255, 255, 1.0)),
            MetalShadow(inset: false, x: 0.0, y: 0.0, blur: 0.0, spread: 0.5, color: MetalRGBA(24, 22, 16, 0.05)),
            MetalShadow(inset: false, x: 0.0, y: 1.0, blur: 2.0, spread: 0.0, color: MetalRGBA(24, 22, 16, 0.07)),
            MetalShadow(inset: false, x: 0.0, y: 5.0, blur: 12.0, spread: -4.0, color: MetalRGBA(24, 22, 16, 0.09)),
        ],
        well: [
            MetalShadow(inset: true, x: 0.0, y: 2.0, blur: 6.0, spread: -1.0, color: MetalRGBA(60, 55, 40, 0.1)),
            MetalShadow(inset: true, x: 0.0, y: 0.0, blur: 0.0, spread: 0.5, color: MetalRGBA(0, 0, 0, 0.03)),
            MetalShadow(inset: true, x: 0.0, y: -2.0, blur: 4.0, spread: -2.0, color: MetalRGBA(255, 255, 255, 0.95)),
        ],
        capBg: MetalGradient(angle: 180.0, stops: [.init(MetalRGBA(255, 255, 255, 1.0), 0.0), .init(MetalRGBA(245, 244, 241, 1.0), 1.0)]),
        capSh: [
            MetalShadow(inset: true, x: 0.0, y: 0.0, blur: 3.0, spread: 1.0, color: MetalRGBA(255, 255, 255, 0.9)),
            MetalShadow(inset: false, x: 0.0, y: 0.0, blur: 0.0, spread: 0.5, color: MetalRGBA(0, 0, 0, 0.07)),
            MetalShadow(inset: false, x: 0.0, y: 1.0, blur: 2.0, spread: 0.0, color: MetalRGBA(0, 0, 0, 0.07)),
        ],
        btnBg: MetalGradient(angle: 180.0, stops: [.init(MetalRGBA(255, 255, 255, 1.0), 0.0), .init(MetalRGBA(244, 243, 240, 1.0), 1.0)]),
        btnSh: [
            MetalShadow(inset: true, x: 0.0, y: 0.0, blur: 4.0, spread: 1.0, color: MetalRGBA(255, 255, 255, 0.9)),
            MetalShadow(inset: true, x: 1.0, y: 2.0, blur: 2.0, spread: -1.0, color: MetalRGBA(255, 255, 255, 1.0)),
            MetalShadow(inset: false, x: 0.0, y: 0.0, blur: 0.0, spread: 0.5, color: MetalRGBA(0, 0, 0, 0.06)),
            MetalShadow(inset: false, x: 0.0, y: 1.0, blur: 2.0, spread: 0.0, color: MetalRGBA(0, 0, 0, 0.06)),
            MetalShadow(inset: false, x: 0.0, y: 4.0, blur: 9.0, spread: -3.0, color: MetalRGBA(0, 0, 0, 0.08)),
        ],
        pressedBg: MetalGradient(angle: 180.0, stops: [.init(MetalRGBA(233, 232, 228, 1.0), 0.0), .init(MetalRGBA(239, 238, 234, 1.0), 1.0)]),
        pressedSh: [
            MetalShadow(inset: true, x: 0.0, y: 2.0, blur: 5.0, spread: -1.0, color: MetalRGBA(60, 55, 40, 0.14)),
            MetalShadow(inset: true, x: 0.0, y: 0.0, blur: 0.0, spread: 0.5, color: MetalRGBA(0, 0, 0, 0.035)),
            MetalShadow(inset: true, x: 0.0, y: -2.0, blur: 3.0, spread: -2.0, color: MetalRGBA(255, 255, 255, 0.9)),
        ],
        duoK: 1.0
    )

    public static let graphite = MetalColorwayTokens(
        sHi: MetalRGBA(44, 44, 47, 1.0),
        s: MetalRGBA(37, 37, 39, 1.0),
        sLo: MetalRGBA(32, 32, 34, 1.0),
        wellTop: MetalRGBA(20, 20, 21, 1.0),
        wellBot: MetalRGBA(24, 24, 26, 1.0),
        ink: MetalRGBA(242, 242, 240, 1.0),
        ink2: MetalRGBA(166, 166, 169, 1.0),
        ink3: MetalRGBA(110, 110, 114, 1.0),
        icon: MetalRGBA(214, 214, 216, 1.0),
        engrave: MetalRGBA(255, 255, 255, 0.34),
        lip: MetalRGBA(0, 0, 0, 0.35),
        rule: MetalRGBA(0, 0, 0, 0.45),
        ruleLip: MetalRGBA(255, 255, 255, 0.035),
        thumbHi: MetalRGBA(58, 58, 61, 1.0),
        thumbLo: MetalRGBA(46, 46, 49, 1.0),
        frost: MetalRGBA(36, 36, 39, 0.66),
        frostStrong: MetalRGBA(34, 34, 37, 0.78),
        raise: [
            MetalShadow(inset: true, x: 0.0, y: 0.0, blur: 6.0, spread: 2.0, color: MetalRGBA(255, 255, 255, 0.055)),
            MetalShadow(inset: true, x: 1.5, y: 2.5, blur: 3.0, spread: -1.0, color: MetalRGBA(255, 255, 255, 0.1)),
            MetalShadow(inset: true, x: -1.0, y: -3.0, blur: 5.0, spread: -2.0, color: MetalRGBA(0, 0, 0, 0.35)),
            MetalShadow(inset: false, x: 0.0, y: 0.0, blur: 0.0, spread: 0.5, color: MetalRGBA(0, 0, 0, 0.45)),
            MetalShadow(inset: false, x: 0.0, y: 1.0, blur: 2.0, spread: 0.0, color: MetalRGBA(0, 0, 0, 0.22)),
            MetalShadow(inset: false, x: 0.0, y: 8.0, blur: 18.0, spread: -6.0, color: MetalRGBA(0, 0, 0, 0.2)),
            MetalShadow(inset: false, x: 0.0, y: 26.0, blur: 50.0, spread: -16.0, color: MetalRGBA(0, 0, 0, 0.34)),
            MetalShadow(inset: false, x: 0.0, y: 52.0, blur: 96.0, spread: -36.0, color: MetalRGBA(0, 0, 0, 0.3)),
        ],
        raiseSm: [
            MetalShadow(inset: true, x: 0.0, y: 0.0, blur: 4.0, spread: 1.0, color: MetalRGBA(255, 255, 255, 0.06)),
            MetalShadow(inset: true, x: 1.0, y: 2.0, blur: 2.0, spread: -1.0, color: MetalRGBA(255, 255, 255, 0.12)),
            MetalShadow(inset: false, x: 0.0, y: 0.0, blur: 0.0, spread: 0.5, color: MetalRGBA(0, 0, 0, 0.55)),
            MetalShadow(inset: false, x: 0.0, y: 1.0, blur: 2.0, spread: 0.0, color: MetalRGBA(0, 0, 0, 0.3)),
            MetalShadow(inset: false, x: 0.0, y: 5.0, blur: 12.0, spread: -4.0, color: MetalRGBA(0, 0, 0, 0.3)),
        ],
        well: [
            MetalShadow(inset: true, x: 0.0, y: 2.0, blur: 6.0, spread: -1.0, color: MetalRGBA(0, 0, 0, 0.6)),
            MetalShadow(inset: true, x: 0.0, y: 0.0, blur: 0.0, spread: 0.5, color: MetalRGBA(0, 0, 0, 0.35)),
            MetalShadow(inset: true, x: 0.0, y: -2.0, blur: 4.0, spread: -2.0, color: MetalRGBA(255, 255, 255, 0.05)),
        ],
        capBg: MetalGradient(angle: 180.0, stops: [.init(MetalRGBA(53, 53, 58, 1.0), 0.0), .init(MetalRGBA(42, 42, 45, 1.0), 1.0)]),
        capSh: [
            MetalShadow(inset: true, x: 0.0, y: 0.0, blur: 3.0, spread: 1.0, color: MetalRGBA(255, 255, 255, 0.06)),
            MetalShadow(inset: false, x: 0.0, y: 0.0, blur: 0.0, spread: 0.5, color: MetalRGBA(0, 0, 0, 0.6)),
            MetalShadow(inset: false, x: 0.0, y: 1.0, blur: 2.0, spread: 0.0, color: MetalRGBA(0, 0, 0, 0.3)),
        ],
        btnBg: MetalGradient(angle: 180.0, stops: [.init(MetalRGBA(49, 49, 52, 1.0), 0.0), .init(MetalRGBA(40, 40, 43, 1.0), 1.0)]),
        btnSh: [
            MetalShadow(inset: true, x: 0.0, y: 0.0, blur: 4.0, spread: 1.0, color: MetalRGBA(255, 255, 255, 0.05)),
            MetalShadow(inset: true, x: 1.0, y: 2.0, blur: 2.0, spread: -1.0, color: MetalRGBA(255, 255, 255, 0.1)),
            MetalShadow(inset: false, x: 0.0, y: 0.0, blur: 0.0, spread: 0.5, color: MetalRGBA(0, 0, 0, 0.6)),
            MetalShadow(inset: false, x: 0.0, y: 1.0, blur: 2.0, spread: 0.0, color: MetalRGBA(0, 0, 0, 0.3)),
            MetalShadow(inset: false, x: 0.0, y: 4.0, blur: 9.0, spread: -3.0, color: MetalRGBA(0, 0, 0, 0.3)),
        ],
        pressedBg: MetalGradient(angle: 180.0, stops: [.init(MetalRGBA(24, 24, 26, 1.0), 0.0), .init(MetalRGBA(28, 28, 30, 1.0), 1.0)]),
        pressedSh: [
            MetalShadow(inset: true, x: 0.0, y: 2.0, blur: 5.0, spread: -1.0, color: MetalRGBA(0, 0, 0, 0.65)),
            MetalShadow(inset: true, x: 0.0, y: 0.0, blur: 0.0, spread: 0.5, color: MetalRGBA(0, 0, 0, 0.5)),
            MetalShadow(inset: true, x: 0.0, y: -2.0, blur: 3.0, spread: -2.0, color: MetalRGBA(255, 255, 255, 0.05)),
        ],
        duoK: 1.3
    )
}

public enum MetalShared {
    public static let page: MetalRGBA = MetalRGBA(243, 243, 241, 1.0)
    public static let pageDark: MetalRGBA = MetalRGBA(14, 14, 15, 1.0)
    public static let green: MetalRGBA = MetalRGBA(120, 214, 165, 1.0)
    public static let greenDeep: MetalRGBA = MetalRGBA(63, 185, 122, 1.0)
    public static let orange: MetalRGBA = MetalRGBA(255, 107, 61, 1.0)
    public static let blue: MetalRGBA = MetalRGBA(36, 87, 242, 1.0)
    public static let red: MetalRGBA = MetalRGBA(216, 69, 59, 1.0)
    public static let gold: MetalRGBA = MetalRGBA(199, 167, 107, 1.0)
    public static let ledGreen: MetalRadialGradient = MetalRadialGradient(center: .init(x: 0.4, y: 0.35), stops: [.init(MetalRGBA(217, 255, 233, 1.0), 0.18), .init(MetalRGBA(123, 234, 174, 1.0), 0.42), .init(MetalRGBA(47, 182, 115, 1.0), 1.0)])
    public static let ledRed: MetalRadialGradient = MetalRadialGradient(center: .init(x: 0.4, y: 0.35), stops: [.init(MetalRGBA(255, 217, 210, 1.0), 0.18), .init(MetalRGBA(255, 122, 102, 1.0), 0.45), .init(MetalRGBA(213, 57, 42, 1.0), 1.0)])
    public static let ledAmber: MetalRadialGradient = MetalRadialGradient(center: .init(x: 0.4, y: 0.35), stops: [.init(MetalRGBA(255, 241, 207, 1.0), 0.18), .init(MetalRGBA(245, 191, 85, 1.0), 0.45), .init(MetalRGBA(201, 138, 24, 1.0), 1.0)])
    public static let focus: MetalRGBA = MetalRGBA(63, 185, 122, 1.0)
}

public enum MetalCaps {
    public static let primary = MetalCapTokens(
        bg: MetalGradient(angle: 180.0, stops: [.init(MetalRGBA(56, 56, 60, 1.0), 0.0), .init(MetalRGBA(37, 37, 40, 1.0), 1.0)]),
        sh: [
            MetalShadow(inset: true, x: 0.0, y: 0.0, blur: 5.0, spread: 1.0, color: MetalRGBA(255, 255, 255, 0.07)),
            MetalShadow(inset: true, x: 1.0, y: 2.0, blur: 2.0, spread: -1.0, color: MetalRGBA(255, 255, 255, 0.18)),
            MetalShadow(inset: false, x: 0.0, y: 0.0, blur: 0.0, spread: 0.5, color: MetalRGBA(0, 0, 0, 0.5)),
            MetalShadow(inset: false, x: 0.0, y: 1.0, blur: 2.0, spread: 0.0, color: MetalRGBA(0, 0, 0, 0.15)),
            MetalShadow(inset: false, x: 0.0, y: 5.0, blur: 12.0, spread: -4.0, color: MetalRGBA(0, 0, 0, 0.22)),
        ],
        pressedBg: MetalGradient(angle: 180.0, stops: [.init(MetalRGBA(28, 28, 30, 1.0), 0.0), .init(MetalRGBA(36, 36, 39, 1.0), 1.0)]),
        pressedSh: [
            MetalShadow(inset: true, x: 0.0, y: 1.0, blur: 3.0, spread: 0.0, color: MetalRGBA(0, 0, 0, 0.6)),
            MetalShadow(inset: false, x: 0.0, y: 0.0, blur: 0.0, spread: 0.5, color: MetalRGBA(0, 0, 0, 0.7)),
        ],
        ink: MetalRGBA(255, 255, 255, 1.0)
    )
    public static let destructive = MetalCapTokens(
        bg: MetalGradient(angle: 180.0, stops: [.init(MetalRGBA(230, 89, 78, 1.0), 0.0), .init(MetalRGBA(208, 67, 58, 1.0), 1.0)]),
        sh: [
            MetalShadow(inset: true, x: 0.0, y: 0.0, blur: 6.0, spread: 1.0, color: MetalRGBA(255, 255, 255, 0.14)),
            MetalShadow(inset: true, x: 1.0, y: 2.0, blur: 2.0, spread: -1.0, color: MetalRGBA(255, 255, 255, 0.32)),
            MetalShadow(inset: false, x: 0.0, y: 0.0, blur: 0.0, spread: 0.5, color: MetalRGBA(120, 20, 10, 0.3)),
            MetalShadow(inset: false, x: 0.0, y: 1.0, blur: 2.0, spread: 0.0, color: MetalRGBA(110, 10, 0, 0.14)),
            MetalShadow(inset: false, x: 0.0, y: 5.0, blur: 12.0, spread: -4.0, color: MetalRGBA(170, 30, 20, 0.24)),
        ],
        pressedBg: MetalGradient(angle: 180.0, stops: [.init(MetalRGBA(190, 53, 44, 1.0), 0.0), .init(MetalRGBA(207, 66, 56, 1.0), 1.0)]),
        pressedSh: [
            MetalShadow(inset: true, x: 0.0, y: 1.0, blur: 3.0, spread: 0.0, color: MetalRGBA(80, 0, 0, 0.45)),
            MetalShadow(inset: false, x: 0.0, y: 0.0, blur: 0.0, spread: 0.5, color: MetalRGBA(110, 10, 0, 0.55)),
        ],
        ink: MetalRGBA(255, 255, 255, 1.0)
    )
}

public enum MetalSprings {
    /// objects: cards, fan-out, hover lift
    public static let obj = MetalSpring(stiffness: 120.0, damping: 13.0, duration: 0.92)
    /// flap tilt, drawers
    public static let flap = MetalSpring(stiffness: 120.0, damping: 14.0, duration: 0.94)
    /// controls: thumbs, toggles, ticks
    public static let ui = MetalSpring(stiffness: 170.0, damping: 16.0, duration: 0.6)
    /// press release
    public static let press = MetalSpring(stiffness: 500.0, damping: 40.0, duration: 0.3)
}
