// Generated by scripts/build-icons.mjs from icons/src/life.mjs. Do not edit.
import { createLifeIcon } from './LifeIcon';

/** Breakfast. Hover: yolk wobbles. */
export const LifeBreakfastIcon = createLifeIcon("breakfast", "LifeBreakfastIcon");
/** Lunch. Hover: chopsticks dip into the bowl. */
export const LifeLunchIcon = createLifeIcon("lunch", "LifeLunchIcon");
/** Dinner. Hover: fork and knife lift off the table. */
export const LifeDinnerIcon = createLifeIcon("dinner", "LifeDinnerIcon");
/** Snack. Hover: cookie turns, a crumb falls. */
export const LifeSnackIcon = createLifeIcon("snack", "LifeSnackIcon");
/** Coffee. Hover: steam rises from the cup. */
export const LifeCoffeeIcon = createLifeIcon("coffee", "LifeCoffeeIcon");
/** Tea. Hover: pot tips to pour. */
export const LifeTeaIcon = createLifeIcon("tea", "LifeTeaIcon");
/** Water. Hover: water sloshes in the glass. */
export const LifeWaterIcon = createLifeIcon("water", "LifeWaterIcon");
/** Alcohol. Hover: glass tilts to clink. */
export const LifeAlcoholIcon = createLifeIcon("alcohol", "LifeAlcoholIcon");
/** Cooking. Hover: lid lifts, steam escapes. */
export const LifeCookingIcon = createLifeIcon("cooking", "LifeCookingIcon");
/** Takeaway. Hover: handle swings. */
export const LifeTakeawayIcon = createLifeIcon("takeaway", "LifeTakeawayIcon");
/** Fasting. Hover: hand sweeps the empty plate. */
export const LifeFastingIcon = createLifeIcon("fasting", "LifeFastingIcon");
/** Sleep. Hover: blanket rises with a breath. */
export const LifeSleepIcon = createLifeIcon("sleep", "LifeSleepIcon");
/** Nap. Hover: a z drifts up. */
export const LifeNapIcon = createLifeIcon("nap", "LifeNapIcon");
/** Woke. Hover: the alarm rings. */
export const LifeWokeIcon = createLifeIcon("woke", "LifeWokeIcon");
/** Bad night. Hover: restless line jitters. */
export const LifeBadNightIcon = createLifeIcon("bad-night", "LifeBadNightIcon");
/** Tired. Hover: last bar flickers. */
export const LifeTiredIcon = createLifeIcon("tired", "LifeTiredIcon");
/** Rested. Hover: bars charge in turn. */
export const LifeRestedIcon = createLifeIcon("rested", "LifeRestedIcon");
/** Run. Hover: the figure strides. */
export const LifeRunIcon = createLifeIcon("run", "LifeRunIcon");
/** Walk. Hover: legs swing a step. */
export const LifeWalkIcon = createLifeIcon("walk", "LifeWalkIcon");
/** Gym. Hover: dumbbell lifts. */
export const LifeGymIcon = createLifeIcon("gym", "LifeGymIcon");
/** Yoga. Hover: a slow breath lifts the figure. */
export const LifeYogaIcon = createLifeIcon("yoga", "LifeYogaIcon");
/** Cycle. Hover: bike rolls forward. */
export const LifeCycleIcon = createLifeIcon("cycle", "LifeCycleIcon");
/** Swim. Hover: water rolls under the stroke. */
export const LifeSwimIcon = createLifeIcon("swim", "LifeSwimIcon");
/** Stretch. Hover: arms reach higher. */
export const LifeStretchIcon = createLifeIcon("stretch", "LifeStretchIcon");
/** Headache. Hover: the ache flares once. */
export const LifeHeadacheIcon = createLifeIcon("headache", "LifeHeadacheIcon");
/** Sick. Hover: mercury climbs. */
export const LifeSickIcon = createLifeIcon("sick", "LifeSickIcon");
/** Medication. Hover: capsule twists open. */
export const LifeMedicationIcon = createLifeIcon("medication", "LifeMedicationIcon");
/** Doctor. Hover: chestpiece swings. */
export const LifeDoctorIcon = createLifeIcon("doctor", "LifeDoctorIcon");
/** Period. Hover: the cycle ring turns a day. */
export const LifePeriodIcon = createLifeIcon("period", "LifePeriodIcon");
/** Weight. Hover: needle settles. */
export const LifeWeightIcon = createLifeIcon("weight", "LifeWeightIcon");
/** Steps. Hover: prints step in turn. */
export const LifeStepsIcon = createLifeIcon("steps", "LifeStepsIcon");
/** Heart rate. Hover: the trace redraws. */
export const LifeHeartRateIcon = createLifeIcon("heart-rate", "LifeHeartRateIcon");
/** Sunlight. Hover: beams reach further in. */
export const LifeSunlightIcon = createLifeIcon("sunlight", "LifeSunlightIcon");
/** Calm. Hover: reflection ripples once. */
export const LifeCalmIcon = createLifeIcon("calm", "LifeCalmIcon");
/** Hopeful. Hover: dawn lifts over the line. */
export const LifeHopefulIcon = createLifeIcon("hopeful", "LifeHopefulIcon");
/** Grateful. Hover: a drop lands in the full vessel. */
export const LifeGratefulIcon = createLifeIcon("grateful", "LifeGratefulIcon");
/** Loved. Hover: the two circles draw closer. */
export const LifeLovedIcon = createLifeIcon("loved", "LifeLovedIcon");
/** Happy. Hover: the crest swells. */
export const LifeHappyIcon = createLifeIcon("happy", "LifeHappyIcon");
/** Excited. Hover: crests bounce. */
export const LifeExcitedIcon = createLifeIcon("excited", "LifeExcitedIcon");
/** Energised. Hover: the bolt pulses up. */
export const LifeEnergisedIcon = createLifeIcon("energised", "LifeEnergisedIcon");
/** Proud. Hover: the summit dot hops. */
export const LifeProudIcon = createLifeIcon("proud", "LifeProudIcon");
/** Curious. Hover: the loop turns over. */
export const LifeCuriousIcon = createLifeIcon("curious", "LifeCuriousIcon");
/** Focused. Hover: the ring tightens on the point. */
export const LifeFocusedIcon = createLifeIcon("focused", "LifeFocusedIcon");
/** Distracted. Hover: dots wander apart. */
export const LifeDistractedIcon = createLifeIcon("distracted", "LifeDistractedIcon");
/** Bored. Hover: dots trail off slowly. */
export const LifeBoredIcon = createLifeIcon("bored", "LifeBoredIcon");
/** Dull. Hover: the flat line sinks a little. */
export const LifeDullIcon = createLifeIcon("dull", "LifeDullIcon");
/** Lonely. Hover: the single dot drifts. */
export const LifeLonelyIcon = createLifeIcon("lonely", "LifeLonelyIcon");
/** Sad. Hover: the line settles lower. */
export const LifeSadIcon = createLifeIcon("sad", "LifeSadIcon");
/** Drained. Hover: the level drops. */
export const LifeDrainedIcon = createLifeIcon("drained", "LifeDrainedIcon");
/** Anxious. Hover: the jitter quickens. */
export const LifeAnxiousIcon = createLifeIcon("anxious", "LifeAnxiousIcon");
/** Angry. Hover: the zigzag sparks once. */
export const LifeAngryIcon = createLifeIcon("angry", "LifeAngryIcon");
/** Stressed. Hover: the plates squeeze the coil. */
export const LifeStressedIcon = createLifeIcon("stressed", "LifeStressedIcon");
/** Frustrated. Hover: the line pushes the wall and crumples. */
export const LifeFrustratedIcon = createLifeIcon("frustrated", "LifeFrustratedIcon");
/** Overwhelmed. Hover: the water rises and churns. */
export const LifeOverwhelmedIcon = createLifeIcon("overwhelmed", "LifeOverwhelmedIcon");
/** Meeting. Hover: heads nod in turn. */
export const LifeMeetingIcon = createLifeIcon("meeting", "LifeMeetingIcon");
/** Call. Hover: handset rings. */
export const LifeCallIcon = createLifeIcon("call", "LifeCallIcon");
/** Deep work. Hover: the cups close in. */
export const LifeDeepWorkIcon = createLifeIcon("deep-work", "LifeDeepWorkIcon");
/** Email. Hover: flap opens. */
export const LifeEmailIcon = createLifeIcon("email", "LifeEmailIcon");
/** Review. Hover: the tick redraws. */
export const LifeReviewIcon = createLifeIcon("review", "LifeReviewIcon");
/** Shipped. Hover: the arrow leaves the box. */
export const LifeShippedIcon = createLifeIcon("shipped", "LifeShippedIcon");
/** Blocked. Hover: the barrier wobbles. */
export const LifeBlockedIcon = createLifeIcon("blocked", "LifeBlockedIcon");
/** Idea. Hover: the bulb warms and glints. */
export const LifeIdeaIcon = createLifeIcon("idea", "LifeIdeaIcon");
/** Bug. Hover: legs scuttle. */
export const LifeBugIcon = createLifeIcon("bug", "LifeBugIcon");
/** Deadline. Hover: hourglass turns over. */
export const LifeDeadlineIcon = createLifeIcon("deadline", "LifeDeadlineIcon");
/** 1:1. Hover: the two bubbles lean in. */
export const LifeOneOnOneIcon = createLifeIcon("one-on-one", "LifeOneOnOneIcon");
/** Presentation. Hover: bars rise on the board. */
export const LifePresentationIcon = createLifeIcon("presentation", "LifePresentationIcon");
/** Friend. Hover: the friend leans in. */
export const LifeFriendIcon = createLifeIcon("friend", "LifeFriendIcon");
/** Family. Hover: the small one hops. */
export const LifeFamilyIcon = createLifeIcon("family", "LifeFamilyIcon");
/** Date. Hover: heart beats twice. */
export const LifeDateIcon = createLifeIcon("date", "LifeDateIcon");
/** Party. Hover: confetti pops. */
export const LifePartyIcon = createLifeIcon("party", "LifePartyIcon");
/** Message. Hover: typing dots bounce. */
export const LifeMessageIcon = createLifeIcon("message", "LifeMessageIcon");
/** Gift. Hover: lid lifts. */
export const LifeGiftIcon = createLifeIcon("gift", "LifeGiftIcon");
/** Home. Hover: the door lights up. */
export const LifeHomeIcon = createLifeIcon("home", "LifeHomeIcon");
/** Office. Hover: windows light in turn. */
export const LifeOfficeIcon = createLifeIcon("office", "LifeOfficeIcon");
/** Café. Hover: awning flutters. */
export const LifeCafeIcon = createLifeIcon("cafe", "LifeCafeIcon");
/** Commute. Hover: train pulls in, lamps blink. */
export const LifeCommuteIcon = createLifeIcon("commute", "LifeCommuteIcon");
/** Travel. Hover: suitcase tips onto its wheels. */
export const LifeTravelIcon = createLifeIcon("travel", "LifeTravelIcon");
/** Flight. Hover: plane climbs. */
export const LifeFlightIcon = createLifeIcon("flight", "LifeFlightIcon");
/** Outdoors. Hover: trees sway. */
export const LifeOutdoorsIcon = createLifeIcon("outdoors", "LifeOutdoorsIcon");
/** Errands. Hover: the route runs to the pin. */
export const LifeErrandsIcon = createLifeIcon("errands", "LifeErrandsIcon");
/** Groceries. Hover: greens pop up. */
export const LifeGroceriesIcon = createLifeIcon("groceries", "LifeGroceriesIcon");
/** Reading. Hover: a page turns. */
export const LifeReadingIcon = createLifeIcon("reading", "LifeReadingIcon");
/** Writing. Hover: the nib writes. */
export const LifeWritingIcon = createLifeIcon("writing", "LifeWritingIcon");
/** Study. Hover: the top book slides. */
export const LifeStudyIcon = createLifeIcon("study", "LifeStudyIcon");
/** Practice. Hover: the metronome ticks. */
export const LifePracticeIcon = createLifeIcon("practice", "LifePracticeIcon");
/** Music. Hover: notes bob. */
export const LifeMusicIcon = createLifeIcon("music", "LifeMusicIcon");
/** Drawing. Hover: paint dots swell. */
export const LifeDrawingIcon = createLifeIcon("drawing", "LifeDrawingIcon");
/** Photo. Hover: lens focuses, flash blinks. */
export const LifePhotoIcon = createLifeIcon("photo", "LifePhotoIcon");
/** Podcast. Hover: sound rings out. */
export const LifePodcastIcon = createLifeIcon("podcast", "LifePodcastIcon");
/** Spent. Hover: card taps. */
export const LifeSpentIcon = createLifeIcon("spent", "LifeSpentIcon");
/** Received. Hover: money drops into the wallet. */
export const LifeReceivedIcon = createLifeIcon("received", "LifeReceivedIcon");
/** Bill. Hover: the receipt prints its lines. */
export const LifeBillIcon = createLifeIcon("bill", "LifeBillIcon");
/** Subscription. Hover: the cycle turns. */
export const LifeSubscriptionIcon = createLifeIcon("subscription", "LifeSubscriptionIcon");
/** Save. Hover: the jar fills. */
export const LifeSaveIcon = createLifeIcon("save", "LifeSaveIcon");
/** Laundry. Hover: the drum spins. */
export const LifeLaundryIcon = createLifeIcon("laundry", "LifeLaundryIcon");
/** Cleaning. Hover: a puff of mist. */
export const LifeCleaningIcon = createLifeIcon("cleaning", "LifeCleaningIcon");
/** Dishes. Hover: bubbles float up. */
export const LifeDishesIcon = createLifeIcon("dishes", "LifeDishesIcon");
/** Plants. Hover: leaves sway. */
export const LifePlantsIcon = createLifeIcon("plants", "LifePlantsIcon");
/** Pet. Hover: the paw presses. */
export const LifePetIcon = createLifeIcon("pet", "LifePetIcon");
/** Morning. Hover: the sun climbs its arc. */
export const LifeMorningIcon = createLifeIcon("morning", "LifeMorningIcon");
/** Afternoon. Hover: the sun moves on. */
export const LifeAfternoonIcon = createLifeIcon("afternoon", "LifeAfternoonIcon");
/** Evening. Hover: the sun settles to the line. */
export const LifeEveningIcon = createLifeIcon("evening", "LifeEveningIcon");
/** Late night. Hover: the moon tilts, a star glints. */
export const LifeLateNightIcon = createLifeIcon("late-night", "LifeLateNightIcon");
/** Weekend. Hover: the weekend lights up. */
export const LifeWeekendIcon = createLifeIcon("weekend", "LifeWeekendIcon");
/** Sunny. Hover: rays turn, core breathes. */
export const LifeSunnyIcon = createLifeIcon("sunny", "LifeSunnyIcon");
/** Rain. Hover: drops fall. */
export const LifeRainIcon = createLifeIcon("rain", "LifeRainIcon");
/** Cold. Hover: the flake turns. */
export const LifeColdIcon = createLifeIcon("cold", "LifeColdIcon");
/** Hot. Hover: heat shimmers. */
export const LifeHotIcon = createLifeIcon("hot", "LifeHotIcon");
