// Generated by scripts/build-icons.mjs from tokens/tokens.json. Do not edit.
/** A feelings tint family (tokens.json foundations.tint). The stroke carries it; words never do. */
export type TintName = "ember" | "blush" | "tide" | "spark" | "graphite" | "dusk" | "iris";
export const TINT_NAMES: readonly TintName[] = ["ember","blush","tide","spark","graphite","dusk","iris"];
